Design Entry;HDL Check||(null)||Checking HDL syntax of 'SpiDac.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Checking HDL syntax of 'SpiDac.vhd'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Checking HDL syntax of 'SpiDac.vhd'||(null);(null)||(null);(null)
HelpInfo,C:\Microchip\Libero_SoC_v2023.2\SynplifyPro\lib\html,fpgahelp.qhc,synerrmsg.mp,C:\Microchip\Libero_SoC_v2023.2\SynplifyPro\bin\assistant
