ESC FilterWheel C++ Source: CGraphFWHardwareInterface.cpp File Reference
CGraphFWHardwareInterface.cpp File Reference
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include "CGraphFWHardwareInterface.hpp"
Variables
CGraphFWHardwareInterface * FW = (CGraphFWHardwareInterface*)0x50000000UL
Variable Documentation
FW
CGraphFWHardwareInterface* FW = (CGraphFWHardwareInterface*)0x50000000UL
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 16 of file CGraphFWHardwareInterface.cpp.
Referenced by BaudDividersCommand(), BinaryFWFilterSelectCommand(), BinaryFWHardwareControlStatusCommand(), BinaryFWMotorControlStatusCommand(), BinaryFWPositionSenseControlStatusCommand(), BinaryFWPositionStepsCommand(), BinaryVersionCommand(), BISTCommand(), PinoutMonitorAdc::busy(), FW_pinout_FPGAUart3::dataready(), FW_pinout_FPGAUart2::dataready(), FW_pinout_FPGAUart1::dataready(), FW_pinout_FPGAUart0::dataready(), FW_pinout_FPGAUartUsb::dataready(), FW_pinout_FPGAUartGps::dataready(), FW_pinout_FPGAUart3::depth(), FW_pinout_FPGAUart2::depth(), FW_pinout_FPGAUart1::depth(), FW_pinout_FPGAUart0::depth(), FW_pinout_FPGAUartUsb::depth(), FW_pinout_FPGAUartGps::depth(), PinoutMonitorAdc::enable(), FilterSelectCommand(), FWHome(), FWSeekPosition(), FWStatusCommand(), FW_pinout_FPGAUart3::getcqq(), FW_pinout_FPGAUart2::getcqq(), FW_pinout_FPGAUart1::getcqq(), FW_pinout_FPGAUart0::getcqq(), FW_pinout_FPGAUartUsb::getcqq(), FW_pinout_FPGAUartGps::getcqq(), main(), MotorCommand(), PinoutMonitorAdc::nDrdy(), FW_pinout_FPGAUart3::putcqq(), FW_pinout_FPGAUart2::putcqq(), FW_pinout_FPGAUart1::putcqq(), FW_pinout_FPGAUart0::putcqq(), FW_pinout_FPGAUartUsb::putcqq(), FW_pinout_FPGAUartGps::putcqq(), PinoutMonitorAdc::receive(), SensorStepsCommand(), PinoutMonitorAdc::transmit(), ValidatedFWHomeStep(), and ValidateFWPostition().