ESC FilterWheel C++ Source: IUart Class Reference
IUart Class Reference abstract
Copyright (c) by Franks Development, LLC.
#include <IUart.h>
Public Member Functions
IUart ()
virtual ~IUart ()
virtual bool dataready () const =0
virtual char getcqq ()=0
virtual char putcqq (char c)=0
virtual void flushoutput ()=0
virtual void purgeinput ()=0
virtual bool isopen () const =0
void puts (const char *s, const size_t len)
Static Public Attributes
static const bool OddParity = true
static const bool NoParity = false
static const bool IUartOK = 0x00
static const bool UseRTSCTS = true
static const bool NoRTSCTS = false
Detailed Description
Copyright (c) by Franks Development, LLC.
Definition at line 31 of file IUart.h.
Constructor & Destructor Documentation
IUart()
IUart::IUart () inline
Definition at line 34 of file IUart.h.
Referenced by FW_pinout_FPGAUart0::FW_pinout_FPGAUart0(), FW_pinout_FPGAUart1::FW_pinout_FPGAUart1(), FW_pinout_FPGAUart2::FW_pinout_FPGAUart2(), FW_pinout_FPGAUart3::FW_pinout_FPGAUart3(), FW_pinout_FPGAUartGps::FW_pinout_FPGAUartGps(), FW_pinout_FPGAUartUsb::FW_pinout_FPGAUartUsb(), linux_pinout_circular_buffer< BufferT, BufferLen >::linux_pinout_circular_buffer(), linux_pinout_client_socket::linux_pinout_client_socket(), linux_pinout_file::linux_pinout_file(), linux_pinout_named_pipe::linux_pinout_named_pipe(), linux_pinout_server_socket::linux_pinout_server_socket(), linux_pinout_stdio::linux_pinout_stdio(), linux_pinout_uart::linux_pinout_uart(), and win32_pinout_uart::win32_pinout_uart().
~IUart()
virtual IUart::~IUart () inline virtual
Definition at line 35 of file IUart.h.
Member Function Documentation
dataready()
virtual bool IUart::dataready () const pure virtual
Implemented in win32_pinout_uart, linux_pinout_uart, linux_pinout_server_socket, linux_pinout_named_pipe, linux_pinout_file, linux_pinout_client_socket, linux_pinout_circular_uart< BufferT, RxBufferLen, TxBufferLen >, linux_pinout_circular_buffer< BufferT, BufferLen >, linux_pinout_circular_buffer< BufferT, BufferLen >, FW_pinout_FPGAUartGps, FW_pinout_FPGAUartUsb, FW_pinout_FPGAUart0, FW_pinout_FPGAUart1, FW_pinout_FPGAUart2, and FW_pinout_FPGAUart3.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetc(), and BinaryUart::Process().
flushoutput()
virtual void IUart::flushoutput () pure virtual
Implemented in win32_pinout_uart, linux_pinout_uart, linux_pinout_server_socket, linux_pinout_named_pipe, linux_pinout_file, linux_pinout_client_socket, linux_pinout_circular_uart< BufferT, RxBufferLen, TxBufferLen >, linux_pinout_circular_buffer< BufferT, BufferLen >, FW_pinout_FPGAUartGps, FW_pinout_FPGAUartUsb, FW_pinout_FPGAUart0, FW_pinout_FPGAUart1, FW_pinout_FPGAUart2, and FW_pinout_FPGAUart3.
getcqq()
virtual char IUart::getcqq () pure virtual
Implemented in win32_pinout_uart, linux_pinout_uart, linux_pinout_stdio, linux_pinout_server_socket, linux_pinout_named_pipe, linux_pinout_file, linux_pinout_client_socket, linux_pinout_circular_uart< BufferT, RxBufferLen, TxBufferLen >, linux_pinout_circular_buffer< BufferT, BufferLen >, linux_pinout_circular_buffer< BufferT, BufferLen >, FW_pinout_FPGAUartGps, FW_pinout_FPGAUartUsb, FW_pinout_FPGAUart0, FW_pinout_FPGAUart1, FW_pinout_FPGAUart2, and FW_pinout_FPGAUart3.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::get(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetc(), and BinaryUart::Process().
isopen()
virtual bool IUart::isopen () const pure virtual
Implemented in win32_pinout_uart, linux_pinout_uart, linux_pinout_server_socket, linux_pinout_named_pipe, linux_pinout_file, linux_pinout_client_socket, linux_pinout_circular_uart< BufferT, RxBufferLen, TxBufferLen >, linux_pinout_circular_buffer< BufferT, BufferLen >, linux_pinout_circular_buffer< BufferT, BufferLen >, FW_pinout_FPGAUartGps, FW_pinout_FPGAUartUsb, FW_pinout_FPGAUart0, FW_pinout_FPGAUart1, FW_pinout_FPGAUart2, and FW_pinout_FPGAUart3.
purgeinput()
virtual void IUart::purgeinput () pure virtual
Implemented in win32_pinout_uart, linux_pinout_uart, linux_pinout_server_socket, linux_pinout_named_pipe, linux_pinout_file, linux_pinout_client_socket, linux_pinout_circular_uart< BufferT, RxBufferLen, TxBufferLen >, linux_pinout_circular_buffer< BufferT, BufferLen >, FW_pinout_FPGAUartGps, FW_pinout_FPGAUartUsb, FW_pinout_FPGAUart0, FW_pinout_FPGAUart1, FW_pinout_FPGAUart2, and FW_pinout_FPGAUart3.
putcqq()
virtual char IUart::putcqq (char c) pure virtual
Implemented in win32_pinout_uart, linux_pinout_uart, linux_pinout_stdio, linux_pinout_server_socket, linux_pinout_named_pipe, linux_pinout_file, linux_pinout_client_socket, FW_pinout_FPGAUartGps, FW_pinout_FPGAUartUsb, FW_pinout_FPGAUart0, FW_pinout_FPGAUart1, FW_pinout_FPGAUart2, FW_pinout_FPGAUart3, linux_pinout_circular_uart< BufferT, RxBufferLen, TxBufferLen >, linux_pinout_circular_buffer< BufferT, BufferLen >, and linux_pinout_circular_buffer< BufferT, BufferLen >.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetc(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessTx(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::put().
puts()
void IUart::puts (const char * s, const size_t len) inline
Definition at line 59 of file IUart.h.
Member Data Documentation
IUartOK
const bool IUart::IUartOK = 0x00 static
Definition at line 39 of file IUart.h.
Referenced by linux_pinout_client_socket::init(), win32_pinout_uart::init(), linux_pinout_uart::init(), linux_pinout_server_socket::init(), linux_pinout_file::init(), FW_pinout_FPGAUart2::init(), FW_pinout_FPGAUart1::init(), FW_pinout_FPGAUart0::init(), linux_pinout_circular_buffer< BufferT, BufferLen >::init(), linux_pinout_circular_uart< BufferT, RxBufferLen, TxBufferLen >::init(), FW_pinout_FPGAUart3::init(), FW_pinout_FPGAUartGps::init(), FW_pinout_FPGAUartUsb::init(), linux_pinout_named_pipe::init(), and linux_pinout_server_socket::SocketConnect().
NoParity
const bool IUart::NoParity = false static
Definition at line 38 of file IUart.h.
NoRTSCTS
const bool IUart::NoRTSCTS = false static
Definition at line 41 of file IUart.h.
OddParity
const bool IUart::OddParity = true static
Definition at line 37 of file IUart.h.
UseRTSCTS
const bool IUart::UseRTSCTS = true static
Definition at line 40 of file IUart.h.
The documentation for this class was generated from the following file:
IUart.h