ESC FilterWheel C++ Source: CmdTableBinary.hpp File Reference
CmdTableBinary.hpp File Reference
#include <stdint.h>
#include "dbg/memwatch.h"
#include "uart/CmdSystem.hpp"
Functions
int8_t BinaryVersionCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t BinaryFWHardwareControlStatusCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t BinaryFWMotorControlStatusCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t BinaryFWPositionSenseControlStatusCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t BinaryFWPositionStepsCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t BinaryFWTelemetryADCCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t BinaryFWFilterSelectCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
Variables
const BinaryCmd BinaryCmds []
The actual table (array) of commands for the system - links with CmdSystem.cpp.o.
const uint8_t NumBinaryCmds
Function Documentation
BinaryFWFilterSelectCommand()
int8_t BinaryFWFilterSelectCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 203 of file CmdHandlersBinary.cpp.
References CGraphPayloadTypeFWFilterSelect, CGraphFWMotorControlStatusRegister::CurrentStep, FW, FWHome(), FWMaxPosition, FWPosition, FWSeekPosition(), CGraphFWHardwareInterface::MotorControlStatus, CGraphFWMotorControlStatusRegister::SeekStep, TxBinaryPacket(), and ValidateFWPostition().
BinaryFWHardwareControlStatusCommand()
int8_t BinaryFWHardwareControlStatusCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 62 of file CmdHandlersBinary.cpp.
References CGraphPayloadTypeFWHardwareControlStatus, CGraphFWHardwareInterface::ControlRegister, CGraphFWHardwareControlRegister::formatf(), FW, and TxBinaryPacket().
BinaryFWMotorControlStatusCommand()
int8_t BinaryFWMotorControlStatusCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 86 of file CmdHandlersBinary.cpp.
References CGraphPayloadTypeFWMotorControlStatus, CGraphFWMotorControlStatusRegister::formatf(), FW, CGraphFWHardwareInterface::MotorControlStatus, and TxBinaryPacket().
BinaryFWPositionSenseControlStatusCommand()
int8_t BinaryFWPositionSenseControlStatusCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 110 of file CmdHandlersBinary.cpp.
References CGraphPayloadTypeFWPositionSenseControlStatus, CGraphFWPositionSenseRegister::formatf(), FW, CGraphFWHardwareInterface::PositionSensors, and TxBinaryPacket().
BinaryFWPositionStepsCommand()
int8_t BinaryFWPositionStepsCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 123 of file CmdHandlersBinary.cpp.
References CGraphPayloadTypeFWPositionSteps, CGraphFWPositionStepRegister::formatf(), FW, CGraphFWPositionStepRegister::OffStep, CGraphFWPositionStepRegister::OnStep, CGraphFWHardwareInterface::PosDet0A, CGraphFWHardwareInterface::PosDet0B, CGraphFWHardwareInterface::PosDet1A, CGraphFWHardwareInterface::PosDet1B, CGraphFWHardwareInterface::PosDet2A, CGraphFWHardwareInterface::PosDet2B, CGraphFWHardwareInterface::PosDet3A, CGraphFWHardwareInterface::PosDet3B, CGraphFWHardwareInterface::PosDet4A, CGraphFWHardwareInterface::PosDet4B, CGraphFWHardwareInterface::PosDet5A, CGraphFWHardwareInterface::PosDet5B, CGraphFWHardwareInterface::PosDet6A, CGraphFWHardwareInterface::PosDet6B, CGraphFWHardwareInterface::PosDet7A, CGraphFWHardwareInterface::PosDet7B, CGraphFWHardwareInterface::PosDetA0, CGraphFWHardwareInterface::PosDetA1, CGraphFWHardwareInterface::PosDetA2, CGraphFWHardwareInterface::PosDetB0, CGraphFWHardwareInterface::PosDetB1, CGraphFWHardwareInterface::PosDetB2, CGraphFWHardwareInterface::PosDetHomeA, CGraphFWHardwareInterface::PosDetHomeB, and TxBinaryPacket().
BinaryFWTelemetryADCCommand()
int8_t BinaryFWTelemetryADCCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 164 of file CmdHandlersBinary.cpp.
References CGraphPayloadTypeFWTelemetry, CGraphFWMonitorAdc::GetP1V2(), CGraphFWMonitorAdc::GetP28V(), CGraphFWMonitorAdc::GetP2I2(), CGraphFWMonitorAdc::GetP2V2(), CGraphFWMonitorAdc::GetP2V5(), CGraphFWMonitorAdc::GetP3V3D(), CGraphFWMonitorAdc::GetP4I3(), CGraphFWMonitorAdc::GetP4V3(), CGraphFWMonitorAdc::GetP5V(), CGraphFWMonitorAdc::GetP6I(), CGraphFWMonitorAdc::GetP6V(), MonitorAdc, CGraphFWTelemetryPayload::P1V2, CGraphFWTelemetryPayload::P28V, CGraphFWTelemetryPayload::P2I2, CGraphFWTelemetryPayload::P2V2, CGraphFWTelemetryPayload::P2V5, CGraphFWTelemetryPayload::P3V3D, CGraphFWTelemetryPayload::P4I3, CGraphFWTelemetryPayload::P4V3, CGraphFWTelemetryPayload::P5V, CGraphFWTelemetryPayload::P6I, CGraphFWTelemetryPayload::P6V, and TxBinaryPacket().
BinaryVersionCommand()
int8_t BinaryVersionCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 42 of file CmdHandlersBinary.cpp.
References CGraphPayloadTypeVersion, CGraphFWHardwareInterface::DeviceSerialNumber, CGraphVersionPayload::formatf(), CGraphVersionPayload::FPGAFirmwareBuildNum, CGraphFWHardwareInterface::FpgaFirmwareBuildNumber, FW, CGraphVersionPayload::ProcessorFirmwareBuildNum, CGraphVersionPayload::SerialNum, and TxBinaryPacket().
Variable Documentation
BinaryCmds
const BinaryCmd BinaryCmds[] extern
The actual table (array) of commands for the system - links with CmdSystem.cpp.o.
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 18 of file CmdTableBinary.cpp.
NumBinaryCmds
const uint8_t NumBinaryCmds extern
Definition at line 62 of file CmdTableBinary.cpp.