ESC FilterWheel C++ Source: DelayLinux.cpp File Reference
DelayLinux.cpp File Reference
#include <sched.h>
#include <unistd.h>
#include <string.h>
#include <sys/time.h>
#include <time.h>
#include <errno.h>
#include "Delay.h"
Functions
void delayus (const unsigned long microseconds)
Copyright (c) by Franks Development, LLC.
void delayms (const unsigned long milliseconds)
void delays (const unsigned long seconds)
Function Documentation
delayms()
void delayms (const unsigned long milliseconds)
Definition at line 65 of file DelayLinux.cpp.
References delayus().
Referenced by delays(), FWHome(), FWSeekPosition(), and ValidateFWPostition().
delays()
void delays (const unsigned long seconds)
Definition at line 70 of file DelayLinux.cpp.
References delayms().
delayus()
void delayus (const unsigned long microseconds)
Copyright (c) by Franks Development, LLC.
This abstraction implements the Delay Bus; derive class to adapt it to your uC/hardware
Definition at line 41 of file DelayLinux.cpp.
Referenced by ads1258< spipinout >::ConvertOnceDiff(), delayms(), ads1258< spipinout >::Init(), FW_pinout_FPGAUart3::putcqq(), FW_pinout_FPGAUart2::putcqq(), FW_pinout_FPGAUart1::putcqq(), FW_pinout_FPGAUart0::putcqq(), FW_pinout_FPGAUartUsb::putcqq(), FW_pinout_FPGAUartGps::putcqq(), lt244x< pinout, spi, SpiClkDiv >::ReadChannel(), ads1258< spipinout >::spi_busmsg::spi_busmsg(), lt244x< pinout, spi, SpiClkDiv >::StillConverting(), lt244x< pinout, spi, SpiClkDiv >::XferData(), and ads1258< spipinout >::spi_busmsg::~spi_busmsg().