ESC FilterWheel C++ Source: FilterWheel.hpp File Reference
FilterWheel.hpp File Reference
#include <stdint.h>
Functions
int16_t ValidatedFWHomeStep ()
void FWHome ()
void FWSeekPosition (const uint32_t SeekPos)
bool ValidateFWPostition ()
Variables
const uint16_t MotorFindHomeSteps = 750
const uint16_t MotorFullCircleSteps = 730
const uint16_t MotorFindHomeTimeoutMs = 1000
const uint16_t MotorSunSafeStep = 135
const uint32_t FWMaxPosition = 8
uint32_t FWPosition
Function Documentation
FWHome()
void FWHome ()
Definition at line 129 of file Main.cpp.
References CGraphFWHardwareInterface::ControlRegister, delayms(), CGraphFWPositionStepRegister::formatf(), FW, FWPosition, CGraphFWHardwareInterface::MotorControlStatus, CGraphFWHardwareControlRegister::MotorEnable, MotorFindHomeSteps, CGraphFWHardwareInterface::PosDetHomeA, CGraphFWHardwareInterface::PosDetHomeB, CGraphFWHardwareControlRegister::PosLedsEnA, CGraphFWHardwareControlRegister::PosLedsEnB, CGraphFWHardwareControlRegister::ResetSteps, CGraphFWMotorControlStatusRegister::SeekStep, and ValidatedFWHomeStep().
Referenced by BinaryFWFilterSelectCommand(), FilterSelectCommand(), FWSeekPosition(), and ValidateFWPostition().
FWSeekPosition()
void FWSeekPosition (const uint32_t SeekPos)
Definition at line 231 of file Main.cpp.
References CGraphFWHardwareInterface::ControlRegister, delayms(), FW, FWHome(), FWMaxPosition, FWPosition, CGraphFWHardwareInterface::MotorControlStatus, CGraphFWHardwareControlRegister::MotorEnable, MotorFullCircleSteps, MotorSunSafeStep, CGraphFWHardwareControlRegister::PosLedsEnA, CGraphFWHardwareControlRegister::PosLedsEnB, and CGraphFWMotorControlStatusRegister::SeekStep.
Referenced by BinaryFWFilterSelectCommand(), and FilterSelectCommand().
ValidatedFWHomeStep()
int16_t ValidatedFWHomeStep ()
Definition at line 79 of file Main.cpp.
References CGraphFWPositionStepRegister::formatf(), FW, CGraphFWPositionStepRegister::MidStep(), MotorFullCircleSteps, CGraphFWPositionStepRegister::OffStep, CGraphFWPositionStepRegister::OnStep, CGraphFWHardwareInterface::PosDetHomeA, and CGraphFWHardwareInterface::PosDetHomeB.
Referenced by FWHome().
ValidateFWPostition()
bool ValidateFWPostition ()
Definition at line 302 of file Main.cpp.
References CGraphFWHardwareInterface::ControlRegister, CGraphFWMotorControlStatusRegister::CurrentStep, delayms(), CGraphFWPositionSenseRegister::formatf(), FW, FWHome(), FWMaxPosition, FWPosition, CGraphFWHardwareInterface::MotorControlStatus, CGraphFWHardwareControlRegister::MotorEnable, MotorSunSafeStep, CGraphFWHardwareInterface::PositionSensors, CGraphFWHardwareControlRegister::PosLedsEnA, CGraphFWHardwareControlRegister::PosLedsEnB, CGraphFWPositionSenseRegister::PosSenseBit0A, CGraphFWPositionSenseRegister::PosSenseBit0B, CGraphFWPositionSenseRegister::PosSenseBit1A, CGraphFWPositionSenseRegister::PosSenseBit1B, CGraphFWPositionSenseRegister::PosSenseBit2A, CGraphFWPositionSenseRegister::PosSenseBit2B, CGraphFWPositionSenseRegister::PosSenseHomeA, CGraphFWPositionSenseRegister::PosSenseHomeB, and CGraphFWMotorControlStatusRegister::SeekStep.
Referenced by BinaryFWFilterSelectCommand(), and FilterSelectCommand().
Variable Documentation
FWMaxPosition
const uint32_t FWMaxPosition = 8
Definition at line 18 of file FilterWheel.hpp.
Referenced by BinaryFWFilterSelectCommand(), FilterSelectCommand(), FWSeekPosition(), and ValidateFWPostition().
FWPosition
uint32_t FWPosition extern
Definition at line 77 of file Main.cpp.
Referenced by BinaryFWFilterSelectCommand(), FilterSelectCommand(), FWHome(), FWSeekPosition(), and ValidateFWPostition().
MotorFindHomeSteps
const uint16_t MotorFindHomeSteps = 750
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 12 of file FilterWheel.hpp.
Referenced by FWHome().
MotorFindHomeTimeoutMs
const uint16_t MotorFindHomeTimeoutMs = 1000
Definition at line 15 of file FilterWheel.hpp.
MotorFullCircleSteps
const uint16_t MotorFullCircleSteps = 730
Definition at line 13 of file FilterWheel.hpp.
Referenced by FWSeekPosition(), and ValidatedFWHomeStep().
MotorSunSafeStep
const uint16_t MotorSunSafeStep = 135
Definition at line 16 of file FilterWheel.hpp.
Referenced by FWSeekPosition(), and ValidateFWPostition().