ESC FilterWheel C++ Source: Main.cpp File Reference
Main.cpp File Reference
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <sys/types.h>
#include <algorithm>
#include "hal/hal.h"
#include "hal/hal_assert.h"
#include "Filterwheel_hw_platform.h"
#include "Delay.h"
#include "cgraph/CGraphFWHardwareInterface.hpp"
#include "format/formatf.h"
#include "CmdTableAscii.hpp"
#include "uart/BinaryUart.hpp"
#include "uart/linux_pinout_circular_uart.hpp"
#include "FlightComms.hpp"
#include "uart/TerminalUart.hpp"
#include "../MonitorAdc.hpp"
#include "FilterWheel.hpp"
#include "arm/armdelay.h"
Functions
const char * TerminalUartPrompt ()
TerminalUart< 16, 4096 > DbgUartUsb (FPGAUartPinoutUsb, AsciiCmds, NumAsciiCmds, &TerminalUartPrompt, NoRTS, NoPrefix, false)
TerminalUart< 16, 4096 > DbgUart485_0 (FPGAUartPinout0, AsciiCmds, NumAsciiCmds, &TerminalUartPrompt, NoRTS, NoPrefix, false)
int16_t ValidatedFWHomeStep ()
void FWHome ()
void FWSeekPosition (const uint32_t SeekPos)
bool ValidateFWPostition ()
void wooinit (void) __attribute__((constructor))
int stdio_hook_putc (int c)
void asm_hard_fault_handler_c_container ()
void hard_fault_handler_c (unsigned int *hardfault_args)
void AtExit ()
void mwOutFunc (int c)
bool Process ()
void ProcessAllUarts ()
int main (int argc, char *argv[])
void delayus (const unsigned long microseconds)
Copyright (c) by Franks Development, LLC.
void delayms (const unsigned long milliseconds)
void delays (const unsigned long seconds)
uint32_t CRC32 (const uint8_t *data, const size_t length)
Variables
CGraphFWHardwareInterface * FW
FPGABinaryUartCallbacks PacketCallbacks
CGraphPacket FPGAUartProtocol
FW_pinout_FPGAUart0 FPGAUartPinout0
FW_pinout_FPGAUart1 FPGAUartPinout1
FW_pinout_FPGAUart2 FPGAUartPinout2
FW_pinout_FPGAUart3 FPGAUartPinout3
FW_pinout_FPGAUartUsb FPGAUartPinoutUsb
linux_pinout_circular_uart< char, 16, 512 > UsbUartAscii
linux_pinout_circular_uart< char, 16, 256 > UsbUartBinary
BinaryUart FpgaUartParser3 (FPGAUartPinout1, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, PacketCallbacks, false)
BinaryUart FpgaUartParser2 (FPGAUartPinout2, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, PacketCallbacks, false)
BinaryUart FpgaUartParser1 (FPGAUartPinout1, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, PacketCallbacks, false)
BinaryUart FpgaUartParserUsb (UsbUartBinary, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, PacketCallbacks, false)
char prompt [] = "\n\nESC-FW> "
CGraphFWMonitorAdc MonitorAdc
uint32_t FWPosition = (uint32_t)-1
Function Documentation
asm_hard_fault_handler_c_container()
void asm_hard_fault_handler_c_container ()
Definition at line 419 of file Main.cpp.
AtExit()
void AtExit ()
Definition at line 484 of file Main.cpp.
CRC32()
uint32_t CRC32 (const uint8_t * data, const size_t length)
Definition at line 707 of file Main.cpp.
DbgUart485_0()
TerminalUart<16, 4096> DbgUart485_0 (FPGAUartPinout0 , AsciiCmds , NumAsciiCmds , & TerminalUartPrompt, NoRTS , NoPrefix , false)
DbgUartUsb()
TerminalUart<16, 4096> DbgUartUsb (FPGAUartPinoutUsb , AsciiCmds , NumAsciiCmds , & TerminalUartPrompt, NoRTS , NoPrefix , false)
delayms()
void delayms (const unsigned long milliseconds)
Definition at line 691 of file Main.cpp.
delays()
void delays (const unsigned long seconds)
Definition at line 696 of file Main.cpp.
delayus()
void delayus (const unsigned long microseconds)
Copyright (c) by Franks Development, LLC.
This abstraction implements the Delay Bus; derive class to adapt it to your uC/hardware
Definition at line 683 of file Main.cpp.
FWHome()
void FWHome ()
Definition at line 129 of file Main.cpp.
References CGraphFWHardwareInterface::ControlRegister, delayms(), CGraphFWPositionStepRegister::formatf(), FW, FWPosition, CGraphFWHardwareInterface::MotorControlStatus, CGraphFWHardwareControlRegister::MotorEnable, MotorFindHomeSteps, CGraphFWHardwareInterface::PosDetHomeA, CGraphFWHardwareInterface::PosDetHomeB, CGraphFWHardwareControlRegister::PosLedsEnA, CGraphFWHardwareControlRegister::PosLedsEnB, CGraphFWHardwareControlRegister::ResetSteps, CGraphFWMotorControlStatusRegister::SeekStep, and ValidatedFWHomeStep().
Referenced by BinaryFWFilterSelectCommand(), FilterSelectCommand(), FWSeekPosition(), and ValidateFWPostition().
FWSeekPosition()
void FWSeekPosition (const uint32_t SeekPos)
Definition at line 231 of file Main.cpp.
References CGraphFWHardwareInterface::ControlRegister, delayms(), FW, FWHome(), FWMaxPosition, FWPosition, CGraphFWHardwareInterface::MotorControlStatus, CGraphFWHardwareControlRegister::MotorEnable, MotorFullCircleSteps, MotorSunSafeStep, CGraphFWHardwareControlRegister::PosLedsEnA, CGraphFWHardwareControlRegister::PosLedsEnB, and CGraphFWMotorControlStatusRegister::SeekStep.
Referenced by BinaryFWFilterSelectCommand(), and FilterSelectCommand().
hard_fault_handler_c()
void hard_fault_handler_c (unsigned int * hardfault_args)
Definition at line 438 of file Main.cpp.
main()
int main (int argc, char * argv[])
Definition at line 539 of file Main.cpp.
References CGraphFWHardwareInterface::ControlRegister, FPGAUartPinout0, FPGAUartPinoutUsb, FW, CGraphFWMonitorAdc::Init(), MonitorAdc, CGraphFWHardwareControlRegister::MotorEnable, CGraphFWHardwareControlRegister::PosLedsEnA, CGraphFWHardwareControlRegister::PosLedsEnB, Process(), FW_pinout_FPGAUart0::putcqq(), FW_pinout_FPGAUartUsb::putcqq(), CGraphFWHardwareControlRegister::ResetSteps, and CGraphFWMonitorAdc::SetMonitor().
mwOutFunc()
void mwOutFunc (int c)
Definition at line 490 of file Main.cpp.
Process()
bool Process ()
Definition at line 496 of file Main.cpp.
References FpgaUartParser1, FpgaUartParser2, FpgaUartParser3, FpgaUartParserUsb, MonitorAdc, CGraphFWMonitorAdc::Process(), and BinaryUart::Process().
Referenced by main().
ProcessAllUarts()
void ProcessAllUarts ()
Definition at line 528 of file Main.cpp.
References FpgaUartParser1, FpgaUartParser2, FpgaUartParser3, FpgaUartParserUsb, and BinaryUart::Process().
stdio_hook_putc()
int stdio_hook_putc (int c)
Definition at line 408 of file Main.cpp.
References FPGAUartPinout0, FPGAUartPinoutUsb, FW_pinout_FPGAUart0::putcqq(), and FW_pinout_FPGAUartUsb::putcqq().
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetc().
TerminalUartPrompt()
const char* TerminalUartPrompt ()
Definition at line 64 of file Main.cpp.
References prompt.
ValidatedFWHomeStep()
int16_t ValidatedFWHomeStep ()
Definition at line 79 of file Main.cpp.
References CGraphFWPositionStepRegister::formatf(), FW, CGraphFWPositionStepRegister::MidStep(), MotorFullCircleSteps, CGraphFWPositionStepRegister::OffStep, CGraphFWPositionStepRegister::OnStep, CGraphFWHardwareInterface::PosDetHomeA, and CGraphFWHardwareInterface::PosDetHomeB.
Referenced by FWHome().
ValidateFWPostition()
bool ValidateFWPostition ()
Definition at line 302 of file Main.cpp.
References CGraphFWHardwareInterface::ControlRegister, CGraphFWMotorControlStatusRegister::CurrentStep, delayms(), CGraphFWPositionSenseRegister::formatf(), FW, FWHome(), FWMaxPosition, FWPosition, CGraphFWHardwareInterface::MotorControlStatus, CGraphFWHardwareControlRegister::MotorEnable, MotorSunSafeStep, CGraphFWHardwareInterface::PositionSensors, CGraphFWHardwareControlRegister::PosLedsEnA, CGraphFWHardwareControlRegister::PosLedsEnB, CGraphFWPositionSenseRegister::PosSenseBit0A, CGraphFWPositionSenseRegister::PosSenseBit0B, CGraphFWPositionSenseRegister::PosSenseBit1A, CGraphFWPositionSenseRegister::PosSenseBit1B, CGraphFWPositionSenseRegister::PosSenseBit2A, CGraphFWPositionSenseRegister::PosSenseBit2B, CGraphFWPositionSenseRegister::PosSenseHomeA, CGraphFWPositionSenseRegister::PosSenseHomeB, and CGraphFWMotorControlStatusRegister::SeekStep.
Referenced by BinaryFWFilterSelectCommand(), and FilterSelectCommand().
wooinit()
void wooinit (void) const
Variable Documentation
FpgaUartParser1
BinaryUart FpgaUartParser1(FPGAUartPinout1, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, PacketCallbacks, false) (FPGAUartPinout1 , FPGAUartProtocol , BinaryCmds , NumBinaryCmds , PacketCallbacks , false)
FpgaUartParser2
BinaryUart FpgaUartParser2(FPGAUartPinout2, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, PacketCallbacks, false) (FPGAUartPinout2 , FPGAUartProtocol , BinaryCmds , NumBinaryCmds , PacketCallbacks , false)
FpgaUartParser3
BinaryUart FpgaUartParser3(FPGAUartPinout1, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, PacketCallbacks, false) (FPGAUartPinout1 , FPGAUartProtocol , BinaryCmds , NumBinaryCmds , PacketCallbacks , false)
FpgaUartParserUsb
BinaryUart FpgaUartParserUsb(UsbUartBinary, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, PacketCallbacks, false) (UsbUartBinary , FPGAUartProtocol , BinaryCmds , NumBinaryCmds , PacketCallbacks , false)
Referenced by Process(), and ProcessAllUarts().
FPGAUartPinout0
FW_pinout_FPGAUart0 FPGAUartPinout0
Definition at line 45 of file Main.cpp.
Referenced by main(), and stdio_hook_putc().
FPGAUartPinout1
FW_pinout_FPGAUart1 FPGAUartPinout1
Definition at line 46 of file Main.cpp.
FPGAUartPinout2
FW_pinout_FPGAUart2 FPGAUartPinout2
Definition at line 47 of file Main.cpp.
FPGAUartPinout3
FW_pinout_FPGAUart3 FPGAUartPinout3
Definition at line 48 of file Main.cpp.
FPGAUartPinoutUsb
FW_pinout_FPGAUartUsb FPGAUartPinoutUsb
Definition at line 49 of file Main.cpp.
Referenced by main(), and stdio_hook_putc().
FPGAUartProtocol
CGraphPacket FPGAUartProtocol
Definition at line 44 of file Main.cpp.
FW
CGraphFWHardwareInterface* FW extern
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 16 of file CGraphFWHardwareInterface.cpp.
FWPosition
uint32_t FWPosition = (uint32_t)-1
Definition at line 77 of file Main.cpp.
Referenced by BinaryFWFilterSelectCommand(), FilterSelectCommand(), FWHome(), FWSeekPosition(), and ValidateFWPostition().
MonitorAdc
CGraphFWMonitorAdc MonitorAdc extern
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
based on a framework Copyright (c) 2009 by Franks Development, LLC, used with permission
Definition at line 18 of file MonitorAdc.cpp.
PacketCallbacks
FPGABinaryUartCallbacks PacketCallbacks
Definition at line 43 of file Main.cpp.
prompt
char prompt[] = "\n\nESC-FW> "
Definition at line 63 of file Main.cpp.
Referenced by TerminalUartPrompt().
UsbUartAscii
linux_pinout_circular_uart<char, 16, 512> UsbUartAscii
Definition at line 51 of file Main.cpp.
UsbUartBinary
linux_pinout_circular_uart<char, 16, 256> UsbUartBinary
Definition at line 52 of file Main.cpp.