ESC FilterWheel C++ Source: MonitorAdc.hpp File Reference
MonitorAdc.hpp File Reference
#include <stdint.h>
#include <string.h>
#include "Delay.h"
#include "adc/ads1258.h"
#include "temp/TempLM35.hpp"
#include "format/formatf.h"
#include "cgraph/CGraphFWHardwareInterface.hpp"
Classes
struct PinoutMonitorAdc
struct MonitorAdcCalibratedInput
struct CGraphFWMonitorAdc
Macros
#define DEBUG
#define P1V2Channel ads1258details::chan_se1
#define P2V2Channel ads1258details::chan_se2
#define P28VChannel ads1258details::chan_se0
#define P2V5Channel ads1258details::chan_se7
#define P6VChannel ads1258details::chan_se10
#define P5VChannel ads1258details::chan_se11
#define P3V3DChannel ads1258details::chan_se6
#define P4V3Channel ads1258details::chan_se8
#define P2I2Channel ads1258details::chan_se3
#define P4I3Channel ads1258details::chan_se9
#define P6IChannel ads1258details::chan_se12
#define Aux0Channel ads1258details::chan_se14
#define Aux1Channel ads1258details::chan_se5
#define Aux2Channel ads1258details::chan_se4
#define AmbientLightChannel ads1258details::chan_se13
#define TemperatureChannel ads1258details::chan_se15
Functions
void ProcessAllUarts ()
int8_t ScanMonitorAdcCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t TestMonitorAdcCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t CalibrateMonitorAdcCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
Variables
CGraphFWHardwareInterface * FW
const size_t MonitorAdcFpgaAdcSampleAddr = 104
const size_t MonitorAdcFpgaAdcChannelAddr = 112
const size_t MonitorAdcFpgaSpiXferAddr = 348
const size_t MonitorAdcSpiCommandStatusRegister = 352
MonitorAdcCalibratedInput P1V2Calibrate
MonitorAdcCalibratedInput P2V2Calibrate
MonitorAdcCalibratedInput P28VCalibrate
MonitorAdcCalibratedInput P2V5Calibrate
MonitorAdcCalibratedInput P6VCalibrate
MonitorAdcCalibratedInput P5VCalibrate
MonitorAdcCalibratedInput P3V3DCalibrate
MonitorAdcCalibratedInput P4V3Calibrate
MonitorAdcCalibratedInput P2I2Calibrate
MonitorAdcCalibratedInput P4I3Calibrate
MonitorAdcCalibratedInput P6ICalibrate
MonitorAdcCalibratedInput Aux0Calibrate
MonitorAdcCalibratedInput Aux1Calibrate
MonitorAdcCalibratedInput Aux2Calibrate
MonitorAdcCalibratedInput AmbientLightCalibrate
MonitorAdcCalibratedInput TemperatureCalibrate
const char ScanMonitorAdcCmdString []
const char ScanMonitorAdcHelp []
const char TestMonitorAdcCmdString []
const char TestMonitorAdcHelp []
const char CalibrateMonitorAdcCmdString []
const char CalibrateMonitorAdcHelp []
Macro Definition Documentation
AmbientLightChannel
#define AmbientLightChannel ads1258details::chan_se13
Definition at line 191 of file MonitorAdc.hpp.
Aux0Channel
#define Aux0Channel ads1258details::chan_se14
Definition at line 188 of file MonitorAdc.hpp.
Aux1Channel
#define Aux1Channel ads1258details::chan_se5
Definition at line 189 of file MonitorAdc.hpp.
Aux2Channel
#define Aux2Channel ads1258details::chan_se4
Definition at line 190 of file MonitorAdc.hpp.
DEBUG
#define DEBUG
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
based on a framework Copyright (c) 2009 by Franks Development, LLC, used with permission
Definition at line 19 of file MonitorAdc.hpp.
P1V2Channel
#define P1V2Channel ads1258details::chan_se1
Definition at line 177 of file MonitorAdc.hpp.
P28VChannel
#define P28VChannel ads1258details::chan_se0
Definition at line 179 of file MonitorAdc.hpp.
P2I2Channel
#define P2I2Channel ads1258details::chan_se3
Definition at line 185 of file MonitorAdc.hpp.
P2V2Channel
#define P2V2Channel ads1258details::chan_se2
Definition at line 178 of file MonitorAdc.hpp.
P2V5Channel
#define P2V5Channel ads1258details::chan_se7
Definition at line 180 of file MonitorAdc.hpp.
P3V3DChannel
#define P3V3DChannel ads1258details::chan_se6
Definition at line 183 of file MonitorAdc.hpp.
P4I3Channel
#define P4I3Channel ads1258details::chan_se9
Definition at line 186 of file MonitorAdc.hpp.
P4V3Channel
#define P4V3Channel ads1258details::chan_se8
Definition at line 184 of file MonitorAdc.hpp.
P5VChannel
#define P5VChannel ads1258details::chan_se11
Definition at line 182 of file MonitorAdc.hpp.
P6IChannel
#define P6IChannel ads1258details::chan_se12
Definition at line 187 of file MonitorAdc.hpp.
P6VChannel
#define P6VChannel ads1258details::chan_se10
Definition at line 181 of file MonitorAdc.hpp.
TemperatureChannel
#define TemperatureChannel ads1258details::chan_se15
Definition at line 192 of file MonitorAdc.hpp.
Function Documentation
CalibrateMonitorAdcCommand()
int8_t CalibrateMonitorAdcCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 132 of file MonitorAdc.cpp.
References AmbientLightCalibrate, Aux0Calibrate, Aux1Calibrate, Aux2Calibrate, MonitorAdcCalibratedInput::Calibrate(), MonitorAdcCalibratedInput::GetGain(), MonitorAdcCalibratedInput::GetOffset(), P1V2Calibrate, P28VCalibrate, P2I2Calibrate, P2V2Calibrate, P2V5Calibrate, P3V3DCalibrate, P4I3Calibrate, P4V3Calibrate, P5VCalibrate, P6ICalibrate, P6VCalibrate, and TemperatureCalibrate.
ProcessAllUarts()
void ProcessAllUarts ()
Definition at line 528 of file Main.cpp.
References FpgaUartParser1, FpgaUartParser2, FpgaUartParser3, FpgaUartParserUsb, and BinaryUart::Process().
ScanMonitorAdcCommand()
int8_t ScanMonitorAdcCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 57 of file MonitorAdc.cpp.
References CGraphFWMonitorAdc::GetAmbientLight(), CGraphFWMonitorAdc::GetAux0(), CGraphFWMonitorAdc::GetAux1(), CGraphFWMonitorAdc::GetAux2(), CGraphFWMonitorAdc::GetP1V2(), CGraphFWMonitorAdc::GetP28V(), CGraphFWMonitorAdc::GetP2I2(), CGraphFWMonitorAdc::GetP2V2(), CGraphFWMonitorAdc::GetP2V5(), CGraphFWMonitorAdc::GetP3V3D(), CGraphFWMonitorAdc::GetP4I3(), CGraphFWMonitorAdc::GetP4V3(), CGraphFWMonitorAdc::GetP5V(), CGraphFWMonitorAdc::GetP6I(), CGraphFWMonitorAdc::GetP6V(), CGraphFWMonitorAdc::GetTemperature(), and MonitorAdc.
TestMonitorAdcCommand()
int8_t TestMonitorAdcCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 84 of file MonitorAdc.cpp.
References CGraphFWMonitorAdc::GetAmbientLightRaw(), CGraphFWMonitorAdc::GetAux0Raw(), CGraphFWMonitorAdc::GetAux1Raw(), CGraphFWMonitorAdc::GetAux2Raw(), CGraphFWMonitorAdc::GetP1V2Raw(), CGraphFWMonitorAdc::GetP28VRaw(), CGraphFWMonitorAdc::GetP2I2Raw(), CGraphFWMonitorAdc::GetP2V2Raw(), CGraphFWMonitorAdc::GetP2V5Raw(), CGraphFWMonitorAdc::GetP3V3DRaw(), CGraphFWMonitorAdc::GetP4I3Raw(), CGraphFWMonitorAdc::GetP4V3Raw(), CGraphFWMonitorAdc::GetP5VRaw(), CGraphFWMonitorAdc::GetP6IRaw(), CGraphFWMonitorAdc::GetP6VRaw(), CGraphFWMonitorAdc::GetTemperatureRaw(), and MonitorAdc.
Variable Documentation
AmbientLightCalibrate
MonitorAdcCalibratedInput AmbientLightCalibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetAmbientLight().
Aux0Calibrate
MonitorAdcCalibratedInput Aux0Calibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetAux0().
Aux1Calibrate
MonitorAdcCalibratedInput Aux1Calibrate extern
Referenced by CalibrateMonitorAdcCommand(), CGraphFWMonitorAdc::GetAux1(), and CGraphFWMonitorAdc::GetAux2().
Aux2Calibrate
MonitorAdcCalibratedInput Aux2Calibrate extern
Referenced by CalibrateMonitorAdcCommand().
CalibrateMonitorAdcCmdString
const char CalibrateMonitorAdcCmdString[] extern
Definition at line 130 of file MonitorAdc.cpp.
CalibrateMonitorAdcHelp
const char CalibrateMonitorAdcHelp[] extern
Definition at line 131 of file MonitorAdc.cpp.
FW
CGraphFWHardwareInterface* FW extern
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 16 of file CGraphFWHardwareInterface.cpp.
MonitorAdcFpgaAdcChannelAddr
const size_t MonitorAdcFpgaAdcChannelAddr = 112
Definition at line 31 of file MonitorAdc.hpp.
MonitorAdcFpgaAdcSampleAddr
const size_t MonitorAdcFpgaAdcSampleAddr = 104
Definition at line 30 of file MonitorAdc.hpp.
MonitorAdcFpgaSpiXferAddr
const size_t MonitorAdcFpgaSpiXferAddr = 348
Definition at line 32 of file MonitorAdc.hpp.
MonitorAdcSpiCommandStatusRegister
const size_t MonitorAdcSpiCommandStatusRegister = 352
Definition at line 33 of file MonitorAdc.hpp.
P1V2Calibrate
MonitorAdcCalibratedInput P1V2Calibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetP1V2().
P28VCalibrate
MonitorAdcCalibratedInput P28VCalibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetP28V().
P2I2Calibrate
MonitorAdcCalibratedInput P2I2Calibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetP2I2().
P2V2Calibrate
MonitorAdcCalibratedInput P2V2Calibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetP2V2().
P2V5Calibrate
MonitorAdcCalibratedInput P2V5Calibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetP2V5().
P3V3DCalibrate
MonitorAdcCalibratedInput P3V3DCalibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetP3V3D().
P4I3Calibrate
MonitorAdcCalibratedInput P4I3Calibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetP4I3().
P4V3Calibrate
MonitorAdcCalibratedInput P4V3Calibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetP4V3().
P5VCalibrate
MonitorAdcCalibratedInput P5VCalibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetP5V().
P6ICalibrate
MonitorAdcCalibratedInput P6ICalibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetP6I().
P6VCalibrate
MonitorAdcCalibratedInput P6VCalibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetP6V().
ScanMonitorAdcCmdString
const char ScanMonitorAdcCmdString[] extern
Definition at line 55 of file MonitorAdc.cpp.
ScanMonitorAdcHelp
const char ScanMonitorAdcHelp[] extern
Definition at line 56 of file MonitorAdc.cpp.
TemperatureCalibrate
MonitorAdcCalibratedInput TemperatureCalibrate extern
Referenced by CalibrateMonitorAdcCommand(), and CGraphFWMonitorAdc::GetTemperature().
TestMonitorAdcCmdString
const char TestMonitorAdcCmdString[] extern
Definition at line 82 of file MonitorAdc.cpp.
TestMonitorAdcHelp
const char TestMonitorAdcHelp[] extern
Definition at line 83 of file MonitorAdc.cpp.