ESC FilterWheel C++ Source: CGraphFWMonitorAdc Struct Reference
CGraphFWMonitorAdc Struct Reference
#include <MonitorAdc.hpp>
Public Member Functions
CGraphFWMonitorAdc ()
~CGraphFWMonitorAdc ()
bool GetMonitor () const
void SetMonitor (bool monitor)
void Init ()
void Process ()
double GetP1V2 ()
double GetP2V2 ()
double GetP28V ()
double GetP2V5 ()
double GetP6V ()
double GetP5V ()
double GetP3V3D ()
double GetP4V3 ()
double GetP2I2 ()
double GetP4I3 ()
double GetP6I ()
double GetAux0 ()
double GetAux1 ()
double GetAux2 ()
double GetAmbientLight ()
double GetTemperature ()
void GetP1V2Raw (int32_t &val)
void GetP2V2Raw (int32_t &val)
void GetP28VRaw (int32_t &val)
void GetP2V5Raw (int32_t &val)
void GetP6VRaw (int32_t &val)
void GetP5VRaw (int32_t &val)
void GetP3V3DRaw (int32_t &val)
void GetP4V3Raw (int32_t &val)
void GetP2I2Raw (int32_t &val)
void GetP4I3Raw (int32_t &val)
void GetP6IRaw (int32_t &val)
void GetAux0Raw (int32_t &val)
void GetAux1Raw (int32_t &val)
void GetAux2Raw (int32_t &val)
void GetAmbientLightRaw (int32_t &val)
void GetTemperatureRaw (int32_t &val)
void SaveCals (double *Buffer, size_t &BufferMaxInBufferUsedOut)
void RestoreCals (const double *Buffer, size_t &BufferMaxInBufferUsedOut)
Public Attributes
ads1258< PinoutMonitorAdc > Adc
Private Attributes
bool AdcFound
bool Monitor
int32_t P1V2
int32_t P2V2
int32_t P28V
int32_t P2V5
int32_t P6V
int32_t P5V
int32_t P3V3D
int32_t P4V3
int32_t P2I2
int32_t P4I3
int32_t P6I
int32_t Aux0
int32_t Aux1
int32_t Aux2
int32_t AmbientLight
int32_t Temperature
Static Private Attributes
static const uint8_t GpioDirections = 0x00
static const uint8_t StartPinMask = 0x80
Detailed Description
Definition at line 129 of file MonitorAdc.hpp.
Constructor & Destructor Documentation
CGraphFWMonitorAdc()
CGraphFWMonitorAdc::CGraphFWMonitorAdc () inline
Definition at line 164 of file MonitorAdc.hpp.
References AdcFound, AmbientLight, Aux0, Aux1, Aux2, Monitor, P1V2, P28V, P2I2, P2V2, P2V5, P3V3D, P4I3, P4V3, P5V, P6I, P6V, and Temperature.
~CGraphFWMonitorAdc()
CGraphFWMonitorAdc::~CGraphFWMonitorAdc () inline
Definition at line 168 of file MonitorAdc.hpp.
Member Function Documentation
GetAmbientLight()
double CGraphFWMonitorAdc::GetAmbientLight () inline
Definition at line 327 of file MonitorAdc.hpp.
References AmbientLight, AmbientLightCalibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by ScanMonitorAdcCommand().
GetAmbientLightRaw()
void CGraphFWMonitorAdc::GetAmbientLightRaw (int32_t & val) inline
Definition at line 344 of file MonitorAdc.hpp.
References AmbientLight.
Referenced by TestMonitorAdcCommand().
GetAux0()
double CGraphFWMonitorAdc::GetAux0 () inline
Definition at line 324 of file MonitorAdc.hpp.
References Aux0, Aux0Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by ScanMonitorAdcCommand().
GetAux0Raw()
void CGraphFWMonitorAdc::GetAux0Raw (int32_t & val) inline
Definition at line 341 of file MonitorAdc.hpp.
References Aux0.
Referenced by TestMonitorAdcCommand().
GetAux1()
double CGraphFWMonitorAdc::GetAux1 () inline
Definition at line 325 of file MonitorAdc.hpp.
References Aux1, Aux1Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by ScanMonitorAdcCommand().
GetAux1Raw()
void CGraphFWMonitorAdc::GetAux1Raw (int32_t & val) inline
Definition at line 342 of file MonitorAdc.hpp.
References Aux1.
Referenced by TestMonitorAdcCommand().
GetAux2()
double CGraphFWMonitorAdc::GetAux2 () inline
Definition at line 326 of file MonitorAdc.hpp.
References Aux1Calibrate, Aux2, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by ScanMonitorAdcCommand().
GetAux2Raw()
void CGraphFWMonitorAdc::GetAux2Raw (int32_t & val) inline
Definition at line 343 of file MonitorAdc.hpp.
References Aux2.
Referenced by TestMonitorAdcCommand().
GetMonitor()
bool CGraphFWMonitorAdc::GetMonitor () const inline
Definition at line 194 of file MonitorAdc.hpp.
References Monitor.
GetP1V2()
double CGraphFWMonitorAdc::GetP1V2 () inline
Definition at line 313 of file MonitorAdc.hpp.
References P1V2, P1V2Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFWTelemetryADCCommand(), and ScanMonitorAdcCommand().
GetP1V2Raw()
void CGraphFWMonitorAdc::GetP1V2Raw (int32_t & val) inline
Definition at line 330 of file MonitorAdc.hpp.
References P1V2.
Referenced by TestMonitorAdcCommand().
GetP28V()
double CGraphFWMonitorAdc::GetP28V () inline
Definition at line 315 of file MonitorAdc.hpp.
References P28V, P28VCalibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFWTelemetryADCCommand(), and ScanMonitorAdcCommand().
GetP28VRaw()
void CGraphFWMonitorAdc::GetP28VRaw (int32_t & val) inline
Definition at line 332 of file MonitorAdc.hpp.
References P28V.
Referenced by TestMonitorAdcCommand().
GetP2I2()
double CGraphFWMonitorAdc::GetP2I2 () inline
Definition at line 321 of file MonitorAdc.hpp.
References P2I2, P2I2Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFWTelemetryADCCommand(), and ScanMonitorAdcCommand().
GetP2I2Raw()
void CGraphFWMonitorAdc::GetP2I2Raw (int32_t & val) inline
Definition at line 338 of file MonitorAdc.hpp.
References P2I2.
Referenced by TestMonitorAdcCommand().
GetP2V2()
double CGraphFWMonitorAdc::GetP2V2 () inline
Definition at line 314 of file MonitorAdc.hpp.
References P2V2, P2V2Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFWTelemetryADCCommand(), and ScanMonitorAdcCommand().
GetP2V2Raw()
void CGraphFWMonitorAdc::GetP2V2Raw (int32_t & val) inline
Definition at line 331 of file MonitorAdc.hpp.
References P2V2.
Referenced by TestMonitorAdcCommand().
GetP2V5()
double CGraphFWMonitorAdc::GetP2V5 () inline
Definition at line 316 of file MonitorAdc.hpp.
References P2V5, P2V5Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFWTelemetryADCCommand(), and ScanMonitorAdcCommand().
GetP2V5Raw()
void CGraphFWMonitorAdc::GetP2V5Raw (int32_t & val) inline
Definition at line 333 of file MonitorAdc.hpp.
References P2V5.
Referenced by TestMonitorAdcCommand().
GetP3V3D()
double CGraphFWMonitorAdc::GetP3V3D () inline
Definition at line 319 of file MonitorAdc.hpp.
References P3V3D, P3V3DCalibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFWTelemetryADCCommand(), and ScanMonitorAdcCommand().
GetP3V3DRaw()
void CGraphFWMonitorAdc::GetP3V3DRaw (int32_t & val) inline
Definition at line 336 of file MonitorAdc.hpp.
References P3V3D.
Referenced by TestMonitorAdcCommand().
GetP4I3()
double CGraphFWMonitorAdc::GetP4I3 () inline
Definition at line 322 of file MonitorAdc.hpp.
References P4I3, P4I3Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFWTelemetryADCCommand(), and ScanMonitorAdcCommand().
GetP4I3Raw()
void CGraphFWMonitorAdc::GetP4I3Raw (int32_t & val) inline
Definition at line 339 of file MonitorAdc.hpp.
References P4I3.
Referenced by TestMonitorAdcCommand().
GetP4V3()
double CGraphFWMonitorAdc::GetP4V3 () inline
Definition at line 320 of file MonitorAdc.hpp.
References P4V3, P4V3Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFWTelemetryADCCommand(), and ScanMonitorAdcCommand().
GetP4V3Raw()
void CGraphFWMonitorAdc::GetP4V3Raw (int32_t & val) inline
Definition at line 337 of file MonitorAdc.hpp.
References P4V3.
Referenced by TestMonitorAdcCommand().
GetP5V()
double CGraphFWMonitorAdc::GetP5V () inline
Definition at line 318 of file MonitorAdc.hpp.
References P5V, P5VCalibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFWTelemetryADCCommand(), and ScanMonitorAdcCommand().
GetP5VRaw()
void CGraphFWMonitorAdc::GetP5VRaw (int32_t & val) inline
Definition at line 335 of file MonitorAdc.hpp.
References P5V.
Referenced by TestMonitorAdcCommand().
GetP6I()
double CGraphFWMonitorAdc::GetP6I () inline
Definition at line 323 of file MonitorAdc.hpp.
References P6I, P6ICalibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFWTelemetryADCCommand(), and ScanMonitorAdcCommand().
GetP6IRaw()
void CGraphFWMonitorAdc::GetP6IRaw (int32_t & val) inline
Definition at line 340 of file MonitorAdc.hpp.
References P6I.
Referenced by TestMonitorAdcCommand().
GetP6V()
double CGraphFWMonitorAdc::GetP6V () inline
Definition at line 317 of file MonitorAdc.hpp.
References P6V, P6VCalibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFWTelemetryADCCommand(), and ScanMonitorAdcCommand().
GetP6VRaw()
void CGraphFWMonitorAdc::GetP6VRaw (int32_t & val) inline
Definition at line 334 of file MonitorAdc.hpp.
References P6V.
Referenced by TestMonitorAdcCommand().
GetTemperature()
double CGraphFWMonitorAdc::GetTemperature () inline
Definition at line 328 of file MonitorAdc.hpp.
References MonitorAdcCalibratedInput::ReadCalibrated(), Temperature, and TemperatureCalibrate.
Referenced by ScanMonitorAdcCommand().
GetTemperatureRaw()
void CGraphFWMonitorAdc::GetTemperatureRaw (int32_t & val) inline
Definition at line 345 of file MonitorAdc.hpp.
References Temperature.
Referenced by TestMonitorAdcCommand().
Init()
void CGraphFWMonitorAdc::Init () inline
Definition at line 197 of file MonitorAdc.hpp.
References AdcFound.
Referenced by main().
Process()
void CGraphFWMonitorAdc::Process () inline
Definition at line 249 of file MonitorAdc.hpp.
References AdcFound.
Referenced by Process().
RestoreCals()
void CGraphFWMonitorAdc::RestoreCals (const double * Buffer, size_t & BufferMaxInBufferUsedOut) inline
Definition at line 392 of file MonitorAdc.hpp.
SaveCals()
void CGraphFWMonitorAdc::SaveCals (double * Buffer, size_t & BufferMaxInBufferUsedOut) inline
Definition at line 347 of file MonitorAdc.hpp.
SetMonitor()
void CGraphFWMonitorAdc::SetMonitor (bool monitor) inline
Definition at line 195 of file MonitorAdc.hpp.
References Monitor.
Referenced by main().
Member Data Documentation
Adc
ads1258<PinoutMonitorAdc> CGraphFWMonitorAdc::Adc
Definition at line 170 of file MonitorAdc.hpp.
AdcFound
bool CGraphFWMonitorAdc::AdcFound private
Definition at line 137 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), Init(), and Process().
AmbientLight
int32_t CGraphFWMonitorAdc::AmbientLight private
Definition at line 158 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetAmbientLight(), and GetAmbientLightRaw().
Aux0
int32_t CGraphFWMonitorAdc::Aux0 private
Definition at line 155 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetAux0(), and GetAux0Raw().
Aux1
int32_t CGraphFWMonitorAdc::Aux1 private
Definition at line 156 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetAux1(), and GetAux1Raw().
Aux2
int32_t CGraphFWMonitorAdc::Aux2 private
Definition at line 157 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetAux2(), and GetAux2Raw().
GpioDirections
const uint8_t CGraphFWMonitorAdc::GpioDirections = 0x00 static private
Definition at line 141 of file MonitorAdc.hpp.
Monitor
bool CGraphFWMonitorAdc::Monitor private
Definition at line 138 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetMonitor(), and SetMonitor().
P1V2
int32_t CGraphFWMonitorAdc::P1V2 private
Definition at line 144 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetP1V2(), and GetP1V2Raw().
P28V
int32_t CGraphFWMonitorAdc::P28V private
Definition at line 146 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetP28V(), and GetP28VRaw().
P2I2
int32_t CGraphFWMonitorAdc::P2I2 private
Definition at line 152 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetP2I2(), and GetP2I2Raw().
P2V2
int32_t CGraphFWMonitorAdc::P2V2 private
Definition at line 145 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetP2V2(), and GetP2V2Raw().
P2V5
int32_t CGraphFWMonitorAdc::P2V5 private
Definition at line 147 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetP2V5(), and GetP2V5Raw().
P3V3D
int32_t CGraphFWMonitorAdc::P3V3D private
Definition at line 150 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetP3V3D(), and GetP3V3DRaw().
P4I3
int32_t CGraphFWMonitorAdc::P4I3 private
Definition at line 153 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetP4I3(), and GetP4I3Raw().
P4V3
int32_t CGraphFWMonitorAdc::P4V3 private
Definition at line 151 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetP4V3(), and GetP4V3Raw().
P5V
int32_t CGraphFWMonitorAdc::P5V private
Definition at line 149 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetP5V(), and GetP5VRaw().
P6I
int32_t CGraphFWMonitorAdc::P6I private
Definition at line 154 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetP6I(), and GetP6IRaw().
P6V
int32_t CGraphFWMonitorAdc::P6V private
Definition at line 148 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetP6V(), and GetP6VRaw().
StartPinMask
const uint8_t CGraphFWMonitorAdc::StartPinMask = 0x80 static private
Definition at line 142 of file MonitorAdc.hpp.
Temperature
int32_t CGraphFWMonitorAdc::Temperature private
Definition at line 159 of file MonitorAdc.hpp.
Referenced by CGraphFWMonitorAdc(), GetTemperature(), and GetTemperatureRaw().
The documentation for this struct was generated from the following file:
MonitorAdc.hpp