ESC FilterWheel C++ Source: linux_pinout_client_socket Class Reference
linux_pinout_client_socket Class Reference
#include <linux_pinout_client_socket.hpp>
Public Member Functions
linux_pinout_client_socket ()
virtual ~linux_pinout_client_socket ()
virtual int init (const int HostPort, const char *HostName)
virtual void deinit ()
virtual bool dataready () const
virtual char getcqq ()
virtual char putcqq (char c)
virtual void flushoutput ()
virtual void purgeinput ()
virtual bool connected () const
virtual bool isopen () const
Public Member Functions inherited from IUart
IUart ()
virtual ~IUart ()
void puts (const char *s, const size_t len)
Public Attributes
int hSocket
Additional Inherited Members
Static Public Attributes inherited from IUart
static const bool OddParity = true
static const bool NoParity = false
static const bool IUartOK = 0x00
static const bool UseRTSCTS = true
static const bool NoRTSCTS = false
Detailed Description
Definition at line 56 of file linux_pinout_client_socket.hpp.
Constructor & Destructor Documentation
linux_pinout_client_socket()
linux_pinout_client_socket::linux_pinout_client_socket () inline
Definition at line 60 of file linux_pinout_client_socket.hpp.
References hSocket, and IUart::IUart().
~linux_pinout_client_socket()
virtual linux_pinout_client_socket::~linux_pinout_client_socket () inline virtual
Definition at line 61 of file linux_pinout_client_socket.hpp.
Member Function Documentation
connected()
virtual bool linux_pinout_client_socket::connected () const inline virtual
Definition at line 266 of file linux_pinout_client_socket.hpp.
References hSocket.
Referenced by isopen().
dataready()
virtual bool linux_pinout_client_socket::dataready () const inline virtual
Implements IUart.
Definition at line 168 of file linux_pinout_client_socket.hpp.
References hSocket.
deinit()
virtual void linux_pinout_client_socket::deinit () inline virtual
Definition at line 148 of file linux_pinout_client_socket.hpp.
References hSocket.
Referenced by getcqq(), init(), and putcqq().
flushoutput()
virtual void linux_pinout_client_socket::flushoutput () inline virtual
Implements IUart.
Definition at line 246 of file linux_pinout_client_socket.hpp.
References hSocket.
getcqq()
virtual char linux_pinout_client_socket::getcqq () inline virtual
Implements IUart.
Definition at line 188 of file linux_pinout_client_socket.hpp.
References deinit(), and hSocket.
init()
virtual int linux_pinout_client_socket::init (const int HostPort, const char * HostName) inline virtual
Definition at line 63 of file linux_pinout_client_socket.hpp.
References deinit(), hSocket, and IUart::IUartOK.
isopen()
virtual bool linux_pinout_client_socket::isopen () const inline virtual
Implements IUart.
Definition at line 271 of file linux_pinout_client_socket.hpp.
References connected().
purgeinput()
virtual void linux_pinout_client_socket::purgeinput () inline virtual
Implements IUart.
Definition at line 261 of file linux_pinout_client_socket.hpp.
putcqq()
virtual char linux_pinout_client_socket::putcqq (char c) inline virtual
Implements IUart.
Definition at line 219 of file linux_pinout_client_socket.hpp.
References deinit(), and hSocket.
Member Data Documentation
hSocket
int linux_pinout_client_socket::hSocket
Definition at line 275 of file linux_pinout_client_socket.hpp.
Referenced by connected(), dataready(), deinit(), flushoutput(), getcqq(), init(), linux_pinout_client_socket(), and putcqq().
The documentation for this class was generated from the following file:
linux_pinout_client_socket.hpp