ESC FilterWheel C++ Source: FW_pinout_FPGAUart0 Class Reference
FW_pinout_FPGAUart0 Class Reference
#include <FlightComms.hpp>
Public Member Functions
FW_pinout_FPGAUart0 ()
virtual ~FW_pinout_FPGAUart0 ()
virtual int init (const uint32_t nc, const char *nc2)
virtual void deinit ()
virtual bool dataready () const
virtual char getcqq ()
virtual char putcqq (char c)
virtual size_t depth () const
virtual void flushoutput ()
virtual void purgeinput ()
virtual bool connected ()
virtual bool isopen () const
Public Member Functions inherited from IUart
IUart ()
virtual ~IUart ()
void puts (const char *s, const size_t len)
Additional Inherited Members
Static Public Attributes inherited from IUart
static const bool OddParity = true
static const bool NoParity = false
static const bool IUartOK = 0x00
static const bool UseRTSCTS = true
static const bool NoRTSCTS = false
Detailed Description
Definition at line 207 of file FlightComms.hpp.
Constructor & Destructor Documentation
FW_pinout_FPGAUart0()
FW_pinout_FPGAUart0::FW_pinout_FPGAUart0 () inline
Definition at line 211 of file FlightComms.hpp.
References IUart::IUart().
~FW_pinout_FPGAUart0()
virtual FW_pinout_FPGAUart0::~FW_pinout_FPGAUart0 () inline virtual
Definition at line 212 of file FlightComms.hpp.
Member Function Documentation
connected()
virtual bool FW_pinout_FPGAUart0::connected () inline virtual
Definition at line 253 of file FlightComms.hpp.
dataready()
virtual bool FW_pinout_FPGAUart0::dataready () const inline virtual
Implements IUart.
Definition at line 218 of file FlightComms.hpp.
References FW, CGraphFWUartStatusRegister::RxFifoEmpty, and CGraphFWHardwareInterface::UartStatusRegister0.
deinit()
virtual void FW_pinout_FPGAUart0::deinit () inline virtual
Definition at line 216 of file FlightComms.hpp.
depth()
virtual size_t FW_pinout_FPGAUart0::depth () const inline virtual
Definition at line 244 of file FlightComms.hpp.
References FW, CGraphFWUartStatusRegister::RxFifoCount, and CGraphFWHardwareInterface::UartStatusRegister0.
flushoutput()
virtual void FW_pinout_FPGAUart0::flushoutput () inline virtual
Implements IUart.
Definition at line 251 of file FlightComms.hpp.
getcqq()
virtual char FW_pinout_FPGAUart0::getcqq () inline virtual
Implements IUart.
Definition at line 225 of file FlightComms.hpp.
References FW, MonitorSerial0, CGraphFWHardwareInterface::UartFifo0, and CGraphFWHardwareInterface::UartFifo0ReadData.
init()
virtual int FW_pinout_FPGAUart0::init (const uint32_t nc, const char * nc2) inline virtual
Definition at line 214 of file FlightComms.hpp.
References IUart::IUartOK.
isopen()
virtual bool FW_pinout_FPGAUart0::isopen () const inline virtual
Implements IUart.
Definition at line 254 of file FlightComms.hpp.
purgeinput()
virtual void FW_pinout_FPGAUart0::purgeinput () inline virtual
Implements IUart.
Definition at line 252 of file FlightComms.hpp.
putcqq()
virtual char FW_pinout_FPGAUart0::putcqq (char c) inline virtual
Implements IUart.
Definition at line 236 of file FlightComms.hpp.
References delayus(), FW, and CGraphFWHardwareInterface::UartFifo0.
Referenced by main(), and stdio_hook_putc().
The documentation for this class was generated from the following file:
FlightComms.hpp