ESC FilterWheel C++ Source: FW_pinout_FPGAUartUsb Class Reference
FW_pinout_FPGAUartUsb Class Reference
#include <FlightComms.hpp>
Public Member Functions
FW_pinout_FPGAUartUsb ()
virtual ~FW_pinout_FPGAUartUsb ()
virtual int init (const uint32_t nc, const char *ncUsb)
virtual void deinit ()
virtual bool dataready () const
virtual char getcqq ()
virtual char putcqq (char c)
virtual size_t depth () const
virtual void flushoutput ()
virtual void purgeinput ()
virtual bool connected ()
virtual bool isopen () const
Public Member Functions inherited from IUart
IUart ()
virtual ~IUart ()
void puts (const char *s, const size_t len)
Additional Inherited Members
Static Public Attributes inherited from IUart
static const bool OddParity = true
static const bool NoParity = false
static const bool IUartOK = 0x00
static const bool UseRTSCTS = true
static const bool NoRTSCTS = false
Detailed Description
Definition at line 262 of file FlightComms.hpp.
Constructor & Destructor Documentation
FW_pinout_FPGAUartUsb()
FW_pinout_FPGAUartUsb::FW_pinout_FPGAUartUsb () inline
Definition at line 266 of file FlightComms.hpp.
References IUart::IUart().
~FW_pinout_FPGAUartUsb()
virtual FW_pinout_FPGAUartUsb::~FW_pinout_FPGAUartUsb () inline virtual
Definition at line 267 of file FlightComms.hpp.
Member Function Documentation
connected()
virtual bool FW_pinout_FPGAUartUsb::connected () inline virtual
Definition at line 309 of file FlightComms.hpp.
dataready()
virtual bool FW_pinout_FPGAUartUsb::dataready () const inline virtual
Implements IUart.
Definition at line 273 of file FlightComms.hpp.
References FW, CGraphFWUartStatusRegister::RxFifoEmpty, and CGraphFWHardwareInterface::UartStatusRegisterUsb.
deinit()
virtual void FW_pinout_FPGAUartUsb::deinit () inline virtual
Definition at line 271 of file FlightComms.hpp.
depth()
virtual size_t FW_pinout_FPGAUartUsb::depth () const inline virtual
Definition at line 300 of file FlightComms.hpp.
References FW, CGraphFWUartStatusRegister::RxFifoCount, and CGraphFWHardwareInterface::UartStatusRegisterUsb.
flushoutput()
virtual void FW_pinout_FPGAUartUsb::flushoutput () inline virtual
Implements IUart.
Definition at line 307 of file FlightComms.hpp.
getcqq()
virtual char FW_pinout_FPGAUartUsb::getcqq () inline virtual
Implements IUart.
Definition at line 281 of file FlightComms.hpp.
References FW, MonitorSerialUsb, CGraphFWHardwareInterface::UartFifoUsb, and CGraphFWHardwareInterface::UartFifoUsbReadData.
init()
virtual int FW_pinout_FPGAUartUsb::init (const uint32_t nc, const char * ncUsb) inline virtual
Definition at line 269 of file FlightComms.hpp.
References IUart::IUartOK.
isopen()
virtual bool FW_pinout_FPGAUartUsb::isopen () const inline virtual
Implements IUart.
Definition at line 310 of file FlightComms.hpp.
purgeinput()
virtual void FW_pinout_FPGAUartUsb::purgeinput () inline virtual
Implements IUart.
Definition at line 308 of file FlightComms.hpp.
putcqq()
virtual char FW_pinout_FPGAUartUsb::putcqq (char c) inline virtual
Implements IUart.
Definition at line 292 of file FlightComms.hpp.
References delayus(), FW, and CGraphFWHardwareInterface::UartFifoUsb.
Referenced by main(), and stdio_hook_putc().
The documentation for this class was generated from the following file:
FlightComms.hpp