ESC FilterWheel C++ Source: TerminalUart< txbufferlenbytes, rxbufferlenbytes > Struct Template Reference
TerminalUart< txbufferlenbytes, rxbufferlenbytes > Struct Template Reference
#include <TerminalUart.hpp>
Public Member Functions
char RxBuffer[rxbufferlenbytes] __attribute__ ((aligned(4)))
TerminalUart (struct IUart &pinout, const Cmd *cmds, const size_t numcmds, const char *(*terminaluartprompt)()=0, struct RTSCallback &rts=NoRTS, const char *prefix=NoPrefix, const uint16_t strlenprefix=0, const bool verbose=true)
int Init ()
void Prompt ()
void Prompt (const char *(*terminaluartprompt)())
void SetVerbose (const bool verbose)
void SetEcho (bool echostate)
void StdOutEcho (bool echostate)
void SetCrLfOrLf (bool crlf)
void SetBlockOnTxBuffFull (bool block)
void SetPrefix (const char *prefix)
void Flush ()
char put (char c)
void puts (const char *s, unsigned int maxlen=(unsigned int)(-1))
void formatf (const char *format,...)
bool ProcessTx ()
bool ProcessRx ()
bool Process ()
bool eof ()
char get ()
char maybegetc ()
int maybegetline ()
Public Attributes
fixedqueue< char, txbufferlenbytes > TxBuffer
uint16_t RxCount
uint16_t TxCount
bool Echo
bool StdEcho
char LastC
bool UseCrLf
bool BlockOnTxBuffFull
IUart & Pinout
const Cmd * Cmds
size_t NumCmds
const char *(* TerminalUartPrompt)()
RTSCallback & RTSPinout
const char * Prefix
uint16_t StrlenPrefix
bool Verbose
Detailed Description
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes>
struct TerminalUart< txbufferlenbytes, rxbufferlenbytes >
Definition at line 67 of file TerminalUart.hpp.
Constructor & Destructor Documentation
TerminalUart()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart (struct IUart & pinout, const Cmd * cmds, const size_t numcmds, const char *(*)() terminaluartprompt = 0, struct RTSCallback & rts = NoRTS, const char * prefix = NoPrefix, const uint16_t strlenprefix = 0, const bool verbose = true) inline
Definition at line 89 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::BlockOnTxBuffFull, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Cmds, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Echo, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::LastC, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Pinout, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Prefix, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::RTSPinout, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::RxCount, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::StdEcho, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::StrlenPrefix, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUartPrompt, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TxBuffer, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TxCount, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::UseCrLf, and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Verbose.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
Member Function Documentation
__attribute__()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> char RxBuffer [rxbufferlenbytes] TerminalUart< txbufferlenbytes, rxbufferlenbytes >::__attribute__ ((aligned(4)))
eof()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> bool TerminalUart< txbufferlenbytes, rxbufferlenbytes >::eof () inline
Definition at line 280 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetc(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::RxCount.
Flush()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> void TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Flush () inline
Definition at line 159 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessTx(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::RxCount.
formatf()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> void TerminalUart< txbufferlenbytes, rxbufferlenbytes >::formatf (const char * format, ...) inline
Definition at line 203 of file TerminalUart.hpp.
get()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> char TerminalUart< txbufferlenbytes, rxbufferlenbytes >::get () inline
Definition at line 296 of file TerminalUart.hpp.
References IUart::getcqq(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::LastC, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Pinout, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::RxCount, and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::UseCrLf.
Init()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> int TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Init () inline
Definition at line 111 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::RxCount, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TxBuffer, and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TxCount.
maybegetc()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> char TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetc () inline
Definition at line 314 of file TerminalUart.hpp.
References CHAR_TAB, IUart::dataready(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Echo, IUart::getcqq(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::LastC, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Pinout, IUart::putcqq(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::StdEcho, stdio_hook_putc(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::UseCrLf.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::eof(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetline().
maybegetline()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> int TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetline () inline
Definition at line 341 of file TerminalUart.hpp.
References CHAR_BAK, CHAR_DEL, CHAR_ESC, CHAR_TAB, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetc(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::RxCount.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessRx().
Process()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> bool TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Process () inline
Definition at line 274 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessRx(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessTx().
ProcessRx()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> bool TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessRx () inline
Definition at line 234 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetline(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::RxCount, TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUartPrompt, and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Verbose.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Process().
ProcessTx()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> bool TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessTx () inline
Definition at line 213 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Pinout, IUart::putcqq(), RTSCallback::RTS(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::RTSPinout, and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TxBuffer.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Flush(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Process().
Prompt() [1/2]
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> void TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Prompt () inline
Definition at line 120 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUartPrompt.
Prompt() [2/2]
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> void TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Prompt (const char *(*)() terminaluartprompt) inline
Definition at line 129 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUartPrompt.
put()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> char TerminalUart< txbufferlenbytes, rxbufferlenbytes >::put (char c) inline
Definition at line 171 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Pinout, IUart::putcqq(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::UseCrLf.
puts()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> void TerminalUart< txbufferlenbytes, rxbufferlenbytes >::puts (const char * s, unsigned int maxlen = (unsigned int)(-1)) inline
Definition at line 194 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TxCount.
SetBlockOnTxBuffFull()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> void TerminalUart< txbufferlenbytes, rxbufferlenbytes >::SetBlockOnTxBuffFull (bool block) inline
Definition at line 148 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::BlockOnTxBuffFull.
SetCrLfOrLf()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> void TerminalUart< txbufferlenbytes, rxbufferlenbytes >::SetCrLfOrLf (bool crlf) inline
Definition at line 143 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::UseCrLf.
SetEcho()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> void TerminalUart< txbufferlenbytes, rxbufferlenbytes >::SetEcho (bool echostate) inline
Definition at line 133 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Echo.
SetPrefix()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> void TerminalUart< txbufferlenbytes, rxbufferlenbytes >::SetPrefix (const char * prefix) inline
Definition at line 153 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Prefix.
SetVerbose()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> void TerminalUart< txbufferlenbytes, rxbufferlenbytes >::SetVerbose (const bool verbose) inline
Definition at line 131 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Verbose.
StdOutEcho()
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> void TerminalUart< txbufferlenbytes, rxbufferlenbytes >::StdOutEcho (bool echostate) inline
Definition at line 138 of file TerminalUart.hpp.
References TerminalUart< txbufferlenbytes, rxbufferlenbytes >::StdEcho.
Member Data Documentation
BlockOnTxBuffFull
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> bool TerminalUart< txbufferlenbytes, rxbufferlenbytes >::BlockOnTxBuffFull
Definition at line 79 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::SetBlockOnTxBuffFull(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
Cmds
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> const Cmd* TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Cmds
Definition at line 81 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
Echo
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> bool TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Echo
Definition at line 75 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetc(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::SetEcho(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
LastC
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> char TerminalUart< txbufferlenbytes, rxbufferlenbytes >::LastC
Definition at line 77 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::get(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetc(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
NumCmds
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> size_t TerminalUart< txbufferlenbytes, rxbufferlenbytes >::NumCmds
Definition at line 82 of file TerminalUart.hpp.
Pinout
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> IUart& TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Pinout
Definition at line 80 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::get(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetc(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessTx(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::put(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
Prefix
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> const char* TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Prefix
Definition at line 85 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::SetPrefix(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
RTSPinout
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> RTSCallback& TerminalUart< txbufferlenbytes, rxbufferlenbytes >::RTSPinout
Definition at line 84 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessTx(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
RxCount
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> uint16_t TerminalUart< txbufferlenbytes, rxbufferlenbytes >::RxCount
Definition at line 73 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::eof(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Flush(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::get(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Init(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetline(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessRx(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
StdEcho
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> bool TerminalUart< txbufferlenbytes, rxbufferlenbytes >::StdEcho
Definition at line 76 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetc(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::StdOutEcho(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
StrlenPrefix
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> uint16_t TerminalUart< txbufferlenbytes, rxbufferlenbytes >::StrlenPrefix
Definition at line 86 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
TerminalUartPrompt
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> const char*(* TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUartPrompt) ()
Definition at line 83 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessRx(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Prompt(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
TxBuffer
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> fixedqueue<char, txbufferlenbytes> TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TxBuffer
Definition at line 71 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Init(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessTx(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
TxCount
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> uint16_t TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TxCount
Definition at line 74 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Init(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::puts(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
UseCrLf
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> bool TerminalUart< txbufferlenbytes, rxbufferlenbytes >::UseCrLf
Definition at line 78 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::get(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::maybegetc(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::put(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::SetCrLfOrLf(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
Verbose
template<uint16_t txbufferlenbytes, uint16_t rxbufferlenbytes> bool TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Verbose
Definition at line 87 of file TerminalUart.hpp.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessRx(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::SetVerbose(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::TerminalUart().
The documentation for this struct was generated from the following file:
TerminalUart.hpp