ESC FilterWheel C++ Source: MonitorAdcCalibratedInput Struct Reference
MonitorAdcCalibratedInput Struct Reference
#include <MonitorAdc.hpp>
Public Member Functions
MonitorAdcCalibratedInput (double gain, double offset)
MonitorAdcCalibratedInput ()
MonitorAdcCalibratedInput (const MonitorAdcCalibratedInput &a)
void Calibrate (double gain, double offset)
double ReadCalibrated (const int32_t &RawInput) const
double GetGain () const
double GetOffset () const
Private Attributes
double Gain
double Offset
Detailed Description
Definition at line 89 of file MonitorAdc.hpp.
Constructor & Destructor Documentation
MonitorAdcCalibratedInput() [1/3]
MonitorAdcCalibratedInput::MonitorAdcCalibratedInput (double gain, double offset) inline
Definition at line 98 of file MonitorAdc.hpp.
References Gain, and Offset.
MonitorAdcCalibratedInput() [2/3]
MonitorAdcCalibratedInput::MonitorAdcCalibratedInput () inline
Definition at line 99 of file MonitorAdc.hpp.
References Gain, and Offset.
MonitorAdcCalibratedInput() [3/3]
MonitorAdcCalibratedInput::MonitorAdcCalibratedInput (const MonitorAdcCalibratedInput & a) inline
Definition at line 100 of file MonitorAdc.hpp.
References Gain, and Offset.
Member Function Documentation
Calibrate()
void MonitorAdcCalibratedInput::Calibrate (double gain, double offset) inline
Definition at line 102 of file MonitorAdc.hpp.
References Gain, and Offset.
Referenced by CalibrateMonitorAdcCommand().
GetGain()
double MonitorAdcCalibratedInput::GetGain () const inline
Definition at line 107 of file MonitorAdc.hpp.
References Gain.
Referenced by CalibrateMonitorAdcCommand().
GetOffset()
double MonitorAdcCalibratedInput::GetOffset () const inline
Definition at line 108 of file MonitorAdc.hpp.
References Offset.
Referenced by CalibrateMonitorAdcCommand().
ReadCalibrated()
double MonitorAdcCalibratedInput::ReadCalibrated (const int32_t & RawInput) const inline
Definition at line 104 of file MonitorAdc.hpp.
References ads1258details::CountsToVolts(), Gain, and Offset.
Referenced by CGraphFWMonitorAdc::GetAmbientLight(), CGraphFWMonitorAdc::GetAux0(), CGraphFWMonitorAdc::GetAux1(), CGraphFWMonitorAdc::GetAux2(), CGraphFWMonitorAdc::GetP1V2(), CGraphFWMonitorAdc::GetP28V(), CGraphFWMonitorAdc::GetP2I2(), CGraphFWMonitorAdc::GetP2V2(), CGraphFWMonitorAdc::GetP2V5(), CGraphFWMonitorAdc::GetP3V3D(), CGraphFWMonitorAdc::GetP4I3(), CGraphFWMonitorAdc::GetP4V3(), CGraphFWMonitorAdc::GetP5V(), CGraphFWMonitorAdc::GetP6I(), CGraphFWMonitorAdc::GetP6V(), and CGraphFWMonitorAdc::GetTemperature().
Member Data Documentation
Gain
double MonitorAdcCalibratedInput::Gain private
Definition at line 93 of file MonitorAdc.hpp.
Referenced by Calibrate(), GetGain(), MonitorAdcCalibratedInput(), and ReadCalibrated().
Offset
double MonitorAdcCalibratedInput::Offset private
Definition at line 94 of file MonitorAdc.hpp.
Referenced by Calibrate(), GetOffset(), MonitorAdcCalibratedInput(), and ReadCalibrated().
The documentation for this struct was generated from the following file:
MonitorAdc.hpp