ESC FilterWheel C++ Source: CGraphFWPositionStepRegister Union Reference
CGraphFWPositionStepRegister Union Reference
#include <CGraphFWHardwareInterface.hpp>
Public Member Functions
struct {
int16_t OnStep
uint16_t reserved1
int16_t OffStep
uint16_t reserved2
} __attribute__ ((__packed__))
CGraphFWPositionStepRegister ()
int16_t MidStep () const
void formatf () const
Public Attributes
uint64_t all
Detailed Description
Definition at line 157 of file CGraphFWHardwareInterface.hpp.
Constructor & Destructor Documentation
CGraphFWPositionStepRegister()
CGraphFWPositionStepRegister::CGraphFWPositionStepRegister () inline
Definition at line 169 of file CGraphFWHardwareInterface.hpp.
References all.
Member Function Documentation
__attribute__()
struct CGraphFWPositionStepRegister::@8 CGraphFWPositionStepRegister::__attribute__ ((__packed__))
formatf()
void CGraphFWPositionStepRegister::formatf () const inline
Definition at line 173 of file CGraphFWHardwareInterface.hpp.
References all, and MidStep().
Referenced by BinaryFWPositionStepsCommand(), FWHome(), SensorStepsCommand(), and ValidatedFWHomeStep().
MidStep()
int16_t CGraphFWPositionStepRegister::MidStep () const inline
Definition at line 171 of file CGraphFWHardwareInterface.hpp.
Referenced by formatf(), and ValidatedFWHomeStep().
Member Data Documentation
all
uint64_t CGraphFWPositionStepRegister::all
Definition at line 159 of file CGraphFWHardwareInterface.hpp.
Referenced by CGraphFWPositionStepRegister(), and formatf().
OffStep
int16_t CGraphFWPositionStepRegister::OffStep
Definition at line 164 of file CGraphFWHardwareInterface.hpp.
Referenced by BinaryFWPositionStepsCommand(), and ValidatedFWHomeStep().
OnStep
int16_t CGraphFWPositionStepRegister::OnStep
Definition at line 162 of file CGraphFWHardwareInterface.hpp.
Referenced by BinaryFWPositionStepsCommand(), and ValidatedFWHomeStep().
reserved1
uint16_t CGraphFWPositionStepRegister::reserved1
Definition at line 163 of file CGraphFWHardwareInterface.hpp.
reserved2
uint16_t CGraphFWPositionStepRegister::reserved2
Definition at line 165 of file CGraphFWHardwareInterface.hpp.
The documentation for this union was generated from the following file:
CGraphFWHardwareInterface.hpp