ESC FilterWheel C++ Source: ads1258.h File Reference
ads1258.h File Reference
#include <stdint.h>
#include "Delay.h"
#include "format/formatf.h"
Classes
union ads1258details::ads1258status
union ads1258details::ads1258sample
union ads1258details::ads1258cmdheader
union ads1258details::config0register
union ads1258details::config1register
union ads1258details::muxschregister
union ads1258details::sysreadregister
struct ads1258< spipinout >
struct ads1258< spipinout >::spi_busmsg
Namespaces
namespace ads1258details
Copyright (c) by Franks Development, LLC.
Functions
static double ads1258details::CountsToVolts (const int32_t &Counts, const double &AdcVRef)
union ads1258details::ads1258status ads1258details::__attribute__ ((__packed__))
struct {
uint8_t channel: 5
uint8_t isbrownout: 1
uint8_t isclipped: 1
uint8_t isnew: 1
} __attribute__ ((__packed__))
void formatf ()
ads1258sample (const uint32_t &val)
ads1258sample ()
ads1258cmdheader ()
ads1258cmdheader (uint8_t c, uint8_t m, uint8_t a)
bool operator!= (const ads1258cmdheader &rhs)
config0register ()
config0register (uint8_t a, uint8_t b, uint8_t c, uint8_t d, uint8_t e, uint8_t f)
bool operator!= (const config0register &rhs)
config1register ()
config1register (uint8_t a, uint8_t b, uint8_t c, uint8_t d)
bool operator!= (const config1register &rhs)
muxschregister ()
muxschregister (uint8_t a, uint8_t b)
bool operator!= (const muxschregister &rhs)
sysreadregister ()
sysreadregister (uint8_t a, uint8_t b, uint8_t c, uint8_t d, uint8_t e)
bool operator!= (const sysreadregister &rhs)
Variables
const int32_t ads1258details::CountPosMax = 0x7FFFFFUL
const int32_t ads1258details::CountPosVRef = 0x780000UL
const int32_t ads1258details::CountZero = 0x000000UL
const int32_t ads1258details::CountNegVRef = (int32_t)0xFF87FFFFUL
const int32_t ads1258details::CountNegMin = (int32_t)0xFF800000UL
const int32_t ads1258details::CountVRefVccDenominator = 786432
const int32_t ads1258details::CountGainDenominator = 7864320
uint8_t channel
uint8_t isbrownout
uint8_t isclipped
uint8_t isnew
uint8_t all
uint8_t zero
uint8_t one
uint8_t two
uint8_t three
int32_t sample
ads1258status status
static const uint8_t ads1258details::cmdtype_chanreaddirect = 0x00
static const uint8_t ads1258details::cmdtype_chanreadregister = 0x01
static const uint8_t ads1258details::cmdtype_registerread = 0x02
static const uint8_t ads1258details::cmdtype_registerwrite = 0x03
static const uint8_t ads1258details::cmdtype_pulseconvert = 0x04
static const uint8_t ads1258details::cmdtype_reserved = 0x05
static const uint8_t ads1258details::cmdtype_reset = 0x06
static const uint8_t ads1258details::cmdtype_chanreaddirectalt = 0x07
static const uint8_t ads1258details::register_config0 = 0x00
static const uint8_t ads1258details::register_config1 = 0x01
static const uint8_t ads1258details::register_muxsch = 0x02
static const uint8_t ads1258details::register_muxdif = 0x03
static const uint8_t ads1258details::register_muxsg0 = 0x04
static const uint8_t ads1258details::register_muxsg1 = 0x05
static const uint8_t ads1258details::register_sysread = 0x06
static const uint8_t ads1258details::register_gpioc = 0x07
static const uint8_t ads1258details::register_gpiod = 0x08
static const uint8_t ads1258details::register_idnum = 0x09
uint8_t address
uint8_t multiple
uint8_t cmdtype
uint8_t alsomustbezero
uint8_t stat
uint8_t chop
uint8_t clkout
uint8_t bypass
uint8_t muxmod
uint8_t spiresettimeout
uint8_t mustbezero
uint8_t datarate
uint8_t sensorbiascurrent
uint8_t delay
uint8_t idlemode
uint8_t chan_posin
uint8_t chan_negin
uint8_t scan_offset
uint8_t reserve2
uint8_t scan_vcc
uint8_t scan_temp
uint8_t scan_gain
uint8_t scan_ref
uint8_t reserve1
uint8_t reserve0
const uint8_t ads1258details::chan_diff0 = 0x00
const uint8_t ads1258details::chan_diff1 = 0x01
const uint8_t ads1258details::chan_diff2 = 0x02
const uint8_t ads1258details::chan_diff3 = 0x03
const uint8_t ads1258details::chan_diff4 = 0x04
const uint8_t ads1258details::chan_diff5 = 0x05
const uint8_t ads1258details::chan_diff6 = 0x06
const uint8_t ads1258details::chan_diff7 = 0x07
const uint8_t ads1258details::chan_se0 = 0x08
const uint8_t ads1258details::chan_se1 = 0x09
const uint8_t ads1258details::chan_se2 = 0x0A
const uint8_t ads1258details::chan_se3 = 0x0B
const uint8_t ads1258details::chan_se4 = 0x0C
const uint8_t ads1258details::chan_se5 = 0x0D
const uint8_t ads1258details::chan_se6 = 0x0E
const uint8_t ads1258details::chan_se7 = 0x0F
const uint8_t ads1258details::chan_se8 = 0x10
const uint8_t ads1258details::chan_se9 = 0x11
const uint8_t ads1258details::chan_se10 = 0x12
const uint8_t ads1258details::chan_se11 = 0x13
const uint8_t ads1258details::chan_se12 = 0x14
const uint8_t ads1258details::chan_se13 = 0x15
const uint8_t ads1258details::chan_se14 = 0x16
const uint8_t ads1258details::chan_se15 = 0x17
const uint8_t ads1258details::chan_offset = 0x18
const uint8_t ads1258details::chan_zeroed = 0x19
const uint8_t ads1258details::chan_vcc = 0x1A
const uint8_t ads1258details::chan_temp = 0x1B
const uint8_t ads1258details::chan_gain = 0x1C
const uint8_t ads1258details::chan_ref = 0x1D
const uint8_t ads1258details::ads1258numchannels = 0x1E
Function Documentation
__attribute__()
struct @8 __attribute__::__attribute__ ((__packed__))
ads1258cmdheader() [1/2]
__attribute__::ads1258cmdheader ()
Definition at line 9 of file ads1258.h.
ads1258cmdheader() [2/2]
__attribute__::ads1258cmdheader (uint8_t c, uint8_t m, uint8_t a)
Definition at line 12 of file ads1258.h.
ads1258sample() [1/2]
__attribute__::ads1258sample ()
Definition at line 17 of file ads1258.h.
ads1258sample() [2/2]
__attribute__::ads1258sample (const uint32_t & val)
Definition at line 16 of file ads1258.h.
config0register() [1/2]
__attribute__::config0register ()
Definition at line 14 of file ads1258.h.
config0register() [2/2]
__attribute__::config0register (uint8_t a, uint8_t b, uint8_t c, uint8_t d, uint8_t e, uint8_t f)
Definition at line 17 of file ads1258.h.
config1register() [1/2]
__attribute__::config1register ()
Definition at line 10 of file ads1258.h.
config1register() [2/2]
__attribute__::config1register (uint8_t a, uint8_t b, uint8_t c, uint8_t d)
Definition at line 13 of file ads1258.h.
formatf()
void formatf ()
Definition at line 10 of file ads1258.h.
Referenced by BinaryFSMStatusCommand(), BISTCommand(), CalibrateMonitorAdcCommand(), ads1258< spipinout >::CommitScanChannels(), ads1258< spipinout >::ConvertOnceDiff(), linux_pinout_server_socket::dataready(), linux_pinout_client_socket::deinit(), linux_pinout_server_socket::deinit(), linux_pinout_client_socket::getcqq(), linux_pinout_server_socket::getcqq(), linux_pinout_uart::getcqq(), HelpCmds(), CGraphFSMMonitorAdc::Init(), linux_pinout_client_socket::init(), linux_pinout_server_socket::init(), ads1258< spipinout >::Init(), FPGABinaryUartCallbacks::InvalidPacket(), FPGABinaryUartCallbacks::InvalidPacket(), main(), MonitorSerialCommand(), ParseCmd(), CGraphFSMMonitorAdc::Process(), linux_pinout_client_socket::putcqq(), linux_pinout_server_socket::putcqq(), linux_pinout_uart::putcqq(), CGraphFSMMonitorAdc::RestoreCals(), CGraphFSMMonitorAdc::SaveCals(), ScanMonitorAdcCommand(), linux_pinout_server_socket::SocketConnect(), TestMonitorAdcCommand(), TxBinaryPacket(), FPGABinaryUartCallbacks::UnHandledPacket(), FPGABinaryUartCallbacks::UnHandledPacket(), and PinoutMonitorAdc::waitbusytimeout().
muxschregister() [1/2]
__attribute__::muxschregister ()
Definition at line 8 of file ads1258.h.
muxschregister() [2/2]
__attribute__::muxschregister (uint8_t a, uint8_t b)
Definition at line 11 of file ads1258.h.
operator!=() [1/5]
bool __attribute__::operator!= (const ads1258cmdheader & rhs)
Definition at line 15 of file ads1258.h.
operator!=() [2/5]
bool __attribute__::operator!= (const config0register & rhs)
Definition at line 20 of file ads1258.h.
operator!=() [3/5]
bool __attribute__::operator!= (const config1register & rhs)
Definition at line 16 of file ads1258.h.
operator!=() [4/5]
bool __attribute__::operator!= (const muxschregister & rhs)
Definition at line 14 of file ads1258.h.
operator!=() [5/5]
bool __attribute__::operator!= (const sysreadregister & rhs)
Definition at line 20 of file ads1258.h.
sysreadregister() [1/2]
__attribute__::sysreadregister ()
Definition at line 14 of file ads1258.h.
sysreadregister() [2/2]
__attribute__::sysreadregister (uint8_t a, uint8_t b, uint8_t c, uint8_t d, uint8_t e)
Definition at line 17 of file ads1258.h.
Variable Documentation
address
uint8_t address
Definition at line 0 of file ads1258.h.
all
uint8_t all
Definition at line 0 of file ads1258.h.
alsomustbezero
uint8_t alsomustbezero
Definition at line 0 of file ads1258.h.
bypass
uint8_t bypass
Definition at line 4 of file ads1258.h.
chan_negin
uint8_t chan_negin
Definition at line 1 of file ads1258.h.
chan_posin
uint8_t chan_posin
Definition at line 0 of file ads1258.h.
channel
uint8_t channel
Definition at line 0 of file ads1258.h.
Referenced by ads1258< spipinout >::GetLastSample().
chop
uint8_t chop
Definition at line 2 of file ads1258.h.
clkout
uint8_t clkout
Definition at line 3 of file ads1258.h.
cmdtype
uint8_t cmdtype
Definition at line 2 of file ads1258.h.
datarate
uint8_t datarate
Definition at line 0 of file ads1258.h.
delay
uint8_t delay
Definition at line 2 of file ads1258.h.
Referenced by delayus().
idlemode
uint8_t idlemode
Definition at line 3 of file ads1258.h.
isbrownout
uint8_t isbrownout
Definition at line 1 of file ads1258.h.
isclipped
uint8_t isclipped
Definition at line 2 of file ads1258.h.
isnew
uint8_t isnew
Definition at line 3 of file ads1258.h.
multiple
uint8_t multiple
Definition at line 1 of file ads1258.h.
mustbezero
uint8_t mustbezero
Definition at line 7 of file ads1258.h.
muxmod
uint8_t muxmod
Definition at line 5 of file ads1258.h.
one
uint8_t one
Definition at line 1 of file ads1258.h.
reserve0
uint8_t reserve0
Definition at line 7 of file ads1258.h.
reserve1
uint8_t reserve1
Definition at line 6 of file ads1258.h.
reserve2
uint8_t reserve2
Definition at line 1 of file ads1258.h.
sample
int32_t sample
Definition at line 0 of file ads1258.h.
Referenced by ads1258< spipinout >::GetLastSample(), and CGraphFSMMonitorAdc::Process().
scan_gain
uint8_t scan_gain
Definition at line 4 of file ads1258.h.
scan_offset
uint8_t scan_offset
Definition at line 0 of file ads1258.h.
scan_ref
uint8_t scan_ref
Definition at line 5 of file ads1258.h.
scan_temp
uint8_t scan_temp
Definition at line 3 of file ads1258.h.
scan_vcc
uint8_t scan_vcc
Definition at line 2 of file ads1258.h.
sensorbiascurrent
uint8_t sensorbiascurrent
Definition at line 1 of file ads1258.h.
spiresettimeout
uint8_t spiresettimeout
Definition at line 6 of file ads1258.h.
stat
uint8_t stat
Definition at line 1 of file ads1258.h.
Referenced by ParseConfigFile().
status
ads1258status status
Definition at line 1 of file ads1258.h.
Referenced by linux_pinout_uart::dataready().
three
uint8_t three
Definition at line 3 of file ads1258.h.
two
uint8_t two
Definition at line 2 of file ads1258.h.
zero
uint8_t zero
Definition at line 0 of file ads1258.h.