ESC FilterWheel C++ Source: AsciiCmdUserInterfaceLinux.h File Reference
AsciiCmdUserInterfaceLinux.h File Reference
#include <sched.h>
#include <unistd.h>
#include <pthread.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/types.h>
#include <errno.h>
#include <dirent.h>
#include "uart/CmdSystem.hpp"
Functions
void * StdInClientThread (void *argument)
void StartUserInterface ()
bool ProcessUserInterface ()
void ParseConfigFile (const char *ConfigFileName)
Variables
const Cmd AsciiCmds []
Copyright (c) by Franks Development, LLC.
const uint8_t NumAsciiCmds
Function Documentation
ParseConfigFile()
void ParseConfigFile (const char * ConfigFileName)
Definition at line 161 of file AsciiCmdUserInterfaceLinux.cpp.
References AsciiCmds, NumAsciiCmds, ParseCmd(), and stat.
ProcessUserInterface()
bool ProcessUserInterface ()
Definition at line 90 of file AsciiCmdUserInterfaceLinux.cpp.
References AsciiCmds, line, linelen, linelock, newline, NumAsciiCmds, and ParseCmd().
StartUserInterface()
void StartUserInterface ()
Definition at line 72 of file AsciiCmdUserInterfaceLinux.cpp.
References AsciiCmds, linelock, NumAsciiCmds, and StdInClientThread().
StdInClientThread()
void * StdInClientThread (void * argument)
Definition at line 124 of file AsciiCmdUserInterfaceLinux.cpp.
References line, linelen, linelock, linemaxlen, newline, and Wait50().
Referenced by StartUserInterface().
Variable Documentation
AsciiCmds
const Cmd AsciiCmds[] extern
Copyright (c) by Franks Development, LLC.
Copyright (c) by Franks Development, LLC.
Definition at line 37 of file CmdTableAscii.cpp.
NumAsciiCmds
const uint8_t NumAsciiCmds extern
Definition at line 191 of file CmdTableAscii.cpp.