ESC FilterWheel C++ Source: BinaryUart.h File Reference
BinaryUart.h File Reference
UART interface for binary packet communication.
#include <stdio.h>
#include <stdarg.h>
#include <stdint.h>
Classes
struct BinaryUartCallbacks
Functions
void TxBinaryPacket (const void *TxPktContext, const uint16_t PayloadTypeToken, const uint32_t SerialNumber, const void *PayloadData, const size_t PayloadLength)
Detailed Description
UART interface for binary packet communication.
Definition in file BinaryUart.h.
Function Documentation
TxBinaryPacket()
void TxBinaryPacket (const void * TxPktContext, const uint16_t PayloadTypeToken, const uint32_t SerialNumber, const void * PayloadData, const size_t PayloadLength)
Definition at line 4 of file BinaryUart.cpp.
References formatf(), PayloadData(), PayloadLen, and TxBinaryPacket().
Referenced by BinaryFSMAdcsCommand(), BinaryFSMAdcsFloatingPointCommand(), BinaryFSMDacsCommand(), BinaryFSMDacsFloatingPointCommand(), BinaryFSMStatusCommand(), BinaryVersionCommand(), TxBinaryPacket(), and UartCommand().