ESC FilterWheel C++ Source: BinaryUart.cpp File Reference
BinaryUart.cpp File Reference
#include "BinaryUart.hpp"
Functions
void TxBinaryPacket (const void *TxPktContext, const uint16_t PayloadTypeToken, const uint32_t SerialNumber, const void *PayloadData, const size_t PayloadLen)
Function Documentation
TxBinaryPacket()
void TxBinaryPacket (const void * TxPktContext, const uint16_t PayloadTypeToken, const uint32_t SerialNumber, const void * PayloadData, const size_t PayloadLen)
Definition at line 4 of file BinaryUart.cpp.
References formatf(), PayloadData(), PayloadLen, and TxBinaryPacket().
Referenced by BinaryFSMAdcsCommand(), BinaryFSMAdcsFloatingPointCommand(), BinaryFSMDacsCommand(), BinaryFSMDacsFloatingPointCommand(), BinaryFSMStatusCommand(), BinaryVersionCommand(), TxBinaryPacket(), and UartCommand().