ESC FilterWheel C++ Source: BinaryUartRingBuffer.hpp File Reference
BinaryUartRingBuffer.hpp File Reference
UART interface for binary packet communication.
#include <stdio.h>
#include <stdarg.h>
#include <stdint.h>
#include "fixedqueue.hpp"
#include "IBlockDevice.hpp"
#include "format/formatf.h"
#include "uart/CmdSystem.hpp"
#include "uart/IProtocol.hpp"
#include "uart/IPacket.hpp"
#include "eeprom/CircularFifoFlattened.hpp"
#include "cgraph/CGraphDMHardwareInterface.hpp"
Classes
struct BinaryUartCallbacks
struct BinaryUart
Functions
void TxBinaryPacket (const void *TxPktContext, const uint16_t PayloadTypeToken, const uint32_t SerialNumber, const void *PayloadData, const size_t PayloadLen)
Variables
CGraphDMHardwareInterface * DM
Detailed Description
UART interface for binary packet communication.
Definition in file BinaryUartRingBuffer.hpp.
Function Documentation
TxBinaryPacket()
void TxBinaryPacket (const void * TxPktContext, const uint16_t PayloadTypeToken, const uint32_t SerialNumber, const void * PayloadData, const size_t PayloadLen)
Definition at line 4 of file BinaryUart.cpp.
References formatf(), PayloadData(), PayloadLen, and TxBinaryPacket().
Referenced by BinaryFSMAdcsCommand(), BinaryFSMAdcsFloatingPointCommand(), BinaryFSMDacsCommand(), BinaryFSMDacsFloatingPointCommand(), BinaryFSMStatusCommand(), BinaryVersionCommand(), TxBinaryPacket(), and UartCommand().
Variable Documentation
DM
CGraphDMHardwareInterface* DM extern
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 11 of file CGraphDMHardwareInterface.cpp.