ESC FilterWheel C++ Source: BinaryUart.hpp File Reference
BinaryUart.hpp File Reference
UART interface for binary packet communication.
#include <stdio.h>
#include <stdarg.h>
#include <stdint.h>
#include "fixedqueue.hpp"
#include "uart/IUart.h"
#include "format/formatf.h"
#include "uart/CmdSystem.hpp"
#include "uart/IProtocol.hpp"
#include "uart/IPacket.hpp"
#include "uart/IUartParser.hpp"
#include "cgraph/CGraphDMHardwareInterface.hpp"
Classes
struct BinaryUartCallbacks
struct BinaryUart
Functions
__inline__ void TxBinaryPacket (const void *TxPktContext, const uint16_t PayloadTypeToken, const uint32_t SerialNumber, const void *PayloadData, const size_t PayloadLen)
Variables
CGraphDMHardwareInterface * DM
Detailed Description
UART interface for binary packet communication.
Definition in file BinaryUart.hpp.
Function Documentation
TxBinaryPacket()
__inline__ void TxBinaryPacket (const void * TxPktContext, const uint16_t PayloadTypeToken, const uint32_t SerialNumber, const void * PayloadData, const size_t PayloadLen)
Definition at line 453 of file BinaryUart.hpp.
References formatf(), PayloadData(), PayloadLen, and TxBinaryPacket().
Referenced by TxBinaryPacket().
Variable Documentation
DM
CGraphDMHardwareInterface* DM extern
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 11 of file CGraphDMHardwareInterface.cpp.