ESC FilterWheel C++ Source: EzThread Class Reference
EzThread Class Reference
Copyright (c) by Franks Development, LLC.
#include <EzThread.hpp>
Public Member Functions
EzThread ()
virtual ~EzThread ()
virtual void ThreadInit ()
virtual bool Process ()
virtual void OneSecondRoutines ()
virtual void TenHzRoutines ()
void Init ()
Static Public Member Functions
static void * EzThreadFunc (void *pthis)
Public Attributes
pthread_t Thread
size_t BoredDelayuS
size_t MinimumDelayuS
char ThreadName [256]
Detailed Description
Copyright (c) by Franks Development, LLC.
EzThread: a class for making threads that do stuff. Just derive a class from this one and fill in your own virtual Process(), OneHzRoutines(), and TenHzRoutines(), then call Init() somewhere in main().
Definition at line 40 of file EzThread.hpp.
Constructor & Destructor Documentation
EzThread()
EzThread::EzThread () inline
Definition at line 45 of file EzThread.hpp.
References ThreadName.
~EzThread()
virtual EzThread::~EzThread () inline virtual
Definition at line 46 of file EzThread.hpp.
Member Function Documentation
EzThreadFunc()
static void * EzThread::EzThreadFunc (void * pthis) inline static
Definition at line 73 of file EzThread.hpp.
References BoredDelayuS, delayus(), MinimumDelayuS, OneSecondRoutines(), Process(), TenHzRoutines(), ThreadInit(), and ThreadName.
Referenced by Init().
Init()
void EzThread::Init () inline
Definition at line 63 of file EzThread.hpp.
References EzThreadFunc(), Thread, and ThreadName.
OneSecondRoutines()
virtual void EzThread::OneSecondRoutines () inline virtual
Definition at line 53 of file EzThread.hpp.
Referenced by EzThreadFunc().
Process()
virtual bool EzThread::Process () inline virtual
Definition at line 51 of file EzThread.hpp.
Referenced by EzThreadFunc().
TenHzRoutines()
virtual void EzThread::TenHzRoutines () inline virtual
Definition at line 55 of file EzThread.hpp.
Referenced by EzThreadFunc().
ThreadInit()
virtual void EzThread::ThreadInit () inline virtual
Definition at line 49 of file EzThread.hpp.
Referenced by EzThreadFunc().
Member Data Documentation
BoredDelayuS
size_t EzThread::BoredDelayuS
Definition at line 58 of file EzThread.hpp.
Referenced by EzThreadFunc().
MinimumDelayuS
size_t EzThread::MinimumDelayuS
Definition at line 59 of file EzThread.hpp.
Referenced by EzThreadFunc().
Thread
pthread_t EzThread::Thread
Definition at line 57 of file EzThread.hpp.
Referenced by Init().
ThreadName
char EzThread::ThreadName[256]
Definition at line 60 of file EzThread.hpp.
Referenced by EzThread(), EzThreadFunc(), and Init().
The documentation for this class was generated from the following file:
EzThread.hpp