ESC FilterWheel C++ Source: IPacket Class Reference
IPacket Class Reference abstract
Copyright (c) by Franks Development, LLC.
#include <IPacket.hpp>
Public Member Functions
IPacket ()
virtual ~IPacket ()
virtual bool FindPacketStartPos (const uint8_t *Buffer, const size_t BufferLen, size_t &Offset) const =0
virtual bool FindPacketEndPos (const uint8_t *Buffer, const size_t BufferLen, size_t &Offset) const =0
virtual bool FindPacketStartPos (const uint8_t *Buffer, const size_t BufferLen, const size_t SearchStartPos, size_t &Offset) const =0
virtual bool FindPacketEndPos (const uint8_t *Buffer, const size_t BufferLen, const size_t SearchStartPos, size_t &Offset) const =0
virtual size_t HeaderLen () const =0
virtual size_t FooterLen () const =0
virtual size_t EndTokenLen () const =0
virtual size_t PayloadOffset () const =0
virtual size_t MaxPayloadLength () const =0
virtual size_t PayloadLen (const uint8_t *Buffer, const size_t BufferCount, const size_t PacketStartPos) const =0
virtual bool IsValid (const uint8_t *Buffer, const size_t BufferCount, const size_t PacketStartPos, const size_t PacketEndPos) const =0
virtual bool IsBroadcastSerialNum (const uint8_t *Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const =0
virtual uint64_t SerialNum (const uint8_t *Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const =0
virtual uint64_t PayloadType (const uint8_t *Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const =0
virtual bool DoesPayloadTypeMatch (const uint8_t *Buffer, const size_t BufferCount, const size_t PacketStartPos, const size_t PacketEndPos, const uint32_t CmdType) const =0
virtual size_t MakePacket (uint8_t *Buffer, const size_t BufferCount, const void *Payload, const uint16_t PayloadType, const size_t PayloadLen) const =0
virtual bool FindPacketStartPos (const IArray &Buffer, const size_t SearchStartPos, size_t &Offset) const =0
virtual bool ReverseFindPacketStartPos (const IArray &Buffer, const size_t SearchEndPos, size_t &Offset) const =0
virtual bool FindPacketEndPos (const IArray &Buffer, const size_t SearchStartPos, size_t &Offset) const =0
virtual size_t PayloadLen (const IArray &Buffer, const size_t PacketStartPos) const =0
virtual bool IsValid (const IArray &Buffer, const size_t PacketStartPos, const size_t PacketEndPos, FpgaRingBufferCrcer &FpgaCrc) const =0
virtual bool IsBroadcastSerialNum (const IArray &Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const =0
virtual uint64_t SerialNum (const IArray &Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const =0
virtual uint64_t PayloadType (const IArray &Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const =0
virtual bool DoesPayloadTypeMatch (const IArray &Buffer, const size_t PacketStartPos, const size_t PacketEndPos, const uint32_t CmdType) const =0
Detailed Description
Copyright (c) by Franks Development, LLC.
Definition at line 35 of file IPacket.hpp.
Constructor & Destructor Documentation
IPacket()
IPacket::IPacket () inline
Definition at line 38 of file IPacket.hpp.
~IPacket()
virtual IPacket::~IPacket () inline virtual
Definition at line 39 of file IPacket.hpp.
Member Function Documentation
DoesPayloadTypeMatch() [1/2]
virtual bool IPacket::DoesPayloadTypeMatch (const IArray & Buffer, const size_t PacketStartPos, const size_t PacketEndPos, const uint32_t CmdType) const pure virtual
Implemented in CGraphPacket.
DoesPayloadTypeMatch() [2/2]
virtual bool IPacket::DoesPayloadTypeMatch (const uint8_t * Buffer, const size_t BufferCount, const size_t PacketStartPos, const size_t PacketEndPos, const uint32_t CmdType) const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUart::CheckPacketEnd(), and BinaryUartRingBuffer::Process().
EndTokenLen()
virtual size_t IPacket::EndTokenLen () const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUartRingBuffer::Process().
FindPacketEndPos() [1/3]
virtual bool IPacket::FindPacketEndPos (const IArray & Buffer, const size_t SearchStartPos, size_t & Offset) const pure virtual
Implemented in CGraphPacket.
FindPacketEndPos() [2/3]
virtual bool IPacket::FindPacketEndPos (const uint8_t * Buffer, const size_t BufferLen, const size_t SearchStartPos, size_t & Offset) const pure virtual
Implemented in CGraphPacket.
FindPacketEndPos() [3/3]
virtual bool IPacket::FindPacketEndPos (const uint8_t * Buffer, const size_t BufferLen, size_t & Offset) const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUart::CheckPacketEnd(), and BinaryUartRingBuffer::Process().
FindPacketStartPos() [1/3]
virtual bool IPacket::FindPacketStartPos (const IArray & Buffer, const size_t SearchStartPos, size_t & Offset) const pure virtual
Implemented in CGraphPacket.
FindPacketStartPos() [2/3]
virtual bool IPacket::FindPacketStartPos (const uint8_t * Buffer, const size_t BufferLen, const size_t SearchStartPos, size_t & Offset) const pure virtual
Implemented in CGraphPacket.
FindPacketStartPos() [3/3]
virtual bool IPacket::FindPacketStartPos (const uint8_t * Buffer, const size_t BufferLen, size_t & Offset) const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUart::CheckPacketStart().
FooterLen()
virtual size_t IPacket::FooterLen () const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUart::Init(), BinaryUartRingBuffer::Init(), BinaryUartRingBuffer::Process(), and BinaryUart::Process().
HeaderLen()
virtual size_t IPacket::HeaderLen () const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUart::CheckPacketStart(), BinaryUart::Init(), BinaryUartRingBuffer::Init(), BinaryUartRingBuffer::Process(), and BinaryUart::Process().
IsBroadcastSerialNum() [1/2]
virtual bool IPacket::IsBroadcastSerialNum (const IArray & Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const pure virtual
Implemented in CGraphPacket.
IsBroadcastSerialNum() [2/2]
virtual bool IPacket::IsBroadcastSerialNum (const uint8_t * Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUart::CheckPacketEnd().
IsValid() [1/2]
virtual bool IPacket::IsValid (const IArray & Buffer, const size_t PacketStartPos, const size_t PacketEndPos, FpgaRingBufferCrcer & FpgaCrc) const pure virtual
Implemented in CGraphPacket.
IsValid() [2/2]
virtual bool IPacket::IsValid (const uint8_t * Buffer, const size_t BufferCount, const size_t PacketStartPos, const size_t PacketEndPos) const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUart::CheckPacketEnd(), and BinaryUartRingBuffer::Process().
MakePacket()
virtual size_t IPacket::MakePacket (uint8_t * Buffer, const size_t BufferCount, const void * Payload, const uint16_t PayloadType, const size_t PayloadLen) const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUart::TxBinaryPacket(), and BinaryUartRingBuffer::TxBinaryPacket().
MaxPayloadLength()
virtual size_t IPacket::MaxPayloadLength () const pure virtual
Implemented in CGraphPacket.
PayloadLen() [1/2]
virtual size_t IPacket::PayloadLen (const IArray & Buffer, const size_t PacketStartPos) const pure virtual
Implemented in CGraphPacket.
PayloadLen() [2/2]
virtual size_t IPacket::PayloadLen (const uint8_t * Buffer, const size_t BufferCount, const size_t PacketStartPos) const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUartRingBuffer::Process(), and BinaryUart::Process().
PayloadOffset()
virtual size_t IPacket::PayloadOffset () const pure virtual
Implemented in CGraphPacket.
PayloadType() [1/2]
virtual uint64_t IPacket::PayloadType (const IArray & Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const pure virtual
Implemented in CGraphPacket.
PayloadType() [2/2]
virtual uint64_t IPacket::PayloadType (const uint8_t * Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUart::CheckPacketEnd(), and BinaryUartRingBuffer::Process().
ReverseFindPacketStartPos()
virtual bool IPacket::ReverseFindPacketStartPos (const IArray & Buffer, const size_t SearchEndPos, size_t & Offset) const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUartRingBuffer::Process().
SerialNum() [1/2]
virtual uint64_t IPacket::SerialNum (const IArray & Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const pure virtual
Implemented in CGraphPacket.
SerialNum() [2/2]
virtual uint64_t IPacket::SerialNum (const uint8_t * Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const pure virtual
Implemented in CGraphPacket.
Referenced by BinaryUart::CheckPacketEnd().
The documentation for this class was generated from the following file:
IPacket.hpp