ESC FilterWheel C++ Source: linux_pinout_file Class Reference
linux_pinout_file Class Reference
Copyright (c) by Franks Development, LLC.
#include <linux_pinout_file.hpp>
Public Member Functions
linux_pinout_file ()
virtual ~linux_pinout_file ()
virtual int init (const uint32_t ignored, const char *FileName)
virtual void deinit ()
virtual void flushoutput ()
virtual void purgeinput ()
virtual bool isopen () const
virtual bool dataready () const
virtual char getcqq ()
virtual char putcqq (char c)
Public Member Functions inherited from IUart
IUart ()
virtual ~IUart ()
void puts (const char *s, const size_t len)
Private Attributes
FILE * fd
Additional Inherited Members
Static Public Attributes inherited from IUart
static const bool OddParity = true
static const bool NoParity = false
static const bool IUartOK = 0x00
static const bool UseRTSCTS = true
static const bool NoRTSCTS = false
Detailed Description
Copyright (c) by Franks Development, LLC.
Definition at line 37 of file linux_pinout_file.hpp.
Constructor & Destructor Documentation
linux_pinout_file()
linux_pinout_file::linux_pinout_file () inline
Definition at line 41 of file linux_pinout_file.hpp.
~linux_pinout_file()
virtual linux_pinout_file::~linux_pinout_file () inline virtual
Definition at line 42 of file linux_pinout_file.hpp.
References deinit().
Member Function Documentation
dataready()
virtual bool linux_pinout_file::dataready () const inline virtual
Implements IUart.
Definition at line 88 of file linux_pinout_file.hpp.
References fd.
deinit()
virtual void linux_pinout_file::deinit () inline virtual
Definition at line 61 of file linux_pinout_file.hpp.
References fd.
Referenced by getcqq(), init(), putcqq(), and ~linux_pinout_file().
flushoutput()
virtual void linux_pinout_file::flushoutput () inline virtual
Implements IUart.
Definition at line 71 of file linux_pinout_file.hpp.
References fd.
getcqq()
virtual char linux_pinout_file::getcqq () inline virtual
Implements IUart.
Definition at line 94 of file linux_pinout_file.hpp.
References deinit(), and fd.
init()
virtual int linux_pinout_file::init (const uint32_t ignored, const char * FileName) inline virtual
Definition at line 44 of file linux_pinout_file.hpp.
References deinit(), fd, and IUart::IUartOK.
isopen()
virtual bool linux_pinout_file::isopen () const inline virtual
Implements IUart.
Definition at line 82 of file linux_pinout_file.hpp.
References fd.
purgeinput()
virtual void linux_pinout_file::purgeinput () inline virtual
Implements IUart.
Definition at line 77 of file linux_pinout_file.hpp.
References fd.
putcqq()
virtual char linux_pinout_file::putcqq (char c) inline virtual
Implements IUart.
Definition at line 115 of file linux_pinout_file.hpp.
References deinit(), and fd.
Member Data Documentation
fd
FILE* linux_pinout_file::fd private
Definition at line 136 of file linux_pinout_file.hpp.
Referenced by dataready(), deinit(), flushoutput(), getcqq(), init(), isopen(), purgeinput(), and putcqq().
The documentation for this class was generated from the following file:
linux_pinout_file.hpp