ESC FilterWheel C++ Source: CGraphPZTProtoHardwareMmapper Class Reference
CGraphPZTProtoHardwareMmapper Class Reference
#include <CGraphDeprecatedPZTHardwareInterface.hpp>
Static Public Member Functions
static int open (int &FpgaHandle, CGraphPZTHardwareInterface *&FpgaBus)
static int close (int &FpgaHandle, CGraphPZTHardwareInterface *&FpgaBus)
static int read (const CGraphPZTHardwareInterface *FpgaBus, const size_t Address, void *Buffer, const size_t Len)
static int write (CGraphPZTHardwareInterface *FpgaBus, const size_t Address, const void *Buffer, const size_t Len)
Static Public Attributes
static const off_t FpgaMmapAdress = 0x08000000UL
static const off_t FpgaMmapMask = 0x00000FFFUL
static const char FpgaBusEmulationPathName [] = "~/.UACGraph/PZTFpgaBusEmulator.ram"
Detailed Description
Definition at line 131 of file CGraphDeprecatedPZTHardwareInterface.hpp.
Member Function Documentation
close()
int CGraphPZTProtoHardwareMmapper::close (int & FpgaHandle, CGraphPZTHardwareInterface *& FpgaBus) static
Definition at line 84 of file CGraphDeprecatedPZTHardwareInterface.cpp.
References close().
Referenced by close().
open()
int CGraphPZTProtoHardwareMmapper::open (int & FpgaHandle, CGraphPZTHardwareInterface *& FpgaBus) static
Definition at line 32 of file CGraphDeprecatedPZTHardwareInterface.cpp.
References FPGA_MAP_MASK, FPGA_MEM_ADDR, FpgaBusEmulationPathName, and open().
Referenced by open().
read()
int CGraphPZTProtoHardwareMmapper::read (const CGraphPZTHardwareInterface * FpgaBus, const size_t Address, void * Buffer, const size_t Len) static
Definition at line 113 of file CGraphDeprecatedPZTHardwareInterface.cpp.
References Buffer.
write()
int CGraphPZTProtoHardwareMmapper::write (CGraphPZTHardwareInterface * FpgaBus, const size_t Address, const void * Buffer, const size_t Len) static
Definition at line 127 of file CGraphDeprecatedPZTHardwareInterface.cpp.
References Buffer.
Member Data Documentation
FpgaBusEmulationPathName
const char CGraphPZTProtoHardwareMmapper::FpgaBusEmulationPathName = "~/.UACGraph/PZTFpgaBusEmulator.ram" static
Definition at line 137 of file CGraphDeprecatedPZTHardwareInterface.hpp.
Referenced by open().
FpgaMmapAdress
const off_t CGraphPZTProtoHardwareMmapper::FpgaMmapAdress = 0x08000000UL static
Definition at line 135 of file CGraphDeprecatedPZTHardwareInterface.hpp.
FpgaMmapMask
const off_t CGraphPZTProtoHardwareMmapper::FpgaMmapMask = 0x00000FFFUL static
Definition at line 136 of file CGraphDeprecatedPZTHardwareInterface.hpp.
The documentation for this class was generated from the following files:
CGraphDeprecatedPZTHardwareInterface.hpp
CGraphDeprecatedPZTHardwareInterface.cpp