ESC FilterWheel C++ Source: linux_pinout_server_socket Class Reference
linux_pinout_server_socket Class Reference
#include <linux_pinout_server_socket.hpp>
Public Member Functions
linux_pinout_server_socket ()
virtual ~linux_pinout_server_socket ()
virtual int init (const uint32_t HostPort, const char *HostName)
int SocketConnect ()
virtual void deinit ()
virtual bool dataready () const
virtual char getcqq ()
virtual char putcqq (char c)
virtual void flushoutput ()
virtual void purgeinput ()
virtual bool connected ()
virtual bool isopen () const
void silent (const bool s)
Public Member Functions inherited from IUart
IUart ()
virtual ~IUart ()
virtual void puts (uint8_t const *s, const size_t len) override
Public Member Functions inherited from IBlockDevice
IBlockDevice ()
virtual ~IBlockDevice ()
Private Attributes
int hSocket
int hServer
struct sockaddr_in Address
int nAddressSize
long nHostAddress
bool Silent
Additional Inherited Members
Static Public Attributes inherited from IUart
static const bool OddParity = true
static const bool NoParity = false
static const bool IUartOK = 0x00
static const bool UseRTSCTS = true
static const bool NoRTSCTS = false
Detailed Description
Definition at line 58 of file linux_pinout_server_socket.hpp.
Constructor & Destructor Documentation
linux_pinout_server_socket()
linux_pinout_server_socket::linux_pinout_server_socket () inline
Definition at line 62 of file linux_pinout_server_socket.hpp.
~linux_pinout_server_socket()
virtual linux_pinout_server_socket::~linux_pinout_server_socket () inline virtual
Definition at line 63 of file linux_pinout_server_socket.hpp.
References deinit().
Member Function Documentation
connected()
virtual bool linux_pinout_server_socket::connected () inline virtual
Definition at line 352 of file linux_pinout_server_socket.hpp.
References hSocket.
dataready()
virtual bool linux_pinout_server_socket::dataready () const inline virtual
Implements IUart.
Definition at line 195 of file linux_pinout_server_socket.hpp.
References formatf(), and hSocket.
deinit()
virtual void linux_pinout_server_socket::deinit () inline virtual
Definition at line 183 of file linux_pinout_server_socket.hpp.
References formatf(), hServer, and hSocket.
Referenced by init(), and ~linux_pinout_server_socket().
flushoutput()
virtual void linux_pinout_server_socket::flushoutput () inline virtual
Implements IUart.
Definition at line 332 of file linux_pinout_server_socket.hpp.
References hSocket.
getcqq()
virtual char linux_pinout_server_socket::getcqq () inline virtual
Implements IUart.
Definition at line 227 of file linux_pinout_server_socket.hpp.
References formatf(), hSocket, Silent, and SocketConnect().
init()
virtual int linux_pinout_server_socket::init (const uint32_t HostPort, const char * HostName) inline virtual
Definition at line 65 of file linux_pinout_server_socket.hpp.
References Address, deinit(), formatf(), HOST_NAME_SIZE, hServer, hSocket, IUart::IUartOK, nAddressSize, and SocketConnect().
isopen()
virtual bool linux_pinout_server_socket::isopen () const inline virtual
Implements IUart.
Definition at line 353 of file linux_pinout_server_socket.hpp.
References hSocket.
purgeinput()
virtual void linux_pinout_server_socket::purgeinput () inline virtual
Implements IUart.
Definition at line 347 of file linux_pinout_server_socket.hpp.
putcqq()
virtual char linux_pinout_server_socket::putcqq (char c) inline virtual
Implements IUart.
Definition at line 304 of file linux_pinout_server_socket.hpp.
References formatf(), hSocket, Silent, and SocketConnect().
silent()
void linux_pinout_server_socket::silent (const bool s) inline
Definition at line 354 of file linux_pinout_server_socket.hpp.
References Silent.
SocketConnect()
int linux_pinout_server_socket::SocketConnect () inline
Definition at line 159 of file linux_pinout_server_socket.hpp.
References Address, formatf(), hServer, hSocket, IUart::IUartOK, and nAddressSize.
Referenced by getcqq(), init(), and putcqq().
Member Data Documentation
Address
struct sockaddr_in linux_pinout_server_socket::Address private
Definition at line 360 of file linux_pinout_server_socket.hpp.
Referenced by init(), and SocketConnect().
hServer
int linux_pinout_server_socket::hServer private
Definition at line 359 of file linux_pinout_server_socket.hpp.
Referenced by deinit(), init(), and SocketConnect().
hSocket
int linux_pinout_server_socket::hSocket private
Definition at line 358 of file linux_pinout_server_socket.hpp.
Referenced by connected(), dataready(), deinit(), flushoutput(), getcqq(), init(), isopen(), putcqq(), and SocketConnect().
nAddressSize
int linux_pinout_server_socket::nAddressSize private
Definition at line 361 of file linux_pinout_server_socket.hpp.
Referenced by init(), and SocketConnect().
nHostAddress
long linux_pinout_server_socket::nHostAddress private
Definition at line 362 of file linux_pinout_server_socket.hpp.
Silent
bool linux_pinout_server_socket::Silent private
Definition at line 363 of file linux_pinout_server_socket.hpp.
Referenced by getcqq(), putcqq(), and silent().
The documentation for this class was generated from the following file:
linux_pinout_server_socket.hpp