ESC FilterWheel C++ Source: CmdHandlersBinary.cpp File Reference
CmdHandlersBinary.cpp File Reference
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
#include <inttypes.h>
#include <unordered_map>
#include "uart/BinaryUart.hpp"
#include "cgraph/CGraphPacket.hpp"
#include "cgraph/CGraphFSMHardwareInterface.hpp"
#include "../MonitorAdc.hpp"
#include "MainBuildNum"
#include "CmdTableBinary.hpp"
Functions
int8_t BinaryVersionCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
Copyright (c) by Franks Development, LLC.
int8_t BinaryFSMDacsCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t BinaryFSMAdcsCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t BinaryFSMAdcsFloatingPointCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t BinaryFSMDacsFloatingPointCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t BinaryFSMStatusCommand (const uint32_t Name, char const *Params, const size_t ParamsLen, const void *Argument)
Variables
CGraphFSMHardwareInterface * FSM
CGraphFSMMonitorAdc MonitorAdc
Function Documentation
BinaryFSMAdcsCommand()
int8_t BinaryFSMAdcsCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 85 of file CmdHandlersBinary.cpp.
References CGraphFSMHardwareInterface::AdcAAccumulator, CGraphFSMHardwareInterface::AdcBAccumulator, CGraphFSMHardwareInterface::AdcCAccumulator, CGraphPayloadTypeFSMAdcs, FSM, Samples, and TxBinaryPacket().
BinaryFSMAdcsFloatingPointCommand()
int8_t BinaryFSMAdcsFloatingPointCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 96 of file CmdHandlersBinary.cpp.
References CGraphFSMHardwareInterface::AdcAAccumulator, CGraphFSMHardwareInterface::AdcBAccumulator, CGraphFSMHardwareInterface::AdcCAccumulator, CGraphPayloadTypeFSMAdcsFloatingPoint, FSM, AdcAccumulator::NumAccums, AdcAccumulator::Samples, and TxBinaryPacket().
BinaryFSMDacsCommand()
int8_t BinaryFSMDacsCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 65 of file CmdHandlersBinary.cpp.
References CGraphPayloadTypeFSMDacs, CGraphFSMHardwareInterface::DacASetpoint, CGraphFSMHardwareInterface::DacBSetpoint, CGraphFSMHardwareInterface::DacCSetpoint, DacSetpoints, FSM, and TxBinaryPacket().
BinaryFSMDacsFloatingPointCommand()
int8_t BinaryFSMDacsFloatingPointCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 114 of file CmdHandlersBinary.cpp.
References CGraphPayloadTypeFSMDacsFloatingPoint, CGraphFSMHardwareInterface::DacASetpoint, CGraphFSMHardwareInterface::DacBSetpoint, CGraphFSMHardwareInterface::DacCSetpoint, DacSetpoints, FSM, and TxBinaryPacket().
BinaryFSMStatusCommand()
int8_t BinaryFSMStatusCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 158 of file CmdHandlersBinary.cpp.
References CGraphPayloadTypeFSMTelemetry, formatf(), CGraphFSMMonitorAdc::GetP1V2(), CGraphFSMMonitorAdc::GetP2V2(), CGraphFSMMonitorAdc::GetP2V5(), CGraphFSMMonitorAdc::GetP3V3D(), CGraphFSMMonitorAdc::GetP4V3(), CGraphFSMMonitorAdc::GetP5V(), CGraphFSMMonitorAdc::GetP6V(), MonitorAdc, CGraphFSMTelemetryPayload::N5V, CGraphFSMTelemetryPayload::N6V, CGraphFSMTelemetryPayload::P150V, CGraphFSMTelemetryPayload::P1V2, CGraphFSMTelemetryPayload::P28V, CGraphFSMTelemetryPayload::P2V2, CGraphFSMTelemetryPayload::P2V5, CGraphFSMTelemetryPayload::P3V3A, CGraphFSMTelemetryPayload::P3V3D, CGraphFSMTelemetryPayload::P4V3, CGraphFSMTelemetryPayload::P5V, CGraphFSMTelemetryPayload::P6V, and TxBinaryPacket().
BinaryVersionCommand()
int8_t BinaryVersionCommand (const uint32_t Name, char const * Params, const size_t ParamsLen, const void * Argument)
Copyright (c) by Franks Development, LLC.
Definition at line 45 of file CmdHandlersBinary.cpp.
References CGraphPayloadTypeVersion, CGraphFSMHardwareInterface::DeviceSerialNumber, CGraphVersionPayload::formatf(), CGraphVersionPayload::FPGAFirmwareBuildNum, CGraphFSMHardwareInterface::FpgaFirmwareBuildNumber, FSM, CGraphVersionPayload::ProcessorFirmwareBuildNum, CGraphVersionPayload::SerialNum, and TxBinaryPacket().
Variable Documentation
FSM
CGraphFSMHardwareInterface* FSM extern
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 74 of file Main.cpp.
Referenced by BinaryFSMAdcsCommand(), BinaryFSMAdcsFloatingPointCommand(), BinaryFSMDacsCommand(), BinaryFSMDacsFloatingPointCommand(), and BinaryVersionCommand().
MonitorAdc
CGraphFSMMonitorAdc MonitorAdc extern
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
based on a framework Copyright (c) 2009 by Franks Development, LLC, used with permission
Definition at line 18 of file MonitorAdc.cpp.
Referenced by BinaryFSMStatusCommand().