ESC FilterWheel C++ Source: CmdTableAscii.cpp File Reference
CmdTableAscii.cpp File Reference
Copyright (c) by Franks Development, LLC.
#include <stdint.h>
#include "uart/CmdSystem.hpp"
#include "../MonitorAdc.hpp"
#include "CmdTableAscii.hpp"
Variables
const Cmd AsciiCmds []
The actual table (array) of commands for the system - links with CmdSystem.cpp.o.
const uint8_t NumAsciiCmds = sizeof(AsciiCmds) / sizeof(AsciiCmds[0])
Detailed Description
Copyright (c) by Franks Development, LLC.
Source
/raincloud/src/clients/UACGraph/Zeus/Zeus3/firmware/arm/main/CmdTable.hpp,v
Revision
1.27
Date
2010/06/08 23:54:01
Author
summer
Definition in file CmdTableAscii.cpp.
Variable Documentation
AsciiCmds
const Cmd AsciiCmds[]
The actual table (array) of commands for the system - links with CmdSystem.cpp.o.
Copyright (c) by Franks Development, LLC.
Definition at line 37 of file CmdTableAscii.cpp.
Referenced by ParseConfigFile(), ProcessUserInterface(), and StartUserInterface().
NumAsciiCmds
const uint8_t NumAsciiCmds = sizeof(AsciiCmds) / sizeof(AsciiCmds[0])
Definition at line 191 of file CmdTableAscii.cpp.
Referenced by ParseConfigFile(), ProcessUserInterface(), and StartUserInterface().