ESC FilterWheel C++ Source: CmdTableAscii.hpp File Reference
CmdTableAscii.hpp File Reference
Copyright (c) by Franks Development, LLC.
#include <stdint.h>
#include "uart/CmdSystem.hpp"
Functions
int8_t VersionCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t HelpCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t ReadFpgaCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t WriteFpgaCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t FSMDacsCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t VoltageCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t FSMAdcsCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t BISTCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t CirclesCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t GoXYCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t UartCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t BaudDividersCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t PrintBuffersCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t MonitorSerialCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
Variables
const Cmd AsciiCmds []
The actual table (array) of commands for the system - links with CmdSystem.cpp.o.
const uint8_t NumAsciiCmds
Detailed Description
Copyright (c) by Franks Development, LLC.
Source
/raincloud/src/clients/UACGraph/Zeus/Zeus3/firmware/arm/main/CmdTable.hpp,v
Revision
1.27
Date
2010/06/08 23:54:01
Author
summer
Definition in file CmdTableAscii.hpp.
Function Documentation
BaudDividersCommand()
int8_t BaudDividersCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 651 of file CmdHandlersAscii.cpp.
References CGraphFSMHardwareInterface::BaudDividers, CGraphBaudDividers::Divider0, CGraphBaudDividers::Divider1, CGraphBaudDividers::Divider2, CGraphBaudDividers::Divider3, and FSM.
BISTCommand()
int8_t BISTCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 310 of file CmdHandlersAscii.cpp.
References formatf(), CGraphFSMMonitorAdc::GetP1V2(), CGraphFSMMonitorAdc::GetP28V(), CGraphFSMMonitorAdc::GetP2V2(), CGraphFSMMonitorAdc::GetP2V5(), CGraphFSMMonitorAdc::GetP3V3D(), CGraphFSMMonitorAdc::GetP4V3(), CGraphFSMMonitorAdc::GetP5V(), CGraphFSMMonitorAdc::GetP6V(), and MonitorAdc.
CirclesCommand()
int8_t CirclesCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 391 of file CmdHandlersAscii.cpp.
References CGraphFSMHardwareInterface::DacASetpoint, CGraphFSMHardwareInterface::DacBSetpoint, CGraphFSMHardwareInterface::DacCSetpoint, and FSM.
FSMAdcsCommand()
int8_t FSMAdcsCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 246 of file CmdHandlersAscii.cpp.
References CGraphFSMHardwareInterface::AdcAAccumulator, CGraphFSMHardwareInterface::AdcBAccumulator, CGraphFSMHardwareInterface::AdcCAccumulator, AdcAccumulator::all, FSM, AdcAccumulator::NumAccums, and AdcAccumulator::Samples.
FSMDacsCommand()
int8_t FSMDacsCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 139 of file CmdHandlersAscii.cpp.
References CGraphFSMHardwareInterface::AdcAAccumulator, CGraphFSMHardwareInterface::AdcBAccumulator, CGraphFSMHardwareInterface::AdcCAccumulator, AdcAccumulator::all, CGraphFSMHardwareInterface::DacASetpoint, CGraphFSMHardwareInterface::DacBSetpoint, CGraphFSMHardwareInterface::DacCSetpoint, FSM, AdcAccumulator::NumAccums, and AdcAccumulator::Samples.
GoXYCommand()
int8_t GoXYCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 467 of file CmdHandlersAscii.cpp.
References CGraphFSMHardwareInterface::AdcAAccumulator, CGraphFSMHardwareInterface::AdcBAccumulator, CGraphFSMHardwareInterface::AdcCAccumulator, AdcAccumulator::all, CGraphFSMHardwareInterface::DacASetpoint, CGraphFSMHardwareInterface::DacBSetpoint, CGraphFSMHardwareInterface::DacCSetpoint, FSM, AdcAccumulator::NumAccums, and AdcAccumulator::Samples.
HelpCommand()
int8_t HelpCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
MonitorSerialCommand()
int8_t MonitorSerialCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 724 of file CmdHandlersAscii.cpp.
References formatf(), FPGAUartPinout0, FPGAUartPinout1, FPGAUartPinout2, FPGAUartPinout3, and uart_pinout_fpga::Monitor().
PrintBuffersCommand()
int8_t PrintBuffersCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 713 of file CmdHandlersAscii.cpp.
References BinaryUart::formatf(), FpgaUartParser1, FpgaUartParser2, and FpgaUartParser3.
ReadFpgaCommand()
int8_t ReadFpgaCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 84 of file CmdHandlersAscii.cpp.
References FSM.
UartCommand()
int8_t UartCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 523 of file CmdHandlersAscii.cpp.
References CGraphPayloadTypeVersion, CGraphFSMHardwareInterface::DeviceSerialNumber, CGraphVersionPayload::formatf(), CGraphVersionPayload::FPGAFirmwareBuildNum, CGraphFSMHardwareInterface::FpgaFirmwareBuildNumber, FpgaUartParser1, FpgaUartParser2, FpgaUartParser3, FSM, CGraphVersionPayload::ProcessorFirmwareBuildNum, CGraphVersionPayload::SerialNum, TxBinaryPacket(), UartFifo2, CGraphFSMHardwareInterface::UartFifo2, and UartStatusRegister2.
VersionCommand()
int8_t VersionCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 70 of file CmdHandlersAscii.cpp.
References CGraphFSMHardwareInterface::DeviceSerialNumber, CGraphFSMHardwareInterface::FpgaFirmwareBuildNumber, and FSM.
VoltageCommand()
int8_t VoltageCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 196 of file CmdHandlersAscii.cpp.
References CGraphFSMHardwareInterface::DacASetpoint, CGraphFSMHardwareInterface::DacBSetpoint, CGraphFSMHardwareInterface::DacCSetpoint, and FSM.
WriteFpgaCommand()
int8_t WriteFpgaCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 117 of file CmdHandlersAscii.cpp.
References FSM.
Variable Documentation
AsciiCmds
const Cmd AsciiCmds[] extern
The actual table (array) of commands for the system - links with CmdSystem.cpp.o.
Definition at line 37 of file CmdTableAscii.cpp.
NumAsciiCmds
const uint8_t NumAsciiCmds extern
Definition at line 191 of file CmdTableAscii.cpp.