ESC FilterWheel C++ Source: Delay.h File Reference
Delay.h File Reference
Functions
void delayus (const unsigned long microseconds)
Copyright (c) by Franks Development, LLC.
void delayms (const unsigned long milliseconds)
void delays (const unsigned long seconds)
Function Documentation
delayms()
void delayms (const unsigned long milliseconds)
Definition at line 70 of file DelayLinux.cpp.
References delayus().
Referenced by delays().
delays()
void delays (const unsigned long seconds)
Definition at line 75 of file DelayLinux.cpp.
References delayms().
delayus()
void delayus (const unsigned long microseconds)
Copyright (c) by Franks Development, LLC.
This abstraction implements the Delay Bus; derive class to adapt it to your uC/hardware
Definition at line 46 of file DelayLinux.cpp.
References delay.
Referenced by ads1258< spipinout >::ConvertOnceDiff(), delayms(), EzThread::EzThreadFunc(), ads1258< spipinout >::Init(), lt244x< pinout, spi, SpiClkDiv >::ReadChannel(), lt244x< pinout, spi, SpiClkDiv >::ReadChannel(), ads1258< spipinout >::spi_busmsg::spi_busmsg(), lt244x< pinout, spi, SpiClkDiv >::StillConverting(), PinoutMonitorAdc::waitbusytimeout(), lt244x< pinout, spi, SpiClkDiv >::XferData(), and ads1258< spipinout >::spi_busmsg::~spi_busmsg().