ESC FilterWheel C++ Source: MonitorAdc.cpp File Reference
MonitorAdc.cpp File Reference
#include <time.h>
#include <ctype.h>
#include "Delay.h"
#include "MonitorAdc.hpp"
Functions
int8_t ScanMonitorAdcCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t TestMonitorAdcCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
int8_t CalibrateMonitorAdcCommand (char const *Name, char const *Params, const size_t ParamsLen, const void *Argument)
Variables
CGraphFSMMonitorAdc MonitorAdc
MonitorAdcCalibratedInput P1V2Calibrate (1.0, 0.0)
MonitorAdcCalibratedInput P2V2Calibrate (2.0, 0.0)
MonitorAdcCalibratedInput P28VCalibrate (16.0, 0.0)
MonitorAdcCalibratedInput P2V5Calibrate (2.0, 0.0)
MonitorAdcCalibratedInput P3V3DCalibrate (2.0, 0.0)
MonitorAdcCalibratedInput P6VCalibrate (4.922, 0.0)
MonitorAdcCalibratedInput P5VCalibrate (4.922, 0.0)
MonitorAdcCalibratedInput P4V3Calibrate (3.0, 0.0)
MonitorAdcCalibratedInput P2I2Calibrate (1.0, 0.0)
MonitorAdcCalibratedInput P4I3Calibrate (1.0, 0.0)
MonitorAdcCalibratedInput P6ICalibrate (1.0, 0.0)
MonitorAdcCalibratedInput Aux0Calibrate (1.0, 0.0)
MonitorAdcCalibratedInput Aux1Calibrate (1.0, 0.0)
MonitorAdcCalibratedInput Aux2Calibrate (1.0, 0.0)
MonitorAdcCalibratedInput AmbientLightCalibrate (1.0, 0.0)
MonitorAdcCalibratedInput TemperatureCalibrate (1.0, 0.0)
const char ScanMonitorAdcCmdString [] = "SCANMONITORADC"
const char ScanMonitorAdcHelp [] = "\"ScanMonitorAdc\"; Show current input voltages..."
const char TestMonitorAdcCmdString [] = "TESTMONITORADC"
const char TestMonitorAdcHelp [] = "\"TestMonitorAdc\"; Show raw A/D counts..."
const char CalibrateMonitorAdcCmdString [] = "CALIBRATEMONITORADC"
const char CalibrateMonitorAdcHelp [] = "\"CalibrateMonitorAdc <readout>,<gain>(optional),<offset>(optional)\"; Calibrate (or query) the given readout"
Function Documentation
CalibrateMonitorAdcCommand()
int8_t CalibrateMonitorAdcCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 132 of file MonitorAdc.cpp.
References AmbientLightCalibrate, Aux0Calibrate, Aux1Calibrate, Aux2Calibrate, MonitorAdcCalibratedInput::Calibrate(), formatf(), MonitorAdcCalibratedInput::GetGain(), MonitorAdcCalibratedInput::GetOffset(), P1V2Calibrate, P28VCalibrate, P2I2Calibrate, P2V2Calibrate, P2V5Calibrate, P3V3DCalibrate, P4I3Calibrate, P4V3Calibrate, P5VCalibrate, P6ICalibrate, P6VCalibrate, and TemperatureCalibrate.
ScanMonitorAdcCommand()
int8_t ScanMonitorAdcCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 57 of file MonitorAdc.cpp.
References formatf(), CGraphFSMMonitorAdc::GetAmbientLight(), CGraphFSMMonitorAdc::GetAux0(), CGraphFSMMonitorAdc::GetAux1(), CGraphFSMMonitorAdc::GetAux2(), CGraphFSMMonitorAdc::GetP1V2(), CGraphFSMMonitorAdc::GetP28V(), CGraphFSMMonitorAdc::GetP2I2(), CGraphFSMMonitorAdc::GetP2V2(), CGraphFSMMonitorAdc::GetP2V5(), CGraphFSMMonitorAdc::GetP3V3D(), CGraphFSMMonitorAdc::GetP4I3(), CGraphFSMMonitorAdc::GetP4V3(), CGraphFSMMonitorAdc::GetP5V(), CGraphFSMMonitorAdc::GetP6I(), CGraphFSMMonitorAdc::GetP6V(), CGraphFSMMonitorAdc::GetTemperature(), and MonitorAdc.
TestMonitorAdcCommand()
int8_t TestMonitorAdcCommand (char const * Name, char const * Params, const size_t ParamsLen, const void * Argument)
Definition at line 84 of file MonitorAdc.cpp.
References formatf(), CGraphFSMMonitorAdc::GetAmbientLightRaw(), CGraphFSMMonitorAdc::GetAux0Raw(), CGraphFSMMonitorAdc::GetAux1Raw(), CGraphFSMMonitorAdc::GetAux2Raw(), CGraphFSMMonitorAdc::GetP1V2Raw(), CGraphFSMMonitorAdc::GetP28VRaw(), CGraphFSMMonitorAdc::GetP2I2Raw(), CGraphFSMMonitorAdc::GetP2V2Raw(), CGraphFSMMonitorAdc::GetP2V5Raw(), CGraphFSMMonitorAdc::GetP3V3DRaw(), CGraphFSMMonitorAdc::GetP4I3Raw(), CGraphFSMMonitorAdc::GetP4V3Raw(), CGraphFSMMonitorAdc::GetP5VRaw(), CGraphFSMMonitorAdc::GetP6IRaw(), CGraphFSMMonitorAdc::GetP6VRaw(), CGraphFSMMonitorAdc::GetTemperatureRaw(), MonitorAdc, and Sample.
Variable Documentation
AmbientLightCalibrate
MonitorAdcCalibratedInput AmbientLightCalibrate(1.0, 0.0) (1. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
Aux0Calibrate
MonitorAdcCalibratedInput Aux0Calibrate(1.0, 0.0) (1. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
Aux1Calibrate
MonitorAdcCalibratedInput Aux1Calibrate(1.0, 0.0) (1. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
Aux2Calibrate
MonitorAdcCalibratedInput Aux2Calibrate(1.0, 0.0) (1. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
CalibrateMonitorAdcCmdString
const char CalibrateMonitorAdcCmdString[] = "CALIBRATEMONITORADC"
Definition at line 130 of file MonitorAdc.cpp.
CalibrateMonitorAdcHelp
const char CalibrateMonitorAdcHelp[] = "\"CalibrateMonitorAdc <readout>,<gain>(optional),<offset>(optional)\"; Calibrate (or query) the given readout"
Definition at line 131 of file MonitorAdc.cpp.
MonitorAdc
CGraphFSMMonitorAdc MonitorAdc
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
based on a framework Copyright (c) 2009 by Franks Development, LLC, used with permission
Definition at line 18 of file MonitorAdc.cpp.
Referenced by BinaryFSMStatusCommand(), BISTCommand(), main(), Process(), ScanMonitorAdcCommand(), and TestMonitorAdcCommand().
P1V2Calibrate
MonitorAdcCalibratedInput P1V2Calibrate(1.0, 0.0) (1. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
P28VCalibrate
MonitorAdcCalibratedInput P28VCalibrate(16.0, 0.0) (16. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
P2I2Calibrate
MonitorAdcCalibratedInput P2I2Calibrate(1.0, 0.0) (1. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
P2V2Calibrate
MonitorAdcCalibratedInput P2V2Calibrate(2.0, 0.0) (2. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
P2V5Calibrate
MonitorAdcCalibratedInput P2V5Calibrate(2.0, 0.0) (2. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
P3V3DCalibrate
MonitorAdcCalibratedInput P3V3DCalibrate(2.0, 0.0) (2. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
P4I3Calibrate
MonitorAdcCalibratedInput P4I3Calibrate(1.0, 0.0) (1. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
P4V3Calibrate
MonitorAdcCalibratedInput P4V3Calibrate(3.0, 0.0) (3. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
P5VCalibrate
MonitorAdcCalibratedInput P5VCalibrate(4.922, 0.0) (4. 922, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
P6ICalibrate
MonitorAdcCalibratedInput P6ICalibrate(1.0, 0.0) (1. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
P6VCalibrate
MonitorAdcCalibratedInput P6VCalibrate(4.922, 0.0) (4. 922, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
ScanMonitorAdcCmdString
const char ScanMonitorAdcCmdString[] = "SCANMONITORADC"
Definition at line 55 of file MonitorAdc.cpp.
ScanMonitorAdcHelp
const char ScanMonitorAdcHelp[] = "\"ScanMonitorAdc\"; Show current input voltages..."
Definition at line 56 of file MonitorAdc.cpp.
TemperatureCalibrate
MonitorAdcCalibratedInput TemperatureCalibrate(1.0, 0.0) (1. 0, 0. 0)
Referenced by CalibrateMonitorAdcCommand().
TestMonitorAdcCmdString
const char TestMonitorAdcCmdString[] = "TESTMONITORADC"
Definition at line 82 of file MonitorAdc.cpp.
TestMonitorAdcHelp
const char TestMonitorAdcHelp[] = "\"TestMonitorAdc\"; Show raw A/D counts..."
Definition at line 83 of file MonitorAdc.cpp.