ESC FilterWheel C++ Source: FPGABinaryUartCallbacks Struct Reference
FPGABinaryUartCallbacks Struct Reference
Public Member Functions
FPGABinaryUartCallbacks ()
virtual ~FPGABinaryUartCallbacks ()
virtual void InvalidPacket (const uint8_t *Buffer, const size_t &BufferLen)
virtual void UnHandledPacket (const IPacket *Packet, const size_t &PacketLen)
virtual void BufferOverflow (const uint8_t *Buffer, const size_t &BufferLen)
FPGABinaryUartCallbacks ()
virtual ~FPGABinaryUartCallbacks ()
virtual void InvalidPacket (const uint8_t *Buffer, const size_t &BufferLen) override
virtual void UnHandledPacket (const IPacket *Packet, const size_t &PacketLen) override
virtual void BufferOverflow (const uint8_t *Buffer, const size_t &BufferLen) override
Public Member Functions inherited from BinaryUartCallbacks
BinaryUartCallbacks ()
virtual ~BinaryUartCallbacks ()
virtual void EveryPacket (const IPacket *Packet, const size_t &PacketLen)
BinaryUartCallbacks ()
virtual ~BinaryUartCallbacks ()
virtual void EveryPacket (const IPacket *Packet, const size_t &PacketLen)
Detailed Description
Definition at line 34 of file Main.cpp.
Constructor & Destructor Documentation
FPGABinaryUartCallbacks() [1/2]
FPGABinaryUartCallbacks::FPGABinaryUartCallbacks () inline
Definition at line 36 of file Main.cpp.
~FPGABinaryUartCallbacks() [1/2]
virtual FPGABinaryUartCallbacks::~FPGABinaryUartCallbacks () inline virtual
Definition at line 37 of file Main.cpp.
FPGABinaryUartCallbacks() [2/2]
FPGABinaryUartCallbacks::FPGABinaryUartCallbacks () inline
Definition at line 43 of file Uarts.cpp.
~FPGABinaryUartCallbacks() [2/2]
virtual FPGABinaryUartCallbacks::~FPGABinaryUartCallbacks () inline virtual
Definition at line 44 of file Uarts.cpp.
Member Function Documentation
BufferOverflow() [1/2]
virtual void FPGABinaryUartCallbacks::BufferOverflow (const uint8_t * Buffer, const size_t & BufferLen) inline virtual
Reimplemented from BinaryUartCallbacks.
Definition at line 66 of file Main.cpp.
BufferOverflow() [2/2]
virtual void FPGABinaryUartCallbacks::BufferOverflow (const uint8_t * Buffer, const size_t & BufferLen) inline override virtual
Reimplemented from BinaryUartCallbacks.
Definition at line 73 of file Uarts.cpp.
InvalidPacket() [1/2]
virtual void FPGABinaryUartCallbacks::InvalidPacket (const uint8_t * Buffer, const size_t & BufferLen) inline virtual
Reimplemented from BinaryUartCallbacks.
Definition at line 40 of file Main.cpp.
References Buffer, and formatf().
InvalidPacket() [2/2]
virtual void FPGABinaryUartCallbacks::InvalidPacket (const uint8_t * Buffer, const size_t & BufferLen) inline override virtual
Reimplemented from BinaryUartCallbacks.
Definition at line 47 of file Uarts.cpp.
References Buffer, and formatf().
UnHandledPacket() [1/2]
virtual void FPGABinaryUartCallbacks::UnHandledPacket (const IPacket * Packet, const size_t & PacketLen) inline virtual
Reimplemented from BinaryUartCallbacks.
Definition at line 52 of file Main.cpp.
References formatf(), and CGraphPacketHeader::formatf().
UnHandledPacket() [2/2]
virtual void FPGABinaryUartCallbacks::UnHandledPacket (const IPacket * Packet, const size_t & PacketLen) inline override virtual
Reimplemented from BinaryUartCallbacks.
Definition at line 59 of file Uarts.cpp.
References formatf(), and CGraphPacketHeader::formatf().
The documentation for this struct was generated from the following files:
Main.cpp
Uarts.cpp