ESC FilterWheel C++ Source: PinoutMonitorAdc Struct Reference
PinoutMonitorAdc Struct Reference
#include <MonitorAdc.hpp>
Public Member Functions
PinoutMonitorAdc ()
virtual ~PinoutMonitorAdc ()
Static Public Member Functions
static uint8_t GetAdcReadChannel ()
static void SetAdcReadChannel (const uint8_t val)
static bool busy ()
static void waitbusytimeout ()
static void enable (const bool en)
static void transmit (const uint8_t val)
static uint8_t receive (uint8_t val)
static bool nDrdy ()
static void setclkpolarity (const bool en)
static void setclkphase (const bool en)
Static Public Attributes
static const size_t spi_timeout = 100
Detailed Description
Definition at line 35 of file MonitorAdc.hpp.
Constructor & Destructor Documentation
PinoutMonitorAdc()
PinoutMonitorAdc::PinoutMonitorAdc () inline
Definition at line 37 of file MonitorAdc.hpp.
~PinoutMonitorAdc()
virtual PinoutMonitorAdc::~PinoutMonitorAdc () inline virtual
Definition at line 38 of file MonitorAdc.hpp.
Member Function Documentation
busy()
static bool PinoutMonitorAdc::busy () inline static
Definition at line 45 of file MonitorAdc.hpp.
References FSM, CGraphFSMHardwareInterface::MonitorAdcSpiCommandStatusRegister, and CGraphMonitorAdcCommandStatusRegister::TransactionComplete.
Referenced by waitbusytimeout().
enable()
static void PinoutMonitorAdc::enable (const bool en) inline static
Definition at line 57 of file MonitorAdc.hpp.
References CGraphMonitorAdcCommandStatusRegister::all, FSM, and CGraphFSMHardwareInterface::MonitorAdcSpiCommandStatusRegister.
GetAdcReadChannel()
static uint8_t PinoutMonitorAdc::GetAdcReadChannel () inline static
Definition at line 39 of file MonitorAdc.hpp.
References FSM, and MonitorAdcFpgaAdcChannelAddr.
nDrdy()
static bool PinoutMonitorAdc::nDrdy () inline static
Definition at line 80 of file MonitorAdc.hpp.
References FSM, CGraphFSMHardwareInterface::MonitorAdcSpiCommandStatusRegister, and CGraphMonitorAdcCommandStatusRegister::nDrdy.
receive()
static uint8_t PinoutMonitorAdc::receive (uint8_t val) inline static
Definition at line 65 of file MonitorAdc.hpp.
References FSM, CGraphFSMHardwareInterface::MonitorAdcSpiTransactionRegister, and waitbusytimeout().
SetAdcReadChannel()
static void PinoutMonitorAdc::SetAdcReadChannel (const uint8_t val) inline static
Definition at line 40 of file MonitorAdc.hpp.
References FSM, and MonitorAdcFpgaAdcChannelAddr.
setclkphase()
static void PinoutMonitorAdc::setclkphase (const bool en) inline static
Definition at line 86 of file MonitorAdc.hpp.
setclkpolarity()
static void PinoutMonitorAdc::setclkpolarity (const bool en) inline static
Definition at line 85 of file MonitorAdc.hpp.
transmit()
static void PinoutMonitorAdc::transmit (const uint8_t val) inline static
Definition at line 59 of file MonitorAdc.hpp.
References FSM, CGraphFSMHardwareInterface::MonitorAdcSpiTransactionRegister, and waitbusytimeout().
waitbusytimeout()
static void PinoutMonitorAdc::waitbusytimeout () inline static
Definition at line 46 of file MonitorAdc.hpp.
References busy(), delayus(), formatf(), and spi_timeout.
Referenced by receive(), and transmit().
Member Data Documentation
spi_timeout
const size_t PinoutMonitorAdc::spi_timeout = 100 static
Definition at line 43 of file MonitorAdc.hpp.
Referenced by waitbusytimeout().
The documentation for this struct was generated from the following file:
MonitorAdc.hpp