ESC FilterWheel C++ Source: BinaryUartRingBuffer Struct Reference
BinaryUartRingBuffer Struct Reference
#include <BinaryUartRingBuffer.hpp>
Public Member Functions
BinaryUartRingBuffer (IArray &data, FpgaRingBufferCrcer &crcer, IPacket &packet, struct IBlockDevice &pinout, const BinaryCmd *cmds, const size_t numcmds, struct BinaryUartCallbacks &callbacks, const bool verbose=true, const uint64_t serialnum=InvalidSerialNumber)
Constructs a BinaryUartRingBuffer object and initializes with given parameters.
void Debug (bool dbg)
int Init (uint64_t serialnum=0)
Initializes the BinaryUartRingBuffer.
int InitFast (uint64_t serialnum=0)
bool Process ()
Processes incoming data and checks for new packets.
virtual void TxBinaryPacket (const uint16_t PayloadType, const uint32_t SerialNumber, const void *PayloadData, const size_t PayloadLength) const
Transmit a binary packet over UART.
void formatf () const
Public Attributes
size_t PacketEndPos = 0
Position of the detected packet end.
IArray & Data
FpgaRingBufferCrcer & Crcer
IPacket & Packet
Packet structure for defining headers, footers, etc.
IBlockDevice & Pinout
const BinaryCmd * Cmds
Array of commands.
size_t NumCmds
BinaryUartCallbacks & Callbacks
bool debug
bool InPacket
Whether a packet is currently being processed.
size_t PacketStartPos
size_t PacketLen
size_t PayloadLen
size_t HeaderLen
size_t FooterLen
uint64_t SerialNum
Serial number for validating received packets.
uint32_t LastDataLen
uint32_t PacketSearchedPos
Static Public Attributes
static const uint16_t LastDataLenInit = 0
Initial count for received bytes.
static const size_t PacketStartPosInit = 0
static const size_t PacketLenInit = 0
static const size_t PayloadLenInit = 0
static const size_t HeaderLenInit = 0
static const size_t FooterLenInit = 0
static const bool InPacketInit = false
Default in-packet status.
static const bool debugDefault = false
static const char EmptyBufferChar = '\0'
Character to fill empty buffer space.
static const size_t TxBufferLenBytes = 4096
static const uint64_t InvalidSerialNumber = 0xFFFFFFFFFFFFFFFFULL
Detailed Description
BinaryUartRingBuffer manages a UART interface for binary packet communication. It provides buffering for received bytes, detects packet boundaries, and processes commands within received packets.
Definition at line 38 of file BinaryUartRingBuffer.hpp.
Constructor & Destructor Documentation
BinaryUartRingBuffer()
BinaryUartRingBuffer::BinaryUartRingBuffer (IArray & data, FpgaRingBufferCrcer & crcer, IPacket & packet, struct IBlockDevice & pinout, const BinaryCmd * cmds, const size_t numcmds, struct BinaryUartCallbacks & callbacks, const bool verbose = true, const uint64_t serialnum = InvalidSerialNumber) inline
Constructs a BinaryUartRingBuffer object and initializes with given parameters.
Parameters
pinout UART interface to use for receiving data.
packet Packet structure defining header, footer, and payload format.
cmds Array of available commands.
numcmds Number of commands in the cmds array.
callbacks Callback functions for handling packet events.
verbose Enable or disable verbose debug mode.
serialnum Optional initial serial number, defaulting to InvalidSerialNumber.
Definition at line 86 of file BinaryUartRingBuffer.hpp.
References Init().
Member Function Documentation
Debug()
void BinaryUartRingBuffer::Debug (bool dbg) inline
Definition at line 113 of file BinaryUartRingBuffer.hpp.
References debug.
formatf()
void BinaryUartRingBuffer::formatf () const inline
Definition at line 407 of file BinaryUartRingBuffer.hpp.
References Data, formatf(), InPacket, LastDataLen, and PacketStartPos.
Referenced by formatf(), Init(), Process(), and TxBinaryPacket().
Init()
int BinaryUartRingBuffer::Init (uint64_t serialnum = 0) inline
Initializes the BinaryUartRingBuffer.
Initializes the BinaryUartRingBuffer with the specified serial number and resets the Rx buffer and other internal states. Called upon construction and after buffer overflows or other packet error states.
Parameters
serialnum Serial number to initialize, used for packet validation.
Returns
int status code, 0 for success.
Definition at line 128 of file BinaryUartRingBuffer.hpp.
References debug, FooterLen, IPacket::FooterLen(), FooterLenInit, formatf(), HeaderLen, IPacket::HeaderLen(), HeaderLenInit, InPacket, InPacketInit, LastDataLen, Packet, PacketLen, PacketLenInit, PacketSearchedPos, PacketStartPos, PacketStartPosInit, PayloadLen, PayloadLenInit, and SerialNum.
Referenced by BinaryUartRingBuffer().
InitFast()
int BinaryUartRingBuffer::InitFast (uint64_t serialnum = 0) inline
Definition at line 150 of file BinaryUartRingBuffer.hpp.
References FooterLen, FooterLenInit, HeaderLen, HeaderLenInit, InPacket, InPacketInit, LastDataLen, PacketLen, PacketLenInit, PacketSearchedPos, PacketStartPos, PacketStartPosInit, PayloadLen, PayloadLenInit, and SerialNum.
Process()
bool BinaryUartRingBuffer::Process () inline
Processes incoming data and checks for new packets.
Reads a new character if available, adds it to the Rx buffer, and checks for packet boundaries (start and end).
Returns
bool Returns true if data was processed, false if no new data.
Definition at line 178 of file BinaryUartRingBuffer.hpp.
References Callbacks, Cmds, IArray::CopyToFlatBuffer(), Crcer, Data, debug, IArray::Depth(), IPacket::DoesPayloadTypeMatch(), IPacket::EndTokenLen(), IPacket::FindPacketEndPos(), FooterLen, IPacket::FooterLen(), formatf(), HeaderLen, IPacket::HeaderLen(), BinaryUartCallbacks::InvalidPacket(), IPacket::IsValid(), LastDataLen, BinaryCmd::Name, NumCmds, Packet, PacketEndPos, PacketStartPos, PayloadLen, IPacket::PayloadLen(), IPacket::PayloadType(), IArray::PopMany(), BinaryCmd::Response, IPacket::ReverseFindPacketStartPos(), and BinaryUartCallbacks::UnHandledPacket().
TxBinaryPacket()
virtual void BinaryUartRingBuffer::TxBinaryPacket (const uint16_t PayloadType, const uint32_t SerialNumber, const void * PayloadData, const size_t PayloadLength) const inline virtual
Transmit a binary packet over UART.
Constructs a binary packet using the specified payload type, serial number, and payload data, and transmits it byte-by-byte over UART.
Parameters
PayloadType The type identifier for the packet. This distinguishes different commands in the packet.
SerialNumber The unique serial number for this packet.
PayloadData A pointer to the data to be transmitted as the packet payload.
PayloadLen The length of the payload data in bytes.
< Temporary buffer to hold the constructed packet
< Build packet
Definition at line 383 of file BinaryUartRingBuffer.hpp.
References debug, formatf(), IPacket::MakePacket(), Packet, PayloadData(), PayloadType, Pinout, IBlockDevice::puts(), and TxBufferLenBytes.
Member Data Documentation
Callbacks
BinaryUartCallbacks& BinaryUartRingBuffer::Callbacks
Definition at line 63 of file BinaryUartRingBuffer.hpp.
Referenced by Process().
Cmds
const BinaryCmd* BinaryUartRingBuffer::Cmds
Array of commands.
Definition at line 61 of file BinaryUartRingBuffer.hpp.
Referenced by Process().
Crcer
FpgaRingBufferCrcer& BinaryUartRingBuffer::Crcer
Definition at line 58 of file BinaryUartRingBuffer.hpp.
Referenced by Process().
Data
IArray& BinaryUartRingBuffer::Data
Definition at line 57 of file BinaryUartRingBuffer.hpp.
Referenced by formatf(), and Process().
debug
bool BinaryUartRingBuffer::debug
Definition at line 64 of file BinaryUartRingBuffer.hpp.
Referenced by Debug(), Init(), Process(), and TxBinaryPacket().
debugDefault
const bool BinaryUartRingBuffer::debugDefault = false static
Definition at line 48 of file BinaryUartRingBuffer.hpp.
EmptyBufferChar
const char BinaryUartRingBuffer::EmptyBufferChar = '\0' static
Character to fill empty buffer space.
Definition at line 49 of file BinaryUartRingBuffer.hpp.
FooterLen
size_t BinaryUartRingBuffer::FooterLen
Definition at line 70 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), InitFast(), and Process().
FooterLenInit
const size_t BinaryUartRingBuffer::FooterLenInit = 0 static
Definition at line 46 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), and InitFast().
HeaderLen
size_t BinaryUartRingBuffer::HeaderLen
Definition at line 69 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), InitFast(), and Process().
HeaderLenInit
const size_t BinaryUartRingBuffer::HeaderLenInit = 0 static
Definition at line 45 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), and InitFast().
InPacket
bool BinaryUartRingBuffer::InPacket
Whether a packet is currently being processed.
Definition at line 65 of file BinaryUartRingBuffer.hpp.
Referenced by formatf(), Init(), and InitFast().
InPacketInit
const bool BinaryUartRingBuffer::InPacketInit = false static
Default in-packet status.
Definition at line 47 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), and InitFast().
InvalidSerialNumber
const uint64_t BinaryUartRingBuffer::InvalidSerialNumber = 0xFFFFFFFFFFFFFFFFULL static
Definition at line 52 of file BinaryUartRingBuffer.hpp.
LastDataLen
uint32_t BinaryUartRingBuffer::LastDataLen
Definition at line 72 of file BinaryUartRingBuffer.hpp.
Referenced by formatf(), Init(), InitFast(), and Process().
LastDataLenInit
const uint16_t BinaryUartRingBuffer::LastDataLenInit = 0 static
Initial count for received bytes.
Definition at line 41 of file BinaryUartRingBuffer.hpp.
NumCmds
size_t BinaryUartRingBuffer::NumCmds
Definition at line 62 of file BinaryUartRingBuffer.hpp.
Referenced by Process().
Packet
IPacket& BinaryUartRingBuffer::Packet
Packet structure for defining headers, footers, etc.
Definition at line 59 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), Process(), and TxBinaryPacket().
PacketEndPos
size_t BinaryUartRingBuffer::PacketEndPos = 0
Position of the detected packet end.
Definition at line 54 of file BinaryUartRingBuffer.hpp.
Referenced by Process().
PacketLen
size_t BinaryUartRingBuffer::PacketLen
Definition at line 67 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), and InitFast().
PacketLenInit
const size_t BinaryUartRingBuffer::PacketLenInit = 0 static
Definition at line 43 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), and InitFast().
PacketSearchedPos
uint32_t BinaryUartRingBuffer::PacketSearchedPos
Definition at line 73 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), and InitFast().
PacketStartPos
size_t BinaryUartRingBuffer::PacketStartPos
Definition at line 66 of file BinaryUartRingBuffer.hpp.
Referenced by formatf(), Init(), InitFast(), and Process().
PacketStartPosInit
const size_t BinaryUartRingBuffer::PacketStartPosInit = 0 static
Definition at line 42 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), and InitFast().
PayloadLen
size_t BinaryUartRingBuffer::PayloadLen
Definition at line 68 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), InitFast(), and Process().
PayloadLenInit
const size_t BinaryUartRingBuffer::PayloadLenInit = 0 static
Definition at line 44 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), and InitFast().
Pinout
IBlockDevice& BinaryUartRingBuffer::Pinout
Definition at line 60 of file BinaryUartRingBuffer.hpp.
Referenced by TxBinaryPacket().
SerialNum
uint64_t BinaryUartRingBuffer::SerialNum
Serial number for validating received packets.
Definition at line 71 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), and InitFast().
TxBufferLenBytes
const size_t BinaryUartRingBuffer::TxBufferLenBytes = 4096 static
Definition at line 51 of file BinaryUartRingBuffer.hpp.
Referenced by TxBinaryPacket().
The documentation for this struct was generated from the following file:
BinaryUartRingBuffer.hpp