ESC FilterWheel C++ Source: CGraphFSMMonitorAdc Struct Reference
CGraphFSMMonitorAdc Struct Reference
#include <MonitorAdc.hpp>
Public Member Functions
CGraphFSMMonitorAdc ()
~CGraphFSMMonitorAdc ()
bool GetMonitor () const
void SetMonitor (bool monitor)
void Init ()
void Process ()
double GetP1V2 ()
double GetP2V2 ()
double GetP28V ()
double GetP2V5 ()
double GetP6V ()
double GetP5V ()
double GetP3V3D ()
double GetP4V3 ()
double GetP2I2 ()
double GetP4I3 ()
double GetP6I ()
double GetAux0 ()
double GetAux1 ()
double GetAux2 ()
double GetAmbientLight ()
double GetTemperature ()
void GetP1V2Raw (int32_t &val)
void GetP2V2Raw (int32_t &val)
void GetP28VRaw (int32_t &val)
void GetP2V5Raw (int32_t &val)
void GetP6VRaw (int32_t &val)
void GetP5VRaw (int32_t &val)
void GetP3V3DRaw (int32_t &val)
void GetP4V3Raw (int32_t &val)
void GetP2I2Raw (int32_t &val)
void GetP4I3Raw (int32_t &val)
void GetP6IRaw (int32_t &val)
void GetAux0Raw (int32_t &val)
void GetAux1Raw (int32_t &val)
void GetAux2Raw (int32_t &val)
void GetAmbientLightRaw (int32_t &val)
void GetTemperatureRaw (int32_t &val)
void SaveCals (double *Buffer, size_t &BufferMaxInBufferUsedOut)
void RestoreCals (const double *Buffer, size_t &BufferMaxInBufferUsedOut)
Public Attributes
ads1258< PinoutMonitorAdc > Adc
Private Attributes
bool AdcFound
bool Monitor
int32_t P1V2
int32_t P2V2
int32_t P28V
int32_t P2V5
int32_t P6V
int32_t P5V
int32_t P3V3D
int32_t P4V3
int32_t P2I2
int32_t P4I3
int32_t P6I
int32_t Aux0
int32_t Aux1
int32_t Aux2
int32_t AmbientLight
int32_t Temperature
Static Private Attributes
static const uint8_t GpioDirections = 0x00
static const uint8_t StartPinMask = 0x80
Detailed Description
Definition at line 129 of file MonitorAdc.hpp.
Constructor & Destructor Documentation
CGraphFSMMonitorAdc()
CGraphFSMMonitorAdc::CGraphFSMMonitorAdc () inline
Definition at line 164 of file MonitorAdc.hpp.
~CGraphFSMMonitorAdc()
CGraphFSMMonitorAdc::~CGraphFSMMonitorAdc () inline
Definition at line 169 of file MonitorAdc.hpp.
Member Function Documentation
GetAmbientLight()
double CGraphFSMMonitorAdc::GetAmbientLight () inline
Definition at line 328 of file MonitorAdc.hpp.
References AmbientLight, AmbientLightCalibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by ScanMonitorAdcCommand().
GetAmbientLightRaw()
void CGraphFSMMonitorAdc::GetAmbientLightRaw (int32_t & val) inline
Definition at line 345 of file MonitorAdc.hpp.
References AmbientLight.
Referenced by TestMonitorAdcCommand().
GetAux0()
double CGraphFSMMonitorAdc::GetAux0 () inline
Definition at line 325 of file MonitorAdc.hpp.
References Aux0, Aux0Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by ScanMonitorAdcCommand().
GetAux0Raw()
void CGraphFSMMonitorAdc::GetAux0Raw (int32_t & val) inline
Definition at line 342 of file MonitorAdc.hpp.
References Aux0.
Referenced by TestMonitorAdcCommand().
GetAux1()
double CGraphFSMMonitorAdc::GetAux1 () inline
Definition at line 326 of file MonitorAdc.hpp.
References Aux1, Aux1Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by ScanMonitorAdcCommand().
GetAux1Raw()
void CGraphFSMMonitorAdc::GetAux1Raw (int32_t & val) inline
Definition at line 343 of file MonitorAdc.hpp.
References Aux1.
Referenced by TestMonitorAdcCommand().
GetAux2()
double CGraphFSMMonitorAdc::GetAux2 () inline
Definition at line 327 of file MonitorAdc.hpp.
References Aux1Calibrate, Aux2, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by ScanMonitorAdcCommand().
GetAux2Raw()
void CGraphFSMMonitorAdc::GetAux2Raw (int32_t & val) inline
Definition at line 344 of file MonitorAdc.hpp.
References Aux2.
Referenced by TestMonitorAdcCommand().
GetMonitor()
bool CGraphFSMMonitorAdc::GetMonitor () const inline
Definition at line 195 of file MonitorAdc.hpp.
References Monitor.
GetP1V2()
double CGraphFSMMonitorAdc::GetP1V2 () inline
Definition at line 314 of file MonitorAdc.hpp.
References P1V2, P1V2Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFSMStatusCommand(), BISTCommand(), and ScanMonitorAdcCommand().
GetP1V2Raw()
void CGraphFSMMonitorAdc::GetP1V2Raw (int32_t & val) inline
Definition at line 331 of file MonitorAdc.hpp.
References P1V2.
Referenced by TestMonitorAdcCommand().
GetP28V()
double CGraphFSMMonitorAdc::GetP28V () inline
Definition at line 316 of file MonitorAdc.hpp.
References P28V, P28VCalibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BISTCommand(), and ScanMonitorAdcCommand().
GetP28VRaw()
void CGraphFSMMonitorAdc::GetP28VRaw (int32_t & val) inline
Definition at line 333 of file MonitorAdc.hpp.
References P28V.
Referenced by TestMonitorAdcCommand().
GetP2I2()
double CGraphFSMMonitorAdc::GetP2I2 () inline
Definition at line 322 of file MonitorAdc.hpp.
References P2I2, P2I2Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by ScanMonitorAdcCommand().
GetP2I2Raw()
void CGraphFSMMonitorAdc::GetP2I2Raw (int32_t & val) inline
Definition at line 339 of file MonitorAdc.hpp.
References P2I2.
Referenced by TestMonitorAdcCommand().
GetP2V2()
double CGraphFSMMonitorAdc::GetP2V2 () inline
Definition at line 315 of file MonitorAdc.hpp.
References P2V2, P2V2Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFSMStatusCommand(), BISTCommand(), and ScanMonitorAdcCommand().
GetP2V2Raw()
void CGraphFSMMonitorAdc::GetP2V2Raw (int32_t & val) inline
Definition at line 332 of file MonitorAdc.hpp.
References P2V2.
Referenced by TestMonitorAdcCommand().
GetP2V5()
double CGraphFSMMonitorAdc::GetP2V5 () inline
Definition at line 317 of file MonitorAdc.hpp.
References P2V5, P2V5Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFSMStatusCommand(), BISTCommand(), and ScanMonitorAdcCommand().
GetP2V5Raw()
void CGraphFSMMonitorAdc::GetP2V5Raw (int32_t & val) inline
Definition at line 334 of file MonitorAdc.hpp.
References P2V5.
Referenced by TestMonitorAdcCommand().
GetP3V3D()
double CGraphFSMMonitorAdc::GetP3V3D () inline
Definition at line 320 of file MonitorAdc.hpp.
References P3V3D, P3V3DCalibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFSMStatusCommand(), BISTCommand(), and ScanMonitorAdcCommand().
GetP3V3DRaw()
void CGraphFSMMonitorAdc::GetP3V3DRaw (int32_t & val) inline
Definition at line 337 of file MonitorAdc.hpp.
References P3V3D.
Referenced by TestMonitorAdcCommand().
GetP4I3()
double CGraphFSMMonitorAdc::GetP4I3 () inline
Definition at line 323 of file MonitorAdc.hpp.
References P4I3, P4I3Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by ScanMonitorAdcCommand().
GetP4I3Raw()
void CGraphFSMMonitorAdc::GetP4I3Raw (int32_t & val) inline
Definition at line 340 of file MonitorAdc.hpp.
References P4I3.
Referenced by TestMonitorAdcCommand().
GetP4V3()
double CGraphFSMMonitorAdc::GetP4V3 () inline
Definition at line 321 of file MonitorAdc.hpp.
References P4V3, P4V3Calibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFSMStatusCommand(), BISTCommand(), and ScanMonitorAdcCommand().
GetP4V3Raw()
void CGraphFSMMonitorAdc::GetP4V3Raw (int32_t & val) inline
Definition at line 338 of file MonitorAdc.hpp.
References P4V3.
Referenced by TestMonitorAdcCommand().
GetP5V()
double CGraphFSMMonitorAdc::GetP5V () inline
Definition at line 319 of file MonitorAdc.hpp.
References P5V, P5VCalibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFSMStatusCommand(), BISTCommand(), and ScanMonitorAdcCommand().
GetP5VRaw()
void CGraphFSMMonitorAdc::GetP5VRaw (int32_t & val) inline
Definition at line 336 of file MonitorAdc.hpp.
References P5V.
Referenced by TestMonitorAdcCommand().
GetP6I()
double CGraphFSMMonitorAdc::GetP6I () inline
Definition at line 324 of file MonitorAdc.hpp.
References P6I, P6ICalibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by ScanMonitorAdcCommand().
GetP6IRaw()
void CGraphFSMMonitorAdc::GetP6IRaw (int32_t & val) inline
Definition at line 341 of file MonitorAdc.hpp.
References P6I.
Referenced by TestMonitorAdcCommand().
GetP6V()
double CGraphFSMMonitorAdc::GetP6V () inline
Definition at line 318 of file MonitorAdc.hpp.
References P6V, P6VCalibrate, and MonitorAdcCalibratedInput::ReadCalibrated().
Referenced by BinaryFSMStatusCommand(), BISTCommand(), and ScanMonitorAdcCommand().
GetP6VRaw()
void CGraphFSMMonitorAdc::GetP6VRaw (int32_t & val) inline
Definition at line 335 of file MonitorAdc.hpp.
References P6V.
Referenced by TestMonitorAdcCommand().
GetTemperature()
double CGraphFSMMonitorAdc::GetTemperature () inline
Definition at line 329 of file MonitorAdc.hpp.
References MonitorAdcCalibratedInput::ReadCalibrated(), Temperature, and TemperatureCalibrate.
Referenced by ScanMonitorAdcCommand().
GetTemperatureRaw()
void CGraphFSMMonitorAdc::GetTemperatureRaw (int32_t & val) inline
Definition at line 346 of file MonitorAdc.hpp.
References Temperature.
Referenced by TestMonitorAdcCommand().
Init()
void CGraphFSMMonitorAdc::Init () inline
Definition at line 198 of file MonitorAdc.hpp.
References Adc, AdcFound, ads1258< spipinout >::AddScanChannel(), AmbientLightChannel, Aux0Channel, Aux1Channel, Aux2Channel, ads1258< spipinout >::ClearScanChannels(), ads1258< spipinout >::CommitScanChannels(), formatf(), GpioDirections, ads1258< spipinout >::Init(), ads1258< spipinout >::InitOK, P1V2Channel, P28VChannel, P2I2Channel, P2V2Channel, P2V5Channel, P3V3DChannel, P4I3Channel, P4V3Channel, P5VChannel, P6IChannel, P6VChannel, ads1258< spipinout >::ReadRegister(), ads1258details::register_gpiod, ads1258< spipinout >::StartChannelScan(), StartPinMask, TemperatureChannel, and ads1258< spipinout >::WriteRegister().
Referenced by main().
Process()
void CGraphFSMMonitorAdc::Process () inline
Definition at line 250 of file MonitorAdc.hpp.
References Adc, AdcFound, ads1258details::ads1258numchannels, AmbientLight, AmbientLightChannel, ads1258< spipinout >::AutoScan(), Aux0, Aux0Channel, Aux1, Aux1Channel, Aux2, Aux2Channel, ads1258< spipinout >::CountsToVolts(), formatf(), ads1258< spipinout >::GetLastSample(), ads1258< spipinout >::IsScanChannel(), Monitor, P1V2, P1V2Channel, P28V, P28VChannel, P2I2, P2I2Channel, P2V2, P2V2Channel, P2V5, P2V5Channel, P3V3D, P3V3DChannel, P4I3, P4I3Channel, P4V3, P4V3Channel, P5V, P5VChannel, P6I, P6IChannel, P6V, P6VChannel, ProcessAllUarts(), sample, Temperature, and TemperatureChannel.
Referenced by Process().
RestoreCals()
void CGraphFSMMonitorAdc::RestoreCals (const double * Buffer, size_t & BufferMaxInBufferUsedOut) inline
Definition at line 393 of file MonitorAdc.hpp.
References Buffer, and formatf().
SaveCals()
void CGraphFSMMonitorAdc::SaveCals (double * Buffer, size_t & BufferMaxInBufferUsedOut) inline
Definition at line 348 of file MonitorAdc.hpp.
References Buffer, and formatf().
SetMonitor()
void CGraphFSMMonitorAdc::SetMonitor (bool monitor) inline
Definition at line 196 of file MonitorAdc.hpp.
References Monitor.
Referenced by main().
Member Data Documentation
Adc
ads1258<PinoutMonitorAdc> CGraphFSMMonitorAdc::Adc
Definition at line 171 of file MonitorAdc.hpp.
Referenced by Init(), and Process().
AdcFound
bool CGraphFSMMonitorAdc::AdcFound private
Definition at line 137 of file MonitorAdc.hpp.
Referenced by Init(), and Process().
AmbientLight
int32_t CGraphFSMMonitorAdc::AmbientLight private
Definition at line 158 of file MonitorAdc.hpp.
Referenced by GetAmbientLight(), GetAmbientLightRaw(), and Process().
Aux0
int32_t CGraphFSMMonitorAdc::Aux0 private
Definition at line 155 of file MonitorAdc.hpp.
Referenced by GetAux0(), GetAux0Raw(), and Process().
Aux1
int32_t CGraphFSMMonitorAdc::Aux1 private
Definition at line 156 of file MonitorAdc.hpp.
Referenced by GetAux1(), GetAux1Raw(), and Process().
Aux2
int32_t CGraphFSMMonitorAdc::Aux2 private
Definition at line 157 of file MonitorAdc.hpp.
Referenced by GetAux2(), GetAux2Raw(), and Process().
GpioDirections
const uint8_t CGraphFSMMonitorAdc::GpioDirections = 0x00 static private
Definition at line 141 of file MonitorAdc.hpp.
Referenced by Init().
Monitor
bool CGraphFSMMonitorAdc::Monitor private
Definition at line 138 of file MonitorAdc.hpp.
Referenced by GetMonitor(), Process(), and SetMonitor().
P1V2
int32_t CGraphFSMMonitorAdc::P1V2 private
Definition at line 144 of file MonitorAdc.hpp.
Referenced by GetP1V2(), GetP1V2Raw(), and Process().
P28V
int32_t CGraphFSMMonitorAdc::P28V private
Definition at line 146 of file MonitorAdc.hpp.
Referenced by GetP28V(), GetP28VRaw(), and Process().
P2I2
int32_t CGraphFSMMonitorAdc::P2I2 private
Definition at line 152 of file MonitorAdc.hpp.
Referenced by GetP2I2(), GetP2I2Raw(), and Process().
P2V2
int32_t CGraphFSMMonitorAdc::P2V2 private
Definition at line 145 of file MonitorAdc.hpp.
Referenced by GetP2V2(), GetP2V2Raw(), and Process().
P2V5
int32_t CGraphFSMMonitorAdc::P2V5 private
Definition at line 147 of file MonitorAdc.hpp.
Referenced by GetP2V5(), GetP2V5Raw(), and Process().
P3V3D
int32_t CGraphFSMMonitorAdc::P3V3D private
Definition at line 150 of file MonitorAdc.hpp.
Referenced by GetP3V3D(), GetP3V3DRaw(), and Process().
P4I3
int32_t CGraphFSMMonitorAdc::P4I3 private
Definition at line 153 of file MonitorAdc.hpp.
Referenced by GetP4I3(), GetP4I3Raw(), and Process().
P4V3
int32_t CGraphFSMMonitorAdc::P4V3 private
Definition at line 151 of file MonitorAdc.hpp.
Referenced by GetP4V3(), GetP4V3Raw(), and Process().
P5V
int32_t CGraphFSMMonitorAdc::P5V private
Definition at line 149 of file MonitorAdc.hpp.
Referenced by GetP5V(), GetP5VRaw(), and Process().
P6I
int32_t CGraphFSMMonitorAdc::P6I private
Definition at line 154 of file MonitorAdc.hpp.
Referenced by GetP6I(), GetP6IRaw(), and Process().
P6V
int32_t CGraphFSMMonitorAdc::P6V private
Definition at line 148 of file MonitorAdc.hpp.
Referenced by GetP6V(), GetP6VRaw(), and Process().
StartPinMask
const uint8_t CGraphFSMMonitorAdc::StartPinMask = 0x80 static private
Definition at line 142 of file MonitorAdc.hpp.
Referenced by Init().
Temperature
int32_t CGraphFSMMonitorAdc::Temperature private
Definition at line 159 of file MonitorAdc.hpp.
Referenced by GetTemperature(), GetTemperatureRaw(), and Process().
The documentation for this struct was generated from the following file:
MonitorAdc.hpp