ESC FilterWheel C++ Source: ads1258< spipinout > Struct Template Reference
ads1258< spipinout > Struct Template Reference
#include <ads1258.h>
Classes
struct spi_busmsg
Public Member Functions
ads1258 (const double adcvref)
virtual ~ads1258 ()
double CountsToVolts (const int32_t &Counts) const
int32_t ConvertOnceDiff (uint8_t chanpos, uint8_t channeg)
void ClearScanChannels ()
uint32_t GetScanChannelsMask ()
void SetScanChannelsMask (const uint32_t Mask)
void AddScanChannel (const unsigned int chan)
void SetScanChannels (const uint8_t chan_diff, const uint8_t chan_se_lo, const uint8_t chan_se_hi, const uint8_t chan_internal)
bool IsScanChannel (const unsigned int chan)
unsigned int NumScanChannels ()
void CommitScanChannels ()
bool StartChannelScan ()
bool Scan ()
bool AutoScan ()
void GetLastSample (const uint8_t channel, ads1258details::ads1258sample &sample)
virtual uint8_t Init (uint8_t gpio_output_mask=gpio_output_mask_all_outputs)
__inline__ void WriteRegister (const uint8_t addr, const uint8_t val)
__inline__ ads1258details::ads1258sample ReadLastChannel ()
__inline__ uint8_t ReadRegister (const uint8_t addr)
__inline__ void ReadRegister (const uint8_t addr, uint8_t &val)
__inline__ void SendCommand (ads1258details::ads1258cmdheader cmd)
Public Attributes
const double AdcVRef
Static Public Attributes
static const uint8_t gpio_output_mask_all_outputs = 0x00
static const uint8_t gpio_output_mask_all_inputs = 0xFF
static const bool inputtypedifferential = true
static const bool inputtypesingleended = false
static const uint8_t InitOK = 0x00
Private Member Functions
__inline__ void txb (uint8_t byte)
__inline__ uint8_t rxb ()
Private Attributes
ads1258details::ads1258sample lastsamples [ads1258details::ads1258numchannels]
uint8_t ScanChansDiff
uint8_t ScanChansSELo
uint8_t ScanChansSEHi
uint8_t ScanChansInternal
struct ads1258::spi_busmsg __attribute__
Detailed Description
template<class spipinout>
struct ads1258< spipinout >
Definition at line 281 of file ads1258.h.
Constructor & Destructor Documentation
ads1258()
template<class spipinout > ads1258< spipinout >::ads1258 (const double adcvref) inline explicit
Definition at line 297 of file ads1258.h.
~ads1258()
template<class spipinout > virtual ads1258< spipinout >::~ads1258 () inline virtual
Definition at line 308 of file ads1258.h.
Member Function Documentation
AddScanChannel()
template<class spipinout > void ads1258< spipinout >::AddScanChannel (const unsigned int chan) inline
Definition at line 373 of file ads1258.h.
References ads1258details::ads1258numchannels, ads1258< spipinout >::GetScanChannelsMask(), and ads1258< spipinout >::SetScanChannelsMask().
Referenced by CGraphFSMMonitorAdc::Init().
AutoScan()
template<class spipinout > bool ads1258< spipinout >::AutoScan () inline
Definition at line 485 of file ads1258.h.
References ads1258details::ads1258numchannels, ads1258details::ads1258status::channel, ads1258details::ads1258status::isnew, ads1258< spipinout >::lastsamples, ads1258< spipinout >::ReadLastChannel(), and ads1258details::ads1258sample::status.
Referenced by CGraphFSMMonitorAdc::Process().
ClearScanChannels()
template<class spipinout > void ads1258< spipinout >::ClearScanChannels () inline
Definition at line 345 of file ads1258.h.
References ads1258< spipinout >::ScanChansDiff, ads1258< spipinout >::ScanChansInternal, ads1258< spipinout >::ScanChansSEHi, and ads1258< spipinout >::ScanChansSELo.
Referenced by CGraphFSMMonitorAdc::Init().
CommitScanChannels()
template<class spipinout > void ads1258< spipinout >::CommitScanChannels () inline
Definition at line 415 of file ads1258.h.
References formatf(), ads1258< spipinout >::ReadRegister(), ads1258details::register_muxdif, ads1258details::register_muxsg0, ads1258details::register_muxsg1, ads1258details::register_sysread, ads1258< spipinout >::ScanChansDiff, ads1258< spipinout >::ScanChansInternal, ads1258< spipinout >::ScanChansSEHi, ads1258< spipinout >::ScanChansSELo, and ads1258< spipinout >::WriteRegister().
Referenced by CGraphFSMMonitorAdc::Init().
ConvertOnceDiff()
template<class spipinout > int32_t ads1258< spipinout >::ConvertOnceDiff (uint8_t chanpos, uint8_t channeg) inline
Definition at line 315 of file ads1258.h.
References ads1258details::config0register::all, ads1258details::muxschregister::all, ads1258details::cmdtype_pulseconvert, delayus(), formatf(), ads1258details::config0register::muxmod, ads1258< spipinout >::ReadLastChannel(), ads1258< spipinout >::ReadRegister(), ads1258details::register_config0, ads1258details::register_muxdif, ads1258details::register_muxsch, ads1258< spipinout >::SendCommand(), and ads1258< spipinout >::WriteRegister().
CountsToVolts()
template<class spipinout > double ads1258< spipinout >::CountsToVolts (const int32_t & Counts) const inline
Definition at line 310 of file ads1258.h.
References ads1258< spipinout >::AdcVRef, and ads1258details::CountPosVRef.
Referenced by CGraphFSMMonitorAdc::Process().
GetLastSample()
template<class spipinout > void ads1258< spipinout >::GetLastSample (const uint8_t channel, ads1258details::ads1258sample & sample) inline
Definition at line 498 of file ads1258.h.
References ads1258details::ads1258numchannels, channel, ads1258details::ads1258status::isnew, ads1258< spipinout >::lastsamples, sample, and ads1258details::ads1258sample::status.
Referenced by CGraphFSMMonitorAdc::Process().
GetScanChannelsMask()
template<class spipinout > uint32_t ads1258< spipinout >::GetScanChannelsMask () inline
Definition at line 353 of file ads1258.h.
References ads1258< spipinout >::ScanChansDiff, ads1258< spipinout >::ScanChansInternal, ads1258< spipinout >::ScanChansSEHi, and ads1258< spipinout >::ScanChansSELo.
Referenced by ads1258< spipinout >::AddScanChannel(), ads1258< spipinout >::IsScanChannel(), and ads1258< spipinout >::NumScanChannels().
Init()
template<class spipinout > virtual uint8_t ads1258< spipinout >::Init (uint8_t gpio_output_mask = gpio_output_mask_all_outputs) inline virtual
Definition at line 510 of file ads1258.h.
References ads1258details::config0register::all, ads1258details::config1register::all, ads1258details::sysreadregister::all, ads1258details::cmdtype_reset, delayus(), formatf(), ads1258< spipinout >::InitOK, ads1258< spipinout >::ReadRegister(), ads1258details::register_config0, ads1258details::register_config1, ads1258details::register_gpioc, ads1258details::register_gpiod, ads1258details::register_idnum, ads1258details::register_sysread, ads1258< spipinout >::SendCommand(), and ads1258< spipinout >::WriteRegister().
Referenced by CGraphFSMMonitorAdc::Init().
IsScanChannel()
template<class spipinout > bool ads1258< spipinout >::IsScanChannel (const unsigned int chan) inline
Definition at line 392 of file ads1258.h.
References ads1258details::ads1258numchannels, and ads1258< spipinout >::GetScanChannelsMask().
Referenced by CGraphFSMMonitorAdc::Process().
NumScanChannels()
template<class spipinout > unsigned int ads1258< spipinout >::NumScanChannels () inline
Definition at line 399 of file ads1258.h.
References ads1258details::ads1258numchannels, and ads1258< spipinout >::GetScanChannelsMask().
ReadLastChannel()
template<class spipinout > __inline__ ads1258details::ads1258sample ads1258< spipinout >::ReadLastChannel () inline
Definition at line 636 of file ads1258.h.
References ads1258details::ads1258sample::one, ads1258< spipinout >::rxb(), ads1258details::ads1258sample::three, ads1258details::ads1258sample::two, ads1258< spipinout >::txb(), and ads1258details::ads1258sample::zero.
Referenced by ads1258< spipinout >::AutoScan(), ads1258< spipinout >::ConvertOnceDiff(), and ads1258< spipinout >::Scan().
ReadRegister() [1/2]
template<class spipinout > __inline__ uint8_t ads1258< spipinout >::ReadRegister (const uint8_t addr) inline
Definition at line 637 of file ads1258.h.
References ads1258< spipinout >::rxb(), and ads1258< spipinout >::txb().
Referenced by ads1258< spipinout >::CommitScanChannels(), ads1258< spipinout >::ConvertOnceDiff(), CGraphFSMMonitorAdc::Init(), and ads1258< spipinout >::Init().
ReadRegister() [2/2]
template<class spipinout > __inline__ void ads1258< spipinout >::ReadRegister (const uint8_t addr, uint8_t & val) inline
Definition at line 638 of file ads1258.h.
References ads1258< spipinout >::rxb(), and ads1258< spipinout >::txb().
rxb()
template<class spipinout > __inline__ uint8_t ads1258< spipinout >::rxb () inline private
Definition at line 626 of file ads1258.h.
Referenced by ads1258< spipinout >::ReadLastChannel(), ads1258< spipinout >::ReadRegister(), and ads1258< spipinout >::ReadRegister().
Scan()
template<class spipinout > bool ads1258< spipinout >::Scan () inline
Definition at line 470 of file ads1258.h.
References ads1258details::ads1258numchannels, ads1258details::ads1258status::channel, ads1258details::cmdtype_pulseconvert, ads1258details::ads1258status::isnew, ads1258< spipinout >::lastsamples, ads1258< spipinout >::ReadLastChannel(), ads1258< spipinout >::SendCommand(), and ads1258details::ads1258sample::status.
SendCommand()
template<class spipinout > __inline__ void ads1258< spipinout >::SendCommand (ads1258details::ads1258cmdheader cmd) inline
Definition at line 640 of file ads1258.h.
References ads1258details::ads1258cmdheader::all, and ads1258< spipinout >::txb().
Referenced by ads1258< spipinout >::ConvertOnceDiff(), ads1258< spipinout >::Init(), ads1258< spipinout >::Scan(), and ads1258< spipinout >::StartChannelScan().
SetScanChannels()
template<class spipinout > void ads1258< spipinout >::SetScanChannels (const uint8_t chan_diff, const uint8_t chan_se_lo, const uint8_t chan_se_hi, const uint8_t chan_internal) inline
Definition at line 384 of file ads1258.h.
References ads1258< spipinout >::ScanChansDiff, ads1258< spipinout >::ScanChansInternal, ads1258< spipinout >::ScanChansSEHi, and ads1258< spipinout >::ScanChansSELo.
SetScanChannelsMask()
template<class spipinout > void ads1258< spipinout >::SetScanChannelsMask (const uint32_t Mask) inline
Definition at line 365 of file ads1258.h.
References ads1258< spipinout >::ScanChansDiff, ads1258< spipinout >::ScanChansInternal, ads1258< spipinout >::ScanChansSEHi, and ads1258< spipinout >::ScanChansSELo.
Referenced by ads1258< spipinout >::AddScanChannel().
StartChannelScan()
template<class spipinout > bool ads1258< spipinout >::StartChannelScan () inline
Definition at line 453 of file ads1258.h.
References ads1258details::config0register::all, ads1258details::config0register::bypass, ads1258details::cmdtype_pulseconvert, ads1258details::config0register::muxmod, ads1258details::register_config0, ads1258< spipinout >::SendCommand(), ads1258details::config0register::stat, and ads1258< spipinout >::WriteRegister().
Referenced by CGraphFSMMonitorAdc::Init().
txb()
template<class spipinout > __inline__ void ads1258< spipinout >::txb (uint8_t byte) inline private
Definition at line 625 of file ads1258.h.
Referenced by ads1258< spipinout >::ReadLastChannel(), ads1258< spipinout >::ReadRegister(), ads1258< spipinout >::ReadRegister(), ads1258< spipinout >::SendCommand(), and ads1258< spipinout >::WriteRegister().
WriteRegister()
template<class spipinout > __inline__ void ads1258< spipinout >::WriteRegister (const uint8_t addr, const uint8_t val) inline
Definition at line 633 of file ads1258.h.
References ads1258< spipinout >::txb().
Referenced by ads1258< spipinout >::CommitScanChannels(), ads1258< spipinout >::ConvertOnceDiff(), CGraphFSMMonitorAdc::Init(), ads1258< spipinout >::Init(), and ads1258< spipinout >::StartChannelScan().
Member Data Documentation
__attribute__
template<class spipinout > struct ads1258::spi_busmsg ads1258< spipinout >::__attribute__ private
AdcVRef
template<class spipinout > const double ads1258< spipinout >::AdcVRef
Definition at line 295 of file ads1258.h.
Referenced by ads1258< spipinout >::CountsToVolts().
gpio_output_mask_all_inputs
template<class spipinout > const uint8_t ads1258< spipinout >::gpio_output_mask_all_inputs = 0xFF static
Definition at line 288 of file ads1258.h.
gpio_output_mask_all_outputs
template<class spipinout > const uint8_t ads1258< spipinout >::gpio_output_mask_all_outputs = 0x00 static
Definition at line 287 of file ads1258.h.
InitOK
template<class spipinout > const uint8_t ads1258< spipinout >::InitOK = 0x00 static
Definition at line 293 of file ads1258.h.
Referenced by CGraphFSMMonitorAdc::Init(), and ads1258< spipinout >::Init().
inputtypedifferential
template<class spipinout > const bool ads1258< spipinout >::inputtypedifferential = true static
Definition at line 290 of file ads1258.h.
inputtypesingleended
template<class spipinout > const bool ads1258< spipinout >::inputtypesingleended = false static
Definition at line 291 of file ads1258.h.
lastsamples
template<class spipinout > ads1258details::ads1258sample ads1258< spipinout >::lastsamples[ads1258details::ads1258numchannels] private
Definition at line 610 of file ads1258.h.
Referenced by ads1258< spipinout >::AutoScan(), ads1258< spipinout >::GetLastSample(), and ads1258< spipinout >::Scan().
ScanChansDiff
template<class spipinout > uint8_t ads1258< spipinout >::ScanChansDiff private
Definition at line 612 of file ads1258.h.
Referenced by ads1258< spipinout >::ClearScanChannels(), ads1258< spipinout >::CommitScanChannels(), ads1258< spipinout >::GetScanChannelsMask(), ads1258< spipinout >::SetScanChannels(), and ads1258< spipinout >::SetScanChannelsMask().
ScanChansInternal
template<class spipinout > uint8_t ads1258< spipinout >::ScanChansInternal private
Definition at line 615 of file ads1258.h.
Referenced by ads1258< spipinout >::ClearScanChannels(), ads1258< spipinout >::CommitScanChannels(), ads1258< spipinout >::GetScanChannelsMask(), ads1258< spipinout >::SetScanChannels(), and ads1258< spipinout >::SetScanChannelsMask().
ScanChansSEHi
template<class spipinout > uint8_t ads1258< spipinout >::ScanChansSEHi private
Definition at line 614 of file ads1258.h.
Referenced by ads1258< spipinout >::ClearScanChannels(), ads1258< spipinout >::CommitScanChannels(), ads1258< spipinout >::GetScanChannelsMask(), ads1258< spipinout >::SetScanChannels(), and ads1258< spipinout >::SetScanChannelsMask().
ScanChansSELo
template<class spipinout > uint8_t ads1258< spipinout >::ScanChansSELo private
Definition at line 613 of file ads1258.h.
Referenced by ads1258< spipinout >::ClearScanChannels(), ads1258< spipinout >::CommitScanChannels(), ads1258< spipinout >::GetScanChannelsMask(), ads1258< spipinout >::SetScanChannels(), and ads1258< spipinout >::SetScanChannelsMask().
The documentation for this struct was generated from the following file:
ads1258.h