ESC FilterWheel C++ Source: BinaryUartCallbacks Struct Reference
BinaryUartCallbacks Struct Reference
#include <BinaryUart.hpp>
Public Member Functions
BinaryUartCallbacks ()
virtual ~BinaryUartCallbacks ()
virtual void InvalidPacket (const uint8_t *Buffer, const size_t &BufferLen)
virtual void UnHandledPacket (const IPacket *Packet, const size_t &PacketLen)
virtual void EveryPacket (const IPacket *Packet, const size_t &PacketLen)
virtual void BufferOverflow (const uint8_t *Buffer, const size_t &BufferLen)
BinaryUartCallbacks ()
virtual ~BinaryUartCallbacks ()
virtual void InvalidPacket (const uint8_t *Buffer, const size_t &BufferLen)
virtual void UnHandledPacket (const IPacket *Packet, const size_t &PacketLen)
virtual void EveryPacket (const IPacket *Packet, const size_t &PacketLen)
virtual void BufferOverflow (const uint8_t *Buffer, const size_t &BufferLen)
Detailed Description
Handlers for specific packet events.
Definition at line 35 of file BinaryUart.hpp.
Constructor & Destructor Documentation
BinaryUartCallbacks() [1/2]
BinaryUartCallbacks::BinaryUartCallbacks () inline
Definition at line 37 of file BinaryUart.hpp.
~BinaryUartCallbacks() [1/2]
virtual BinaryUartCallbacks::~BinaryUartCallbacks () inline virtual
Definition at line 38 of file BinaryUart.hpp.
BinaryUartCallbacks() [2/2]
BinaryUartCallbacks::BinaryUartCallbacks () inline
Definition at line 37 of file BinaryUartRingBuffer.hpp.
~BinaryUartCallbacks() [2/2]
virtual BinaryUartCallbacks::~BinaryUartCallbacks () inline virtual
Definition at line 38 of file BinaryUartRingBuffer.hpp.
Member Function Documentation
BufferOverflow() [1/2]
virtual void BinaryUartCallbacks::BufferOverflow (const uint8_t * Buffer, const size_t & BufferLen) inline virtual
Reimplemented in FPGABinaryUartCallbacks, and FPGABinaryUartCallbacks.
Definition at line 50 of file BinaryUart.hpp.
Referenced by BinaryUart::ProcessByte().
BufferOverflow() [2/2]
virtual void BinaryUartCallbacks::BufferOverflow (const uint8_t * Buffer, const size_t & BufferLen) inline virtual
Reimplemented in FPGABinaryUartCallbacks, and FPGABinaryUartCallbacks.
Definition at line 50 of file BinaryUartRingBuffer.hpp.
EveryPacket() [1/2]
virtual void BinaryUartCallbacks::EveryPacket (const IPacket * Packet, const size_t & PacketLen) inline virtual
Definition at line 47 of file BinaryUart.hpp.
Referenced by BinaryUart::CheckPacketEnd(), and BinaryUart::Process().
EveryPacket() [2/2]
virtual void BinaryUartCallbacks::EveryPacket (const IPacket * Packet, const size_t & PacketLen) inline virtual
Definition at line 47 of file BinaryUartRingBuffer.hpp.
InvalidPacket() [1/2]
virtual void BinaryUartCallbacks::InvalidPacket (const uint8_t * Buffer, const size_t & BufferLen) inline virtual
Reimplemented in FPGABinaryUartCallbacks, and FPGABinaryUartCallbacks.
Definition at line 41 of file BinaryUart.hpp.
Referenced by BinaryUart::CheckPacketEnd(), and BinaryUart::Process().
InvalidPacket() [2/2]
virtual void BinaryUartCallbacks::InvalidPacket (const uint8_t * Buffer, const size_t & BufferLen) inline virtual
Reimplemented in FPGABinaryUartCallbacks, and FPGABinaryUartCallbacks.
Definition at line 41 of file BinaryUartRingBuffer.hpp.
UnHandledPacket() [1/2]
virtual void BinaryUartCallbacks::UnHandledPacket (const IPacket * Packet, const size_t & PacketLen) inline virtual
Reimplemented in FPGABinaryUartCallbacks, and FPGABinaryUartCallbacks.
Definition at line 44 of file BinaryUart.hpp.
Referenced by BinaryUart::CheckPacketEnd(), and BinaryUart::Process().
UnHandledPacket() [2/2]
virtual void BinaryUartCallbacks::UnHandledPacket (const IPacket * Packet, const size_t & PacketLen) inline virtual
Reimplemented in FPGABinaryUartCallbacks, and FPGABinaryUartCallbacks.
Definition at line 44 of file BinaryUartRingBuffer.hpp.
The documentation for this struct was generated from the following files:
BinaryUart.hpp
BinaryUartRingBuffer.hpp