ESC FilterWheel C++ Source: Uarts.cpp File Reference
Uarts.cpp File Reference
#include "uart/UartParserTable.hpp"
#include "cgraph/CGraphFSMHardwareInterface.hpp"
#include "format/formatf.h"
#include "uart/BinaryUart.hpp"
#include "uart/uart_pinout_fpga.hpp"
#include "cgraph/CGraphPacket.hpp"
#include "uart/TerminalUart.hpp"
#include "Uarts.hpp"
#include "CmdTableAscii.hpp"
#include "CmdTableBinary.hpp"
Classes
struct FPGABinaryUartCallbacks
Functions
const char * TerminalUartPrompt ()
TerminalUart< 16, 4096 > DbgUart485_0 (FPGAUartPinout0, AsciiCmds, NumAsciiCmds, &TerminalUartPrompt, NoRTS, NoPrefix, false)
void ProcessAllUarts ()
int stdio_hook_putc (int c)
Variables
char prompt [] = "\n\nESC-FSM> "
uart_pinout_fpga FPGAUartPinout0 FSM
uart_pinout_fpga FPGAUartPinout0 &FSM UartFifo0
uart_pinout_fpga FPGAUartPinout0 &FSM &FSM UartFifo0ReadData
uart_pinout_fpga FPGAUartPinout0 &FSM &FSM &FSM uart_pinout_fpga FPGAUartPinout1 &FSM UartFifo1
uart_pinout_fpga FPGAUartPinout0 &FSM &FSM &FSM uart_pinout_fpga FPGAUartPinout1 &FSM &FSM UartFifo1ReadData
uart_pinout_fpga FPGAUartPinout0 &FSM &FSM &FSM uart_pinout_fpga FPGAUartPinout1 &FSM &FSM &FSM uart_pinout_fpga FPGAUartPinout2 &FSM UartFifo2
uart_pinout_fpga FPGAUartPinout0 &FSM &FSM &FSM uart_pinout_fpga FPGAUartPinout1 &FSM &FSM &FSM uart_pinout_fpga FPGAUartPinout2 &FSM &FSM UartFifo2ReadData
uart_pinout_fpga FPGAUartPinout0 &FSM &FSM &FSM uart_pinout_fpga FPGAUartPinout1 &FSM &FSM &FSM uart_pinout_fpga FPGAUartPinout2 &FSM &FSM &FSM uart_pinout_fpga FPGAUartPinout3 &FSM UartFifo3
uart_pinout_fpga FPGAUartPinout0 &FSM &FSM &FSM uart_pinout_fpga FPGAUartPinout1 &FSM &FSM &FSM uart_pinout_fpga FPGAUartPinout2 &FSM &FSM &FSM uart_pinout_fpga FPGAUartPinout3 &FSM &FSM UartFifo3ReadData
FPGABinaryUartCallbacks BinaryPacketCallbacks
CGraphPacket FPGAUartProtocol
BinaryUart FpgaUartParser1 (FPGAUartPinout1, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, BinaryPacketCallbacks, false)
BinaryUart FpgaUartParser2 (FPGAUartPinout2, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, BinaryPacketCallbacks, false)
BinaryUart FpgaUartParser3 (FPGAUartPinout3, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, BinaryPacketCallbacks, false)
IUartParser *const UartParsers []
const uint8_t NumUartParsers = sizeof(UartParsers) / sizeof(UartParsers[0])
BinaryUart *const BinaryUartParsers []
const uint8_t NumBinaryUartParsers = sizeof(BinaryUartParsers) / sizeof(BinaryUartParsers[0])
TerminalUart< 16, 4096 > *const AsciiUartParsers []
const uint8_t NumAsciiUartParsers = sizeof(AsciiUartParsers) / sizeof(AsciiUartParsers[0])
Function Documentation
DbgUart485_0()
TerminalUart< 16, 4096 > DbgUart485_0 (FPGAUartPinout0 , AsciiCmds , NumAsciiCmds , & TerminalUartPrompt, NoRTS , NoPrefix , false)
ProcessAllUarts()
void ProcessAllUarts ()
Definition at line 117 of file Uarts.cpp.
References NumUartParsers, IUartParser::Process(), and UartParsers.
Referenced by CGraphFSMMonitorAdc::Process().
stdio_hook_putc()
int stdio_hook_putc (int c)
Definition at line 129 of file Uarts.cpp.
References FPGAUartPinout0, and uart_pinout_fpga::putcqq().
TerminalUartPrompt()
const char * TerminalUartPrompt ()
Definition at line 30 of file Uarts.cpp.
References prompt.
Variable Documentation
AsciiUartParsers
TerminalUart<16, 4096>* const AsciiUartParsers[]
Initial value:
=
{
    &DbgUart485_0,
}
Definition at line 110 of file Uarts.cpp.
BinaryPacketCallbacks
FPGABinaryUartCallbacks BinaryPacketCallbacks
BinaryUartParsers
BinaryUart* const BinaryUartParsers[]
Initial value:
=
{
    &FpgaUartParser1,
    &FpgaUartParser2,
    &FpgaUartParser3,
}
Definition at line 102 of file Uarts.cpp.
FpgaUartParser1
BinaryUart FpgaUartParser1(FPGAUartPinout1, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, BinaryPacketCallbacks, false) (FPGAUartPinout1 , FPGAUartProtocol , BinaryCmds , NumBinaryCmds , BinaryPacketCallbacks , false)
FpgaUartParser2
BinaryUart FpgaUartParser2(FPGAUartPinout2, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, BinaryPacketCallbacks, false) (FPGAUartPinout2 , FPGAUartProtocol , BinaryCmds , NumBinaryCmds , BinaryPacketCallbacks , false)
FpgaUartParser3
BinaryUart FpgaUartParser3(FPGAUartPinout3, FPGAUartProtocol, BinaryCmds, NumBinaryCmds, BinaryPacketCallbacks, false) (FPGAUartPinout3 , FPGAUartProtocol , BinaryCmds , NumBinaryCmds , BinaryPacketCallbacks , false)
FPGAUartProtocol
CGraphPacket FPGAUartProtocol
Definition at line 80 of file Uarts.cpp.
FSM
uart_pinout_fpga FPGAUartPinout0 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout1 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout2 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout3 FSM
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 35 of file Uarts.cpp.
NumAsciiUartParsers
const uint8_t NumAsciiUartParsers = sizeof(AsciiUartParsers) / sizeof(AsciiUartParsers[0])
Definition at line 115 of file Uarts.cpp.
NumBinaryUartParsers
const uint8_t NumBinaryUartParsers = sizeof(BinaryUartParsers) / sizeof(BinaryUartParsers[0])
Definition at line 108 of file Uarts.cpp.
NumUartParsers
const uint8_t NumUartParsers = sizeof(UartParsers) / sizeof(UartParsers[0])
Definition at line 100 of file Uarts.cpp.
Referenced by ProcessAllUarts().
prompt
char prompt[] = "\n\nESC-FSM> "
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 29 of file Uarts.cpp.
Referenced by TerminalUartPrompt().
UartFifo0
uart_pinout_fpga FPGAUartPinout0 & FSM & FSM & FSM UartFifo0
Definition at line 35 of file Uarts.cpp.
UartFifo0ReadData
uart_pinout_fpga FPGAUartPinout0 & FSM & FSM UartFifo0ReadData
Definition at line 35 of file Uarts.cpp.
UartFifo1
uart_pinout_fpga FPGAUartPinout0 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout1 & FSM & FSM & FSM UartFifo1
Definition at line 36 of file Uarts.cpp.
UartFifo1ReadData
uart_pinout_fpga FPGAUartPinout0 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout1 & FSM & FSM UartFifo1ReadData
Definition at line 36 of file Uarts.cpp.
UartFifo2
uart_pinout_fpga FPGAUartPinout0 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout1 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout2 & FSM & FSM & FSM UartFifo2
Definition at line 37 of file Uarts.cpp.
UartFifo2ReadData
uart_pinout_fpga FPGAUartPinout0 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout1 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout2 & FSM & FSM UartFifo2ReadData
Definition at line 37 of file Uarts.cpp.
UartFifo3
uart_pinout_fpga FPGAUartPinout0 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout1 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout2 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout3 & FSM & FSM & FSM UartFifo3
Definition at line 38 of file Uarts.cpp.
UartFifo3ReadData
uart_pinout_fpga FPGAUartPinout0 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout1 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout2 & FSM & FSM & FSM uart_pinout_fpga FPGAUartPinout3 & FSM & FSM UartFifo3ReadData
Definition at line 38 of file Uarts.cpp.
UartParsers
IUartParser* const UartParsers[]
Initial value:
=
{
    &FpgaUartParser1,
    &FpgaUartParser2,
    &FpgaUartParser3,
    &DbgUart485_0,
}
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 92 of file Uarts.cpp.
Referenced by ProcessAllUarts().