all: 
	scp PZT.service root@192.168.1.223:/etc/systemd/system
	#scp PZT.service torizon@192.168.1.223:/home/torizon/root/etc/systemd/system
	#ssh torizon@192.168.1.223 "sudo cp -r /home/torizon/root/* /"
