ESC FilterWheel C++ Source: CGraphPacket.hpp File Reference
CGraphPacket.hpp File Reference
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include "uart/IPacket.hpp"
#include "uart/Crc32Bzip2.h"
Classes
struct CGraphPacketHeader
struct CGraphPacketFooter
class CGraphPacket
struct CGraphVersionPayload
struct CGraphHardFaultPayload
struct CGraphFSMTelemetryPayload
struct CGraphDMTelemetryPayload
struct CGraphFWTelemetryPayload
Macros
#define _IPacket_H_
Enumerations
enum FWFilterSelectPositions {
FW_MOVING = -1 , FW_SUNSAFE = 0 , FILTERWHEEL_ONE = 1 , FILTERWHEEL_TWO = 2 ,
FILTERWHEEL_THREE = 3 , FILTERWHEEL_FOUR = 4 , FILTERWHEEL_FIVE = 5 , FILTERWHEEL_SIX = 6 ,
FILTERWHEEL_SEVEN = 7 , FILTERWHEEL_EIGHT = 8
}
Functions
struct CGraphPacketHeader __attribute__ ((__packed__))
CGraphPacketHeader ()
CGraphPacketHeader (uint16_t packettype, uint16_t payloadtype, uint16_t payloadlen)
const void * PayloadData () const
void * PayloadDataNonConst ()
void formatf () const
CGraphPacketFooter ()
Variables
static const uint32_t CGraphMagikPacketStartToken = 0x1BADBABEUL
uint32_t PacketStartToken
uint16_t PayloadType
uint16_t PayloadLen
static const uint32_t CGraphMagikPacketEndToken = 0x0A0FADEDUL
uint32_t CRC32BZIP2
uint32_t PacketEndToken
CGraphPacket __attribute__
static const uint16_t CGraphPayloadTypeVersionDeprecated = 0x0001U
static const uint16_t CGraphPayloadTypeVersion = 0x1001U
static const uint16_t CGraphPayloadTypeBaudClock = 0x1002U
static const uint16_t CGraphPayloadTypeBaudDividers = 0x1003U
static const uint16_t CGraphPayloadTypeHardFault = 0x1004U
static const uint16_t CGraphPayloadTypeFSMDacs = 0x2002U
static const uint16_t CGraphPayloadTypeFSMDacsDeprecated = 0x0002U
static const uint16_t CGraphPayloadTypeFSMDacsFloatingPoint = 0x2003U
static const uint16_t CGraphPayloadTypeFSMDacsFloatingPointDeprecated = 0x0003U
static const uint16_t CGraphPayloadTypeFSMAdcs = 0x2004U
static const uint16_t CGraphPayloadTypeFSMAdcsDeprecated = 0x0004U
static const uint16_t CGraphPayloadTypeFSMAdcsFloatingPoint = 0x2005U
static const uint16_t CGraphPayloadTypeFSMAdcsFloatingPointDeprecated = 0x0005U
static const uint16_t CGraphPayloadTypeFSMTelemetry = 0x2006U
static const uint16_t CGraphPayloadTypeFSMStatusDeprecated = 0x0006U
static const uint16_t CGraphPayloadTypeDMDac = 0x3002U
static const uint16_t CGraphPayloadTypeDMTelemetry = 0x3004U
static const uint16_t CGraphPayloadTypeDMHVSwitch = 0x3007U
static const uint16_t CGraphPayloadTypeDMDacConfig = 0x3009U
static const uint16_t CGraphPayloadTypeFWHardwareControlStatus = 0x4001U
static const uint16_t CGraphPayloadTypeFWMotorControlStatus = 0x4002U
static const uint16_t CGraphPayloadTypeFWPositionSenseControlStatus = 0x4003U
static const uint16_t CGraphPayloadTypeFWPositionSteps = 0x4004U
static const uint16_t CGraphPayloadTypeFWTelemetry = 0x4005U
static const uint16_t CGraphPayloadTypeFWFilterSelect = 0x4006U
Macro Definition Documentation
_IPacket_H_
#define _IPacket_H_
University of Arizona Steward Observatory UASAL - UA Space Astrophysics Labratory CAAO - Center for Astronomical Adaptive Optics MagAOX
Definition at line 11 of file CGraphPacket.hpp.
Enumeration Type Documentation
FWFilterSelectPositions
enum FWFilterSelectPositions
Enumerator
FW_MOVING
FW_SUNSAFE
FILTERWHEEL_ONE
FILTERWHEEL_TWO
FILTERWHEEL_THREE
FILTERWHEEL_FOUR
FILTERWHEEL_FIVE
FILTERWHEEL_SIX
FILTERWHEEL_SEVEN
FILTERWHEEL_EIGHT
Definition at line 254 of file CGraphPacket.hpp.
Function Documentation
__attribute__()
struct CGraphPacketHeader __attribute__ ((__packed__))
CGraphPacketFooter()
__attribute__::CGraphPacketFooter ()
Definition at line 3 of file CGraphPacket.hpp.
Referenced by CGraphPacket::IsValid().
CGraphPacketHeader() [1/2]
__attribute__::CGraphPacketHeader ()
Definition at line 4 of file CGraphPacket.hpp.
Referenced by CGraphPacket::IsValid(), and CGraphPacket::MakePacket().
CGraphPacketHeader() [2/2]
__attribute__::CGraphPacketHeader (uint16_t packettype, uint16_t payloadtype, uint16_t payloadlen)
Definition at line 6 of file CGraphPacket.hpp.
formatf()
void __attribute__::formatf () const
Definition at line 12 of file CGraphPacket.hpp.
PayloadData()
const void* __attribute__::PayloadData () const
Definition at line 8 of file CGraphPacket.hpp.
Referenced by BinaryUart::TxBinaryPacket(), and TxBinaryPacket().
PayloadDataNonConst()
void* __attribute__::PayloadDataNonConst ()
Definition at line 10 of file CGraphPacket.hpp.
Variable Documentation
__attribute__
CGraphPacket __attribute__
CGraphMagikPacketEndToken
const uint32_t CGraphMagikPacketEndToken = 0x0A0FADEDUL static
Definition at line 41 of file CGraphPacket.hpp.
Referenced by CGraphPacket::FindPacketEnd(), CGraphPacket::IsValid(), and CGraphPacket::MakePacket().
CGraphMagikPacketStartToken
const uint32_t CGraphMagikPacketStartToken = 0x1BADBABEUL static
Definition at line 21 of file CGraphPacket.hpp.
Referenced by CGraphPacket::FindPacketStart(), and CGraphPacket::IsValid().
CGraphPayloadTypeBaudClock
const uint16_t CGraphPayloadTypeBaudClock = 0x1002U static
Definition at line 148 of file CGraphPacket.hpp.
CGraphPayloadTypeBaudDividers
const uint16_t CGraphPayloadTypeBaudDividers = 0x1003U static
Definition at line 149 of file CGraphPacket.hpp.
CGraphPayloadTypeDMDac
const uint16_t CGraphPayloadTypeDMDac = 0x3002U static
Definition at line 203 of file CGraphPacket.hpp.
CGraphPayloadTypeDMDacConfig
const uint16_t CGraphPayloadTypeDMDacConfig = 0x3009U static
Definition at line 206 of file CGraphPacket.hpp.
CGraphPayloadTypeDMHVSwitch
const uint16_t CGraphPayloadTypeDMHVSwitch = 0x3007U static
Definition at line 205 of file CGraphPacket.hpp.
CGraphPayloadTypeDMTelemetry
const uint16_t CGraphPayloadTypeDMTelemetry = 0x3004U static
Definition at line 204 of file CGraphPacket.hpp.
CGraphPayloadTypeFSMAdcs
const uint16_t CGraphPayloadTypeFSMAdcs = 0x2004U static
Definition at line 177 of file CGraphPacket.hpp.
CGraphPayloadTypeFSMAdcsDeprecated
const uint16_t CGraphPayloadTypeFSMAdcsDeprecated = 0x0004U static
Definition at line 178 of file CGraphPacket.hpp.
CGraphPayloadTypeFSMAdcsFloatingPoint
const uint16_t CGraphPayloadTypeFSMAdcsFloatingPoint = 0x2005U static
Definition at line 179 of file CGraphPacket.hpp.
CGraphPayloadTypeFSMAdcsFloatingPointDeprecated
const uint16_t CGraphPayloadTypeFSMAdcsFloatingPointDeprecated = 0x0005U static
Definition at line 180 of file CGraphPacket.hpp.
CGraphPayloadTypeFSMDacs
const uint16_t CGraphPayloadTypeFSMDacs = 0x2002U static
Definition at line 173 of file CGraphPacket.hpp.
CGraphPayloadTypeFSMDacsDeprecated
const uint16_t CGraphPayloadTypeFSMDacsDeprecated = 0x0002U static
Definition at line 174 of file CGraphPacket.hpp.
CGraphPayloadTypeFSMDacsFloatingPoint
const uint16_t CGraphPayloadTypeFSMDacsFloatingPoint = 0x2003U static
Definition at line 175 of file CGraphPacket.hpp.
CGraphPayloadTypeFSMDacsFloatingPointDeprecated
const uint16_t CGraphPayloadTypeFSMDacsFloatingPointDeprecated = 0x0003U static
Definition at line 176 of file CGraphPacket.hpp.
CGraphPayloadTypeFSMStatusDeprecated
const uint16_t CGraphPayloadTypeFSMStatusDeprecated = 0x0006U static
Definition at line 183 of file CGraphPacket.hpp.
CGraphPayloadTypeFSMTelemetry
const uint16_t CGraphPayloadTypeFSMTelemetry = 0x2006U static
Definition at line 182 of file CGraphPacket.hpp.
CGraphPayloadTypeFWFilterSelect
const uint16_t CGraphPayloadTypeFWFilterSelect = 0x4006U static
Definition at line 255 of file CGraphPacket.hpp.
CGraphPayloadTypeFWHardwareControlStatus
const uint16_t CGraphPayloadTypeFWHardwareControlStatus = 0x4001U static
Definition at line 229 of file CGraphPacket.hpp.
CGraphPayloadTypeFWMotorControlStatus
const uint16_t CGraphPayloadTypeFWMotorControlStatus = 0x4002U static
Definition at line 230 of file CGraphPacket.hpp.
CGraphPayloadTypeFWPositionSenseControlStatus
const uint16_t CGraphPayloadTypeFWPositionSenseControlStatus = 0x4003U static
Definition at line 231 of file CGraphPacket.hpp.
CGraphPayloadTypeFWPositionSteps
const uint16_t CGraphPayloadTypeFWPositionSteps = 0x4004U static
Definition at line 232 of file CGraphPacket.hpp.
CGraphPayloadTypeFWTelemetry
const uint16_t CGraphPayloadTypeFWTelemetry = 0x4005U static
Definition at line 236 of file CGraphPacket.hpp.
CGraphPayloadTypeHardFault
const uint16_t CGraphPayloadTypeHardFault = 0x1004U static
Definition at line 151 of file CGraphPacket.hpp.
CGraphPayloadTypeVersion
const uint16_t CGraphPayloadTypeVersion = 0x1001U static
Definition at line 139 of file CGraphPacket.hpp.
CGraphPayloadTypeVersionDeprecated
const uint16_t CGraphPayloadTypeVersionDeprecated = 0x0001U static
Definition at line 138 of file CGraphPacket.hpp.
CRC32BZIP2
uint32_t CRC32BZIP2
Definition at line 0 of file CGraphPacket.hpp.
Referenced by CGraphPacket::IsValid(), and CGraphPacket::MakePacket().
PacketEndToken
uint32_t PacketEndToken
Definition at line 1 of file CGraphPacket.hpp.
PacketStartToken
uint32_t PacketStartToken
Definition at line 0 of file CGraphPacket.hpp.
PayloadLen
uint16_t PayloadLen
Definition at line 2 of file CGraphPacket.hpp.
Referenced by BinaryUart::TxBinaryPacket(), and TxBinaryPacket().
PayloadType
uint16_t PayloadType
Definition at line 1 of file CGraphPacket.hpp.
Referenced by BinaryUart::TxBinaryPacket().