OCams FSW: ocams_util.h File Reference
ocams_util.h File Reference
Header file for ocams_util.c.
#include "ocams_fsw.h"
Functions
uint08 Read1 (const uint08 *bp)
uint16 Read2 (const uint08 *bp)
uint32 Read4 (const uint08 *bp)
void Write1 (uint08 *bp, uint08 x)
void Write2 (uint08 *bp, uint16 x)
void Write4 (uint08 *bp, uint32 x)
uint16 rfc_1071x (bool ps, uint32 sum, const uint08 *buf, uint16 len)
Detailed Description
Header file for ocams_util.c.
Copyright:
This document contains technical data that is controlled by the International Traffic in Arms Regulations (22 CFR 120-130) and may not be provided, disclosed, or transferred in any manner to any person, whether in the U.S. or abroad, who is not 1) a citizen of the United States, 2) a lawful permanent resident of the United States, or 3) a protected individual as defined by 8 USC 1324b(a)(3), without the written permission of the United States Department of State.
VersionControl
Definition in file ocams_util.h.
Function Documentation
uint08 Read1 (const uint08 * bp)
Function:
Read1()
Description:
Read a uint08 from the specified xdata address.
Return values
uint08
Exceptions
N/A
Parameters
bp byte address of uint08 to be read
Definition at line 38 of file ocams_util.c.
Referenced by readEvalCIPs().
{
   return bp[0]  ;
}
uint16 Read2 (const uint08 * bp)
Function:
Read2()
Description:
Read a uint16 from the specified address.
Return values
uint16
Exceptions
N/A
Parameters
bp byte address of uint16 to be read
Definition at line 59 of file ocams_util.c.
Referenced by clockReadSclk(), readEvalCIPs(), readValidatePkt(), rfc_1071x(), and telemPopPkt().
{
   return ( (uint16)bp[0] << 8 ) |
          ( (uint16)bp[1]      ) ;
}
uint32 Read4 (const uint08 * bp)
Function:
Read4()
Description:
Read a uint32 from the specified address.
Return values
N/A
Exceptions
N/A
Parameters
bp byte address of uint32 to be read
Definition at line 78 of file ocams_util.c.
Referenced by clockReadSclk(), readEvalCIPs(), and readValidatePkt().
{
   //lint -save -e662
   return ( (uint32)bp[0] << 24 ) |
          ( (uint32)bp[1] << 16 ) |
          ( (uint32)bp[2] <<  8 ) |
          ( (uint32)bp[3]       ) ;
   //lint -restore
}
uint16 rfc_1071x (bool ps, uint32 sum, const uint08 * buf, uint16 len)
Function:
rfc_1071x()
Description:
Calculate an RFC-1071 checksum over the specified region. If the result is 0 (zero) then replace it with 0xFFFF. If the parameter 'ps' is TRUE, the checksum is initialized with the parameter 'sum' which is always a precalculated IP pseudo checksum. Else it is initialized to 0.
Return values
N/A
Exceptions
N/A
Parameters
ps true if calculation is to be initialized with 'sum'
sum initialization value if 'ps' is true
buf pointer to buffer over which checksum should be takem
len length of checksummed buffer
Definition at line 171 of file ocams_util.c.
References errIsRaised(), errRaiseErr(), and Read2().
Referenced by execExecOcams(), msgCopyPkt(), pktEmitHK(), pktEmitMsg(), pktEmitNOOP(), pktInitHeader(), and readValidatePkt().
{
   uint16 hi ;
   uint16 n  ;
   if ( !buf ) {
      errRaiseErr( 0, 0, 0 ) ;
      return 0 ;
   }
   if ( len & 1 ) {
      errRaiseErr( 0, 0, 0 ) ;
      return 0;
   }
   if ( errIsRaised() ) {
      return 0 ;
   }
   // 8051 is big-endian
   if ( ps ) {
      sum += len       ;
   }
   for ( n = 0 ; n < len ; n += 2 ) {
      sum += Read2(buf) ;
      buf += 2          ;
   }
   // need to roll over at most once so don't need a loop.
   hi = sum >> 16  ;
   if ( hi ) {
      sum = (sum & 0xFFFFL) + hi  ;
   }
   hi = ~(uint16) sum             ;
   return sum == 0 ? 0xFFFFL : hi ;
}
void Write1 (uint08 * bp, uint08 x)
Function:
Write1()
Description:
Write a uint08 to the specified address
Return values
N/A
Exceptions
N/A
Parameters
bp byte address of uint08 to be written
x uint08 to be written
Definition at line 102 of file ocams_util.c.
Referenced by pktInitHeader().
{
   bp[0] = x     ;
}
void Write2 (uint08 * bp, uint16 x)
Function:
Write2()
Description:
Write a uint16 to the specified address
Return values
N/A
Exceptions
N/A
Parameters
bp byte address of uint16 to be read
x uint16 to be written
Definition at line 122 of file ocams_util.c.
Referenced by msgCopyPkt(), pktEmitHK(), pktEmitMsg(), pktEmitNOOP(), pktInitHeader(), and telemPushPkt().
{
   bp[0] = ( x >> 8 ) & 0xff ;
   bp[1] = ( x      ) & 0xff ;
}
void Write4 (uint08 * bp, uint32 x)
Function:
Write4()
Description:
Write a uint32 to the specified address
Return values
N/A
Exceptions
N/A
Parameters
bp byte address of uint32 to be read
x uint32 to be written
Definition at line 143 of file ocams_util.c.
Referenced by pktInitHeader().
{
   bp[0] = ( x >> 24 ) & 0xff ;
   bp[1] = ( x >> 16 ) & 0xff ;
   bp[2] = ( x >>  8 ) & 0xff ;
   bp[3] = ( x       ) & 0xff ;
}