OCams FSW: ocams_sclk.h File Reference
ocams_sclk.h File Reference
Header file for ocams_sclk.c.
#include "ocams_fsw.h"
Data Structures
struct sclk_t
Typedefs
typedef struct sclk_t sclk_t
Functions
void clockReadSclk (void)
void clockLoadSclk (uint32, uint16)
Variables
sclk_t xdata TheSclk
Detailed Description
Header file for ocams_sclk.c.
Copyright:
This document contains technical data that is controlled by the International Traffic in Arms Regulations (22 CFR 120-130) and may not be provided, disclosed, or transferred in any manner to any person, whether in the U.S. or abroad, who is not 1) a citizen of the United States, 2) a lawful permanent resident of the United States, or 3) a protected individual as defined by 8 USC 1324b(a)(3), without the written permission of the United States Department of State.
VersionControl
Definition in file ocams_sclk.h.
Function Documentation
void clockReadSclk (void)
Function:
clockReadSclk()
Description:
Atomically read the 6-byte SCLK into the global variable TheSclk. The SCLK maintains the OCAMS instrument time and is periodically synchronizes with the S/C time. This routine is only called from the main thread, never from the interrupt handler.
Return values
N/A
Exceptions
N/A
Definition at line 45 of file ocams_sclk.c.
References Read2(), and Read4().
Referenced by msgAppendMsg(), msgCopyPkt(), msgIsReady(), msgSetTime(), and pktEmitHK().
{
   TheSclk.raw[0] = sfr_read(SCLK_T0)  ;
   TheSclk.raw[1] = sfr_read(SCLK_T1)  ;
   TheSclk.raw[2] = sfr_read(SCLK_T2)  ;
   TheSclk.raw[3] = sfr_read(SCLK_T3)  ;
   TheSclk.raw[4] = sfr_read(SCLK_T4)  ;
   TheSclk.raw[5] = sfr_read(SCLK_T5)  ;
   TheSclk.secs   = Read4( TheSclk.raw   ) ;
   TheSclk.tics   = Read2( TheSclk.raw+4 ) ;
}