OCams FSW: ocams_packet.c File Reference
ocams_packet.c File Reference
This file contains code to create engineering telemetry packets.
#include "ocams_packet.h"
#include "ocams_header.h"
#include "ocams_util.h"
#include "ocams_err.h"
#include "ocams_sclk.h"
#include "ocams_msg.h"
#include "ocams_telem.h"
Data Structures
struct TelemPacket
Functions
STATIC void pktInitHeader (uint08 cip_type, uint16 cip_len)
void pktEmitNOOP (void)
void pktEmitHK (void)
void pktEmitMsg (void)
Variables
STATIC xdata struct TelemPacket tlmPkt
Detailed Description
This file contains code to create engineering telemetry packets.
Copyright:
This document contains technical data that is controlled by the International Traffic in Arms Regulations (22 CFR 120-130) and may not be provided, disclosed, or transferred in any manner to any person, whether in the U.S. or abroad, who is not 1) a citizen of the United States, 2) a lawful permanent resident of the United States, or 3) a protected individual as defined by 8 USC 1324b(a)(3), without the written permission of the United States Department of State.
VersionControl
Definition in file ocams_packet.c.
Function Documentation
void pktEmitHK (void)
Function:
pktEmitHK
Description:
This routine creates an OCAMS HK packet and queues it for transmission to the S/C.
Return values
N/A
Exceptions
N/A
Definition at line 160 of file ocams_packet.c.
References clockReadSclk(), errIsRaised(), pktInitHeader(), rfc_1071x(), telemPushPkt(), and Write2().
Referenced by loopExecLoopContents().
{
   uint16   csum ;
   uint08  *base ;
   hk_pkt  *hp   ;
   pktInitHeader( CIP_ENGINEERING, HK_PKT_LEN ) ;
   if ( errIsRaised() ) {
      return ;
   }
   base = tlmPkt.buf + CIP_DATA_OFFSET ;
   hp   = (hk_pkt*) base            ;
   clockReadSclk() ;
   hp->hk_type   = HK_PKT_ID        ;
   hp->sclk_secs = TheSclk.secs     ;
   hp->sclk_tics = TheSclk.tics     ;
   hp->len       = sizeof(hk_pkt)   ;
   // clear the UDP check-sum
   Write2( tlmPkt.buf + UDP_CSUM_OFFSET, 0   )  ;
   csum = rfc_1071x( TRUE, PseudoSum, tlmPkt.buf + UDP_OFFSET, tlmPkt.udp_len ) ;
   if( errIsRaised() ) {
      return ;
   }
   Write2( tlmPkt.buf + UDP_CSUM_OFFSET, csum ) ;
   telemPushPkt( tlmPkt.buf, tlmPkt.ip_len )    ;
}
void pktEmitMsg (void)
Function:
pktEmitMsg()
Description:
This routine creates a message packet and queues it for transmission to the S/C. The contents of the packet are copied from the message packet staging area where messages have been accumulating to this point in time.
Return values
N/A
Exceptions
N/A
Definition at line 208 of file ocams_packet.c.
References errIsRaised(), msgCopyPkt(), msgGetSize(), pktInitHeader(), rfc_1071x(), telemPushPkt(), and Write2().
Referenced by loopExecLoopContents().
{
   uint16  csum    ;
   uint08 *base    ;
   uint16  msg_len ;
   msg_len = msgGetSize() ;
   pktInitHeader( CIP_ENGINEERING, msg_len ) ;
   if ( errIsRaised() ) {
      return ;
   }
   base = tlmPkt.buf + CIP_DATA_OFFSET ;
   msgCopyPkt( base, msg_len  )   ;
   if ( errIsRaised() ) {
      return ;
   }
   // clear the UDP check-sum
   Write2( tlmPkt.buf + UDP_CSUM_OFFSET, 0   )  ;
   csum = rfc_1071x( TRUE, PseudoSum, tlmPkt.buf + UDP_OFFSET, tlmPkt.udp_len ) ;
   if( errIsRaised() ) {
      return ;
   }
   Write2( tlmPkt.buf + UDP_CSUM_OFFSET, csum ) ;
   telemPushPkt( tlmPkt.buf, tlmPkt.ip_len )    ;
}
void pktEmitNOOP (void)
Function:
pktEmitNOOP()
Description:
Create a packet containing a NOOP CIP, type 0x00, and then queue for transmission to the S/C. This is the simplist packet that can be created.
Return values
N/A
Exceptions
N/A
Definition at line 125 of file ocams_packet.c.
References errIsRaised(), pktInitHeader(), rfc_1071x(), telemPushPkt(), and Write2().
Referenced by loopExecLoopContents().
{
   uint16 csum  ;
   pktInitHeader( CIP_NOOP, NOP_DATA_LEN ) ;
   if ( errIsRaised() ) {
      return ;
   }
   // clear the check-sum
   Write2( tlmPkt.buf + UDP_CSUM_OFFSET, 0   )  ;
   csum = rfc_1071x( TRUE, PseudoSum, tlmPkt.buf + UDP_OFFSET, tlmPkt.udp_len ) ;
   if( errIsRaised() ) {
      return ;
   }
   Write2( tlmPkt.buf + UDP_CSUM_OFFSET, csum ) ;
   telemPushPkt( tlmPkt.buf, tlmPkt.ip_len )       ;
}
STATIC void pktInitHeader (uint08 cip_type, uint16 cip_len)
Function:
pktInitHeader()
Description:
Single CIP packets are constructed in a staging area prior to being queued for transmission to the S/C. This routine generates the packet header, filling in everything except the UDP checksum.
Return values
N/A
Exceptions
N/A
Parameters
cip_type CIP type to be carried by the packet
Definition at line 62 of file ocams_packet.c.
References errIsRaised(), errRaiseErr(), rfc_1071x(), Write1(), Write2(), and Write4().
Referenced by pktEmitHK(), pktEmitMsg(), and pktEmitNOOP().
{
   uint08 k       ;
   uint16 csum    ;
   uint16 ip_len  ;
   uint16 udp_len ;
   cip_len += CIP_HEADER_LEN            ;
   udp_len  = UDP_HEADER_LEN + cip_len  ;
   ip_len   = IP_HEADER_LEN  + udp_len  ;
   if ( ip_len > MAX_PACKET_LEN ) {
      errRaiseErr( 0, 0, 0 ) ;
      return ;
   }
   tlmPkt.cip_len = cip_len ;
   tlmPkt.udp_len = udp_len ;
   tlmPkt.ip_len  = ip_len  ;
   // inet header
   for ( k = 0 ; k < INET_HEADER_LEN ; k++ ) {
      tlmPkt.buf[k] = net_dat[k].out ;
   }
   // cip header
   Write4( tlmPkt.buf+CIP_OFFSET,      cip_sync )   ;
   Write2( tlmPkt.buf+CIP_SIZE_OFFSET, cip_len  )   ;
   Write1( tlmPkt.buf+CIP_TYPE_OFFSET, cip_type )   ;
   Write1( tlmPkt.buf+CIP_PAD_OFFSET,  0x00     )   ;
   // fill in IP and UPD sizes
   Write2( tlmPkt.buf+IP_SIZE_OFFSET, ip_len    )   ;
   Write2( tlmPkt.buf+UDP_SIZE_OFFSET, udp_len  )   ;
   // ip check-sum over header only
   Write2( tlmPkt.buf + IP_CSUM_OFFSET, 0 )                 ;   // clear the check-sum
   csum = rfc_1071x( FALSE, 0L, tlmPkt.buf, IP_HEADER_LEN ) ;   // no pseudo-sum
   if( errIsRaised() ) {
      return ;
   }
   Write2( tlmPkt.buf + IP_CSUM_OFFSET, csum )              ;
}