OCams FSW: ocams_main.c File Reference
ocams_main.c File Reference
The entry point for the FSW.
#include "ocams_fsw.h"
#include "ocams_loop.h"
#include "ocams_err.h"
#include "ocams_read.h"
#include "ocams_telem.h"
#include "ocams_msg.h"
Functions
void main (void)
Detailed Description
The entry point for the FSW.
Copyright:
This document contains technical data that is controlled by the International Traffic in Arms Regulations (22 CFR 120-130) and may not be provided, disclosed, or transferred in any manner to any person, whether in the U.S. or abroad, who is not 1) a citizen of the United States, 2) a lawful permanent resident of the United States, or 3) a protected individual as defined by 8 USC 1324b(a)(3), without the written permission of the United States Department of State.
VersionControl
Definition in file ocams_main.c.
Function Documentation
void main (void)
Function:
main()
Description:
Sole entry point to the FSW. This function never returns.
Return values
N/A
Exceptions
N/A
Definition at line 55 of file ocams_main.c.
References errInitErr(), loopExecLoop(), loopInitLoop(), msgInitMsg(), readInitRead(), and telemInitTelem().
{
   // Disable all interrupts
    reg_write(EA, 0) ;  // global   enable/disable
    reg_write(EX0, 0) ; // specific enable/disable
    reg_write(EX1, 0) ;
    reg_write(IE0, 0) ; // clear pending interrupts
    reg_write(IE1, 0) ;
   loopInitLoop()   ;   // init main loop
   errInitErr()     ;   // init error handler
   readInitRead()   ;   // init command read/parse
   telemInitTelem() ;   // init telemetry handler
   msgInitMsg()     ;   // init message handler
   RED_TAG( remember to enable interrupts in main.c when handler is coded )
#if 0
    reg_write(EX0, 1)          ;
    reg_write(EX1, 1)          ;
    reg_write(EA, 1)          ;
#endif
   // there is no return from this call
   loopExecLoop()   ;
}