OCams FSW: ocams_msg.c File Reference
ocams_msg.c File Reference
This file contains code to create messages and message packets.
#include "ocams_msg.h"
#include "ocams_sclk.h"
#include "ocams_err.h"
#include "ocams_util.h"
#include "ocams_packet.h"
Functions
STATIC void msgSetTime (msg_t *mp)
uint16 msgGetSize (void)
bool msgIsReady (void)
void msgCopyPkt (uint08 *buf, uint16 b_len)
void msgAppendMsg (uint16 id, uint16 dat0, uint16 dat1, uint16 dat2)
void msgInitMsg (void)
Variables
STATIC msg_t xdata msg_buf [MAX_MSG_CNT]
STATIC uint16 xdata msg_cnt
STATIC uint32 xdata start_secs
STATIC uint16 xdata start_tics
Detailed Description
This file contains code to create messages and message packets.
Copyright:
This document contains technical data that is controlled by the International Traffic in Arms Regulations (22 CFR 120-130) and may not be provided, disclosed, or transferred in any manner to any person, whether in the U.S. or abroad, who is not 1) a citizen of the United States, 2) a lawful permanent resident of the United States, or 3) a protected individual as defined by 8 USC 1324b(a)(3), without the written permission of the United States Department of State.
VersionControl
Definition in file ocams_msg.c.
Function Documentation
void msgAppendMsg (uint16 id, uint16 dat0, uint16 dat1, uint16 dat2)
Function:
msgAppendMsg()
Description:
Append a new message to the message packet being formed in the message packet staging area.
Return values
N/A
Exceptions
N/A
Parameters
id message ID
dat0 1st 16-bits of message data
dat1 2nd 16-bits of message data
dat2 3rd 16-bits of message data
Definition at line 197 of file ocams_msg.c.
References clockReadSclk(), errRaiseErr(), and msgSetTime().
Referenced by execExecOcams().
{
   msg_t *mp  ;
   if ( msg_cnt >= MAX_MSG_CNT ) {
      errRaiseErr( 0, 0, 0 ) ;
      return ;
   }
   // log the packet creation time
   if ( msg_cnt == 0 ) {
      clockReadSclk() ;
      start_secs = TheSclk.secs ;
      start_tics = TheSclk.tics ;
   }
   mp = msg_buf+ msg_cnt ;
   mp->id = id           ;
   mp->dat[0] = dat0     ;
   mp->dat[1] = dat1     ;
   mp->dat[2] = dat2     ;
   msgSetTime( mp )      ;
   msg_cnt++             ;
}
void msgCopyPkt (uint08 * buf, uint16 b_len)
Function:
msgCopyPkt()
Description:
Copy a message packet from its staging area into the general enginerring telemetry staging area where headers will be added prior to its being queued for transmission to the S/C
Return values
N/A
Exceptions
N/A
Parameters
buf buffer into which message packet should be copied
b_len buffer length in bytes
Definition at line 126 of file ocams_msg.c.
References clockReadSclk(), errRaiseErr(), msgGetSize(), rfc_1071x(), and Write2().
Referenced by pktEmitMsg().
{
   msg_pkt_t *mp   ;
   uint16     n    ;
   uint08    *src  ;
   uint08    *dst  ;
   uint16     len  ;
   uint16     csum ;
   if ( buf == NULL ) {
      errRaiseErr( 0, 0, 0 ) ;
      return ;
   }
   if ( b_len < msgGetSize() ) {
      errRaiseErr( 0, 0, 0 ) ;
      return ;
   }
   //lint -save -e826
   // previous guard shows buf is large enough
   mp = (msg_pkt_t*) buf ;
   //lint -restore
   // look after the corner case where the start time
   // was not logged because there were no messages
   if ( msg_cnt == 0 ) {
      clockReadSclk()           ;
      start_secs = TheSclk.secs ;
      start_tics = TheSclk.tics ;
   }
   mp->id      = MSG_PKT_ID   ;
   mp->secs    = start_secs   ;
   mp->tics    = start_tics   ;
   mp->msg_cnt = msg_cnt      ;
   if ( msg_cnt > 0 ) {
      src  = (uint08*)msg_buf        ;  // source      message array
      dst  = (uint08*)mp->msg        ;  // destination message array
      len  = sizeof(msg_t) * msg_cnt ;  // size of the source array
      for ( n = 0 ; n < len ; n++ ) {
         dst[n] = src[n] ;
      }
   }
   len  = msgGetSize() - sizeof(uint16)    ;  // checksum is last two bytes of packet
   csum = rfc_1071x( FALSE, 0L, buf, len ) ;  // can raise an error, trapped by caller
   Write2( buf + len, csum )               ;
   msg_cnt    = 0 ;
   start_secs = 0 ;
   start_tics = 0 ;
}
uint16 msgGetSize (void)
Function:
msgGetSize()
Description:
Return the size of the message packet currently being staged, in bytes.
Return values
size of staged message packet in bytes
Exceptions
N/A
Definition at line 77 of file ocams_msg.c.
Referenced by msgCopyPkt(), and pktEmitMsg().
{
   return ( sizeof(msg_pkt_t) + msg_cnt * sizeof(msg_t) ) - sizeof(msg_t) ;
}
void msgInitMsg (void)
Function:
msgInitMsg()
Description:
This must be called once, and prior to any message packet creation, to initialize message packet state variables.
Return values
N/A
Exceptions
N/A
Definition at line 241 of file ocams_msg.c.
Referenced by main().
{
   msg_cnt    = 0 ;
   start_secs = 0 ;
   start_tics = 0 ;
}
bool msgIsReady (void)
Function:
msgIsRead()
Description:
Return TRUE if and only if a message packet in the staging area should be queued for emission to the S/C. This will occur if the message packet contains more than XXX messages or if more than XXX seconds have elapsed since packet creation.
Return values
TRUE if a message packet is ready for transmission to the S/C FALSE if a message packet is not ready for transmission to the S/C
Exceptions
N/A
Definition at line 99 of file ocams_msg.c.
References clockReadSclk().
Referenced by loopExecLoopContents().
{
   int32 elapsed   ;
   clockReadSclk() ;
   elapsed = (int32)TheSclk.secs - (int32)start_secs ;
   return ( msg_cnt >= MSG_EMIT_CNT ) ? TRUE  :
          ( msg_cnt == 0            ) ? FALSE :
          ( elapsed >= MSG_TIMEOUT  ) ? TRUE  : FALSE ;
}
STATIC void msgSetTime (msg_t * mp)
Function:
msgSetTime()
Description:
Generate message time stamp from the SCLK. The time stamp rolls over after approximately 65 sec but this is not a problem since the message has a timeout less than this.
Return values
N/A
Exceptions
N/A
Parameters
mp message whose time is to be set
Definition at line 49 of file ocams_msg.c.
References clockReadSclk(), and errRaiseErr().
Referenced by msgAppendMsg().
{
   if ( mp == NULL ) {
      errRaiseErr( 0, 0, 0 ) ;
      return ;
   }
   clockReadSclk() ;
   RED_TAG( "8051 bit fields may be inefficient, hand code" )
   mp->time.secs = TheSclk.raw[3]      & 0x3f  ;   // bits 0:5   of SCLK.secs
   mp->time.tics = (TheSclk.tics >> 4) & 0x3ff ;   // bits 4:13  of SCLK.tics
}