OCams FSW: ocams_exec.c File Reference
ocams_exec.c File Reference
Dispatch a command based on its op-code.
#include "ocams_exec.h"
#include "ocams_err.h"
#include "ocams_util.h"
#include "ocams_msg.h"
Functions
STATIC void execResetFPGA (void)
void execExecOcams (uint08 *buf, uint16 buf_len)
Detailed Description
Dispatch a command based on its op-code.
Copyright:
This document contains technical data that is controlled by the International Traffic in Arms Regulations (22 CFR 120-130) and may not be provided, disclosed, or transferred in any manner to any person, whether in the U.S. or abroad, who is not 1) a citizen of the United States, 2) a lawful permanent resident of the United States, or 3) a protected individual as defined by 8 USC 1324b(a)(3), without the written permission of the United States Department of State.
VersionControl
Definition in file ocams_exec.c.
Function Documentation
void execExecOcams (uint08 * buf, uint16 buf_len)
Function:
execExecOcams()
Description:
This function is passed a command from read.h in the form of a byte array or buffer. Afer some checks the array is cast to type 'ocams_cmd' and its contents are validated. The op-code is then used to dispatch a handler via a switch() construct.
Return values
N/A
Exceptions
N/A
Parameters
buf buffer in which command is held
buf_len buffer length in bytes
Definition at line 64 of file ocams_exec.c.
References errIsRaised(), errRaiseErr(), execResetFPGA(), msgAppendMsg(), and rfc_1071x().
Referenced by readEvalCIPs().
{
   uint16     csum ;
   uint16     len  ;
   uint16     argc ;
   ocams_cmd *cp   ;
   if ( buf_len < sizeof(ocams_cmd) || (buf_len & 1) ) {
      errRaiseErr( 0, 0, 0 )  ;
      return ;
   }
   //lint -save -e826
   // above guard verified that buf_len >= sizeof(ocams_cmd)
   cp  = (ocams_cmd*)buf     ;
   //lint -restore
   len = cp->len             ;
   if ( len > buf_len ) {
      errRaiseErr( 0, 0, 0 ) ;
      return ;
   }
   if ( len < sizeof( ocams_cmd ) || (len & 1) ) {
      errRaiseErr( 0, 0, 0 ) ;
      return                 ;
   }
   csum = rfc_1071x( 0, 0L, buf, len )  ;
   if( errIsRaised() ) {
      return ;
   }
   if ( csum != 0xFFFFL ) {
      errRaiseErr( 0, 0, 0 ) ;
      return                 ;
   }
   // reduce len by the size of a packet having no data to find
   // the arg vector size in bytes and then divide by 2 to
   // find the number of 16-bits arguments
   len  = len - sizeof(ocams_cmd) ;
   argc = len >> 1                ;
   switch ( cp->op_code ) {
      // motors, filter wheels and LEDs
      // heater config and control
      // sensor related
      // camera related
      // system commands
      case SYS_RESET_FPGA :
         if ( argc != 0 ) {
            errRaiseErr( 0, 0, 0 ) ;
         }
         else {
            execResetFPGA()  ;
         }
         break ;
      default:
         errRaiseErr( 0, 0, 0 ) ;
   }
   if ( !errIsRaised() ) {
      msgAppendMsg( MSG_CMD_RECEIVED, cp->op_code, cp->id, 0 ) ;
   }
}
STATIC void execResetFPGA (void)
Function:
execResetFPGA()
Description:
Cause an immediate context switch to the boot code running in PROM.
Return values
N/A
Exceptions
N/A
Definition at line 42 of file ocams_exec.c.
Referenced by execExecOcams().
{
   sfr_write(BootCodeSel, 0) ;
}