OCams FSW: ocams_read.c File Reference
ocams_read.c File Reference
This file contains code to read and parse S/C transactions.
#include "ocams_err.h"
#include "ocams_read.h"
#include "ocams_header.h"
#include "ocams_util.h"
#include "ocams_loop.h"
#include "ocams_exec.h"
#include "ocams_fpga.h"
Functions
bool readFifoIsEmpty (void)
bool readFifoNotEmpty (void)
STATIC uint08 readReadChar (void)
void readDrainFIFO (void)
STATIC void readEvalCIPs (void)
STATIC void readValidatePkt (void)
void readScanPkt (void)
void readInitRead (void)
Variables
STATIC cmd_pkt xdata cmdPkt
Detailed Description
This file contains code to read and parse S/C transactions.
Copyright:
This document contains technical data that is controlled by the International Traffic in Arms Regulations (22 CFR 120-130) and may not be provided, disclosed, or transferred in any manner to any person, whether in the U.S. or abroad, who is not 1) a citizen of the United States, 2) a lawful permanent resident of the United States, or 3) a protected individual as defined by 8 USC 1324b(a)(3), without the written permission of the United States Department of State.
VersionControl
Definition in file ocams_read.c.
Function Documentation
void readDrainFIFO (void)
Function:
readDrainFIFO()
Description:
Copy the contents of the FPGA command FIFO into the command parsing buffer. The process continues until the FIFO has been drained or until the command buffer is full.
Return values
N/A
Exceptions
N/A
Definition at line 110 of file ocams_read.c.
References errRaiseErr(), readFifoIsEmpty(), and readReadChar().
Referenced by loopExecLoopContents().
{
   uint16 k ;
   if ( cmdPkt.pkt_len >= COMMAND_BUF_LEN ) {
      errRaiseErr( 0, 0, 0 ) ;
      return ;
   }
   for ( k = cmdPkt.pkt_len ; k < COMMAND_BUF_LEN ; k++ ) {
      if ( readFifoIsEmpty() ) {
         break ;
      }
      cmdPkt.buf[k] = readReadChar() ;
   }
   cmdPkt.pkt_len = k ;
}
STATIC void readEvalCIPs (void)
Function:
readEvalCIPs()
Description:
This routine is called after the command transaction from the S/C has been shown to have a valid header. It locates the messages, CIPs, within the transaction and evaluates each in turn.
Return values
N/A
Exceptions
N/A
Definition at line 144 of file ocams_read.c.
References errRaiseErr(), execExecOcams(), Read1(), Read2(), and Read4().
Referenced by readValidatePkt().
{
   uint16   soc        ;
   uint08   cip_cnt    ;
   uint16   cip_len    ;
   uint16   cip_type   ;
   uint16   data_start ;
   uint16   data_len   ;
   // offset tor first CIP in packet from start of buffer
   soc = cmdPkt.soc ;
   for ( cip_cnt = 0 ; cip_cnt < MAX_CIP_COUNT ; cip_cnt++ ) {
      // Normal return for valid packet
      if ( soc == cmdPkt.eop ) {
         return ;
      }
      // not enough data for cip header
      if ( soc + CIP_HEADER_LEN > cmdPkt.eop ) {
         errRaiseErr( 0, 0, 0 ) ;
         return ;
      }
      // invalid sync
      if ( Read4( cmdPkt.buf+soc ) != cip_sync ) {
         errRaiseErr( 0, 0, 0 ) ;
         return ;
      }
      //    cip_len  = Read2( cmdPkt.buf+soc+CIP_SIZE_OFFSET ) ;
      //    cip_type = Read1( cmdPkt.buf+soc+CIP_TYPE_OFFSET ) ;
      cip_len  = Read2( cmdPkt.buf+soc+4 ) ;
      cip_type = Read1( cmdPkt.buf+soc+6 ) ;
      // missing data
      if ( soc + cip_len > cmdPkt.eop ) {
         errRaiseErr( 0, 0, 0 ) ;
         return ;
      }
      // Other CIP types are not S/C -> Payload or are undefined.
      // If processing a CIP raises an error then log it and
      // move on to the next CIP
      data_start = soc     + CIP_HEADER_LEN  ;
      data_len   = cip_len - CIP_HEADER_LEN  ;
      switch ( cip_type ) {
      case CIP_TIME_UPDATE:  // time update
         State.cmd_received++ ;
         //          exec_sclk_update( data_len, cmdPkt.buf + data_start ) ;
         break  ;
      case CIP_INST_CMD   :  // instrument command
         State.cmd_received++ ;
         execExecOcams( cmdPkt.buf + data_start, data_len ) ;
         break  ;
      case CIP_NOOP       :  // NOP
         State.cmd_received++ ;
         break  ;
      default:
         // invalid CIP type
         errRaiseErr( 0, 0, 0 ) ;
         break  ;
      }
      // advance to the next CIP
      soc = soc + cip_len ;
   }
   // too many CIPS in command packet
   errRaiseErr( 0, 0, 0 ) ;
}
bool readFifoIsEmpty (void)
Function:
readFifoIsEmpty()
Description:
Return TRUE if the FPGA Command FIFO is not empty.
Return values
TRUE FPGA command FIFO is empty FALSE FPGA command FIFO is not empty
Exceptions
N/A
Definition at line 49 of file ocams_read.c.
Referenced by readDrainFIFO().
{
   return CMD_FIFO_EMPTY ? TRUE : FALSE ;
}
bool readFifoNotEmpty (void)
Function:
readFifoNotEmpty()
Description:
Return TRUE if the FPGA Command FIFO is not empty.
Return values
TRUE FPGA command FIFO not empty FALSE FPGA command FIFO is empty
Exceptions
N/A
Definition at line 68 of file ocams_read.c.
Referenced by loopExecLoopContents().
{
   return CMD_FIFO_EMPTY ? FALSE : TRUE ;
}
void readInitRead (void)
Function:
readInitRead()
Description:
One time call to initialize the command transaction parser to a known state. This must be called prior to parsing any transaction.
Return values
N/A
Exceptions
N/A
Definition at line 383 of file ocams_read.c.
Referenced by main().
{
   cmdPkt.pkt_len  = 0  ;
   cmdPkt.ip_len   = 0  ;
   cmdPkt.udp_len  = 0  ;
   cmdPkt.ip_sum   = 0  ;
   cmdPkt.udp_sum  = 0  ;
   cmdPkt.org      = 0  ;
}
STATIC uint08 readReadChar (void)
Function:
readReadChar()
Description:
Read the next uint8 from the FPGA command FIFO.
Return values
uint8 next char in command FIFO
Exceptions
N/A
Definition at line 85 of file ocams_read.c.
Referenced by readDrainFIFO().
{
   // temporary to get around FPGA memory timing problem
   // that pitted EEPROM against the FIFOs
   volatile uint08 xdata xx ;
   xx = sfr_read(ScCmdFifo)           ;
   return xx                ;
}
void readScanPkt (void)
Function:
readScanPkt()
Description:
This is a wrapper for readValidatePkt(). It guarantees that the command parser is reset to a known state even if readValidatePkt() should fail.
Return values
N/A
Exceptions
N/A
Definition at line 354 of file ocams_read.c.
References readValidatePkt().
Referenced by loopExecLoopContents().
{
   readValidatePkt() ;
   // these data are stale so set to default state
   // maybe just call readReadInit() instead
   cmdPkt.ip_len  = 0  ;
   cmdPkt.udp_len = 0  ;
   cmdPkt.ip_sum  = 0  ;
   cmdPkt.udp_sum = 0  ;
   cmdPkt.org     = 0  ;
   cmdPkt.pkt_len = 0  ;
   // add command here to flush the FIFO
}
STATIC void readValidatePkt (void)
Function:
readValidatePkt()
Description:
Parse the packet in the command buffer and validate its header. If the packet has a valid header, call readEvalCIPs() to to evaluate all the messages in the transaction.
Return values
N/A
Exceptions
N/A
Definition at line 228 of file ocams_read.c.
References errIsRaised(), errRaiseErr(), Read2(), Read4(), readEvalCIPs(), and rfc_1071x().
Referenced by readScanPkt().
{
   uint16 n   ;
   uint16 max ;
   uint16 org ;
   if ( cmdPkt.pkt_len < MIN_CMD_PKT_LEN ) {
      errRaiseErr( 0, 0, 0 ) ;
      return   ;
   }
   org = 0    ;
   max = cmdPkt.pkt_len - sizeof(cip_sync) ;
   // look for the first CIP SYNC
   for ( n = INET_HEADER_LEN ; n < max ; n++ ) {
      if ( cip_sync == Read4(cmdPkt.buf+n) ) {
         break ;
      }
      org++   ;
   }
   // bummer, no sync found
   if ( n == max ) {
      errRaiseErr( 0, 0, 0 )   ;
      return  ;
   }
   cmdPkt.soc = n   ;
   cmdPkt.org = org ;
   // check fixed part of header against template
   for ( n = 0 ; n < INET_HEADER_LEN ; n++ ) {
      if ( net_dat[n].match && net_dat[n].in != (cmdPkt.buf+org+n)[0] ) {
         errRaiseErr( 0, 0, 0 ) ;
         return ;
      }
   }
   // the checksum over just the IP header
   if ( org + IP_HEADER_LEN >= sizeof(cmdPkt.buf ) ) {
      errRaiseErr( 0, 0, 0 ) ;
      return ;
   }
   cmdPkt.ip_sum = rfc_1071x( FALSE, 0L, cmdPkt.buf+org, IP_HEADER_LEN ) ;
   if( errIsRaised() ) {
      return ;
   }
   if ( cmdPkt.ip_sum != 0xFFFFL ) {
      errRaiseErr( 0, 0, 0 ) ;
      return  ;
   }
   // now we have the packet length including the headers
   cmdPkt.ip_len  = Read2( cmdPkt.buf + org + IP_SIZE_OFFSET  ) ;
   //lint -save -e662
   //guards guarantee that pointer is in range
   cmdPkt.udp_len = Read2( cmdPkt.buf + org + UDP_SIZE_OFFSET ) ;
   //lint -restore
   if ( cmdPkt.ip_len < MIN_CMD_PKT_LEN ) {
      errRaiseErr( 0, 0, 0 )  ;
      return  ;
   }
   // not enough data for a complete packet
   if ( org + cmdPkt.ip_len > cmdPkt.pkt_len ) {
      errRaiseErr( 0, 0, 0 )    ;
      return  ;
   }
   // check that the UDP length is OK
   if ( cmdPkt.udp_len + IP_HEADER_LEN != cmdPkt.ip_len ) {
      errRaiseErr( 0, 0, 0 ) ;
      return  ;
   }
   // we have udp-data, compute the UDP checksum including the pseudo header
   if ( org+IP_HEADER_LEN + cmdPkt.udp_len >= sizeof(cmdPkt.buf) ) {
      errRaiseErr( 0, 0, 0 ) ;
      return  ;
   }
   cmdPkt.udp_sum = rfc_1071x( TRUE, PseudoSum, cmdPkt.buf+org+IP_HEADER_LEN, cmdPkt.udp_len ) ;
   if( errIsRaised() ) {
      return ;
   }
   if ( cmdPkt.udp_sum != 0xFFFFL ) {
      errRaiseErr( 0, 0, 0 ) ;
      return  ;
   }
   cmdPkt.eop = org + cmdPkt.ip_len ;
   readEvalCIPs()             ;
   // are there bytes before the start of the packet ?
   if ( org ) {
      errRaiseErr( 0, 0, 0 )    ;
   }
   // are there bytes left over?
   if ( org + cmdPkt.ip_len > cmdPkt.pkt_len ) {
      errRaiseErr( 0, 0, 0 )    ;
      return  ;
   }
}