OCams FSW: ocams_telem.c File Reference
ocams_telem.c File Reference
This file contains code to queue telemetry packets to the S/C.
#include "ocams_telem.h"
#include "ocams_err.h"
#include "ocams_util.h"
#include "ocams_fpga.h"
#include "ocams_loop.h"
Functions
void telemTriggerEmit (void)
STATIC void telemSwapBuffers (void)
void telemPushPkt (const uint08 *buf, uint16 len)
void telemPopPkt (void)
void telemInitTelem (void)
Variables
STATIC uint08 xdata Aside [TELEM_BUF_LEN]
STATIC uint08 xdata Bside [TELEM_BUF_LEN]
STATIC bool xdata pushA
STATIC uint16 xdata r_dot
STATIC uint16 xdata r_size
STATIC uint16 xdata w_size
Detailed Description
This file contains code to queue telemetry packets to the S/C.
Copyright:
This document contains technical data that is controlled by the International Traffic in Arms Regulations (22 CFR 120-130) and may not be provided, disclosed, or transferred in any manner to any person, whether in the U.S. or abroad, who is not 1) a citizen of the United States, 2) a lawful permanent resident of the United States, or 3) a protected individual as defined by 8 USC 1324b(a)(3), without the written permission of the United States Department of State.
VersionControl
Definition in file ocams_telem.c.
Function Documentation
void telemInitTelem (void)
Function:
telemInitTelem()
Description:
A one time call to initialize the telemetry subsystem.
Return values
N/A
Exceptions
N/A
Definition at line 242 of file ocams_telem.c.
Referenced by main().
{
   pushA   = TRUE ;
   r_dot  = 0     ;
   r_size = 0     ;
   w_size = 0     ;
}
void telemPopPkt (void)
Function:
telemPopPkt()
Description:
Pop a packet from the currently active queue send it to the FPGA telemetry FIFO for transmission to the S/C
Return values
N/A
Exceptions
N/A
Definition at line 160 of file ocams_telem.c.
References errIsRaised(), errRaiseErr(), Read2(), telemSwapBuffers(), and telemTriggerEmit().
Referenced by loopExecLoopContents().
{
   uint16 len  ;
   uint16 next ;
   uint16 k    ;
   // 10 msec gap timer running
   if ( State.telem_active ) {
      return       ;
   }
   if ( r_size == 0 ) {
      telemSwapBuffers() ;
      if ( r_size == 0 ) {
         return     ;
      }
   }
   // locate the packet size from the first
   // word in the record
   if ( r_dot + TELEM_BUF_HEADER_LEN > r_size ) {
      next = 0 ;
      errRaiseErr( 0, 0, 0 ) ;
   }
   else {
      if ( pushA ) {
         len = Read2(Bside + r_dot )  ;
      }
      else {
         len = Read2(Aside + r_dot )  ;
      }
      next = r_dot + 2 + len   ;
      if ( len == 0 ) {
         errRaiseErr( 0, 0, 0 ) ;
      }
      if ( next > TELEM_BUF_LEN ) {
         errRaiseErr( 0, 0, 0 ) ;
      }
   }
   if ( errIsRaised() ) {
      r_dot  = 0  ;
      r_size = 0  ;
      return      ;
   }
   if ( pushA ) {
      for ( k = r_dot+TELEM_BUF_HEADER_LEN ; k < next ; k++ ) {
         sfr_write(ScTlmFifo, Bside[k])   ;
      }
   }
   else {
      for ( k = r_dot+TELEM_BUF_HEADER_LEN ; k < next ; k++ ) {
         sfr_write(ScTlmFifo, Aside[k])   ;
      }
   }
   r_dot  = next ;
   if ( r_dot + TELEM_BUF_HEADER_LEN >= r_size ) {
      r_size = 0  ;
   }
   // trigger FIFO transmission
   State.telem_active = TRUE ;
   telemTriggerEmit()        ;
}
void telemPushPkt (const uint08 * buf, uint16 len)
Function:
telemPushPkt()
Description:
Calledd from the main loop or its children to push a telemetry packet onto the queue for transmission to the S/C
Return values
N/A
Exceptions
N/A
Parameters
buf buffer containing the packet
len buffer length in bytes
Definition at line 117 of file ocams_telem.c.
References errRaiseErr(), and Write2().
Referenced by pktEmitHK(), pktEmitMsg(), and pktEmitNOOP().
{
   uint16 k ;
   if ( w_size + len + TELEM_BUF_HEADER_LEN > TELEM_BUF_LEN ) {
      errRaiseErr( 0, 0, 0 ) ;
      return ;
   }
   if ( pushA ) {
      Write2( Aside + w_size, len )   ;
      w_size += 2              ;
      for ( k = 0 ; k < len ; k++, w_size++ ) {
         Aside[w_size] = buf[k]     ;
      }
   }
   else {
      Write2( Bside + w_size, len )   ;
      w_size += 2              ;
      for ( k = 0 ; k < len ; k++, w_size++ ) {
         Bside[w_size] = buf[k]     ;
      }
   }
}
STATIC void telemSwapBuffers (void)
Function:
telemSwapBuffers()
Description:
This function is called from the main loop and swaps the ping/pong queues if and only if:
there is no ongoing active transmission to the S/C
the current queue has been drained
the alternate queue is non-empty
Return values
N/A
Exceptions
N/A
Definition at line 74 of file ocams_telem.c.
Referenced by telemPopPkt().
{
   // current buffer not empty
   if ( r_size != 0 ) {
      return ;
   }
   // other buffer is empty too
   if ( w_size == 0 ) {
      return ;
   }
   // have to wait out gap timer
   if ( State.telem_active ) {
      return ;
   }
   // and swap
   if ( pushA ) {
      pushA = FALSE ;
   }
   else {
      pushA = TRUE  ;
   }
   r_dot  = 0       ;  // start of first record in new buffer
   r_size = w_size  ;  // size of new buffer
   w_size = 0       ;  // clear old buffer
}
void telemTriggerEmit (void)
Function:
telemTriggerEmit()
Description:
Command the FPGA telemtry FIFO to begin transmitting its contents to the S/C. This function is called after the FIFO has been loaded with a complete enginerring telemetry packet.
Return values
N/A
Exceptions
N/A
Definition at line 52 of file ocams_telem.c.
Referenced by telemPopPkt().
{
   sfr_write(ScTlmCsr, TELEM_TRIGGER) ;
}