OCams FSW: ocams_loop.h File Reference
ocams_loop.h File Reference
Header file for ocams_loop.c.
#include "ocams_fsw.h"
Data Structures
struct state_t
Typedefs
typedef struct state_t state_t
Functions
void loopInitLoop (void)
void loopExecLoopContents (void)
void loopExecLoop (void)
Variables
state_t xdata State
Detailed Description
Header file for ocams_loop.c.
Copyright:
This document contains technical data that is controlled by the International Traffic in Arms Regulations (22 CFR 120-130) and may not be provided, disclosed, or transferred in any manner to any person, whether in the U.S. or abroad, who is not 1) a citizen of the United States, 2) a lawful permanent resident of the United States, or 3) a protected individual as defined by 8 USC 1324b(a)(3), without the written permission of the United States Department of State.
VersionControl
Definition in file ocams_loop.h.
Function Documentation
void loopExecLoop (void)
Function:
loopExecLoop()
Description:
Enter the main processing loop. This function never returns.
Return values
N/A
Exceptions
N/A
Definition at line 120 of file ocams_loop.c.
References loopExecLoopContents().
Referenced by main().
{
   while ( TRUE ) {
      loopExecLoopContents();
   }
}
void loopExecLoopContents (void)
Function:
loopExecLoopContents()
Description:
The main processing loop execution. One pass thru the loop.
Return values
N/A
Exceptions
N/A
Definition at line 47 of file ocams_loop.c.
References errIsRaised(), errProcessErr(), msgIsReady(), pktEmitHK(), pktEmitMsg(), pktEmitNOOP(), readDrainFIFO(), readFifoNotEmpty(), readScanPkt(), and telemPopPkt().
Referenced by loopExecLoop().
{
      // call fault handler if needed
      if ( errIsRaised() ) {
         errProcessErr() ;
      }
      // on H/K required
      if ( State.emit_hk ) {
         State.emit_hk = FALSE ;
         pktEmitHK()           ;
         if ( errIsRaised() ) {
            errProcessErr()    ;
         }
         else {
            State.emit_aliveness = FALSE ;        // not needed if H/K sent
         }
      }
      // on aliveness packet required
      if ( State.emit_aliveness ) {
         State.emit_aliveness = FALSE ;
         pktEmitNOOP()                ;
         if ( errIsRaised() ) {
            errProcessErr() ;
         }
      }
      // there is a message packet ready to be queued
      if ( msgIsReady() ) {
         pktEmitMsg()     ;
         if ( errIsRaised() ) {
            errProcessErr() ;
         }
      }
      // check if there is a packet in the telemetry queue and
      // if so, pop it and send it to the FPGA telemetry FIFO
      telemPopPkt()         ;
      if ( errIsRaised()   ) {
         errProcessErr()    ;
      }
      // command FIFO <non-empty>, append contents to buffer
      if ( readFifoNotEmpty() ) {
         readDrainFIFO()     ;
         if ( errIsRaised() ) {
            errProcessErr()  ;
         }
      }
      // interrupt raised at <end-of-command> gap [ >= 10 msec ]
      if ( State.have_eoc ) {
         State.have_eoc = FALSE ;
         readDrainFIFO()      ;  // make certain we have all the data
         readScanPkt( )       ;  // validate packet and evaluate contents
         if ( errIsRaised() ) {
            errProcessErr()     ;
         }
      }
}
void loopInitLoop (void)
Function:
loopInitLoop()
Description:
Must be called to initialize the FSW state before entering the main loop.
Return values
N/A
Exceptions
N/A
Definition at line 140 of file ocams_loop.c.
Referenced by main().
{
   State.have_eoc        = FALSE ;
   State.emit_hk         = FALSE ;
   State.emit_aliveness  = FALSE ;
   State.telem_active    = FALSE ;
   State.hk_interval     = 1     ;
   State.cmd_received    = 0     ;
   State.cmd_rejected    = 0     ;
}