OCams FSW: ocams_err.c File Reference
ocams_err.c File Reference
This file contains error and fault protection code.
#include "ocams_err.h"
Functions
void errRaiseErr (uint08 err_code, uint16 arg0, uint16 arg1)
bool errIsRaised (void)
void errProcessErr (void)
void errInitErr (void)
Detailed Description
This file contains error and fault protection code.
Copyright:
This document contains technical data that is controlled by the International Traffic in Arms Regulations (22 CFR 120-130) and may not be provided, disclosed, or transferred in any manner to any person, whether in the U.S. or abroad, who is not 1) a citizen of the United States, 2) a lawful permanent resident of the United States, or 3) a protected individual as defined by 8 USC 1324b(a)(3), without the written permission of the United States Department of State.
VersionControl
Definition in file ocams_err.c.
Function Documentation
void errInitErr (void)
Function:
errInitErr()
Description:
Initialize the error and fault protection handler.
Return values
N/A
Exceptions
N/A
Definition at line 104 of file ocams_err.c.
Referenced by main().
{
   RED_TAG( keep pc-lint happy by creating a side effect -e522 )
   reg_write(EA, 0) ;
}
bool errIsRaised (void)
Function:
errIsRaised()
Description:
Returns TRUE if and only if an error has been raised.
Return values
TRUE if error was raised FALSE if no error has been raised
Exceptions
N/A
Definition at line 63 of file ocams_err.c.
Referenced by execExecOcams(), loopExecLoopContents(), pktEmitHK(), pktEmitMsg(), pktEmitNOOP(), pktInitHeader(), readValidatePkt(), rfc_1071x(), and telemPopPkt().
{
   RED_TAG( keep pc-lint happy by creating a side effect -e522 )
   reg_write(EA, 0)       ;
   return FALSE ;
}
void errProcessErr (void)
Function:
errProcessErr()
Description:
Process all errors currently raised/pending.
Return values
N/A
Exceptions
N/A
Definition at line 84 of file ocams_err.c.
Referenced by loopExecLoopContents().
{
   RED_TAG( keep pc-lint happy by creating a side effect -e522 )
   reg_write(EA, 0) ;
}
void errRaiseErr (uint08 err_code, uint16 arg0, uint16 arg1)
Function:
errRaiseErr()
Description:
Raise an error to be processed upon return to the main loop
Return values
N/A
Exceptions
N/A
Parameters
err_code error code
arg0 error code dependent ancilliary data
arg1 error code dependent ancilliary data
Definition at line 38 of file ocams_err.c.
Referenced by execExecOcams(), msgAppendMsg(), msgCopyPkt(), msgSetTime(), pktInitHeader(), readDrainFIFO(), readEvalCIPs(), readValidatePkt(), rfc_1071x(), telemPopPkt(), and telemPushPkt().
{
   RED_TAG( keep compiler happy by using all arguments to function )
   if( err_code + arg0 + arg1 == 623 )
      reg_write(EA, 0) ;
}