OCams FSW: ocams_read.h File Reference
ocams_read.h File Reference
Header file for ocams_read.c.
#include "ocams_fsw.h"
Data Structures
struct cmd_pkt
Macros
#define COMMAND_BUF_LEN 3000
#define MAX_CIP_COUNT 16
Typedefs
typedef struct cmd_pkt cmd_pkt
Functions
void readInitRead (void)
bool readFifoNotEmpty (void)
bool readFifoIsEmpty (void)
void readScanPkt (void)
void readDrainFIFO (void)
Detailed Description
Header file for ocams_read.c.
Copyright:
This document contains technical data that is controlled by the International Traffic in Arms Regulations (22 CFR 120-130) and may not be provided, disclosed, or transferred in any manner to any person, whether in the U.S. or abroad, who is not 1) a citizen of the United States, 2) a lawful permanent resident of the United States, or 3) a protected individual as defined by 8 USC 1324b(a)(3), without the written permission of the United States Department of State.
VersionControl
Definition in file ocams_read.h.
Function Documentation
void readDrainFIFO (void)
Function:
readDrainFIFO()
Description:
Copy the contents of the FPGA command FIFO into the command parsing buffer. The process continues until the FIFO has been drained or until the command buffer is full.
Return values
N/A
Exceptions
N/A
Definition at line 110 of file ocams_read.c.
References errRaiseErr(), readFifoIsEmpty(), and readReadChar().
Referenced by loopExecLoopContents().
{
   uint16 k ;
   if ( cmdPkt.pkt_len >= COMMAND_BUF_LEN ) {
      errRaiseErr( 0, 0, 0 ) ;
      return ;
   }
   for ( k = cmdPkt.pkt_len ; k < COMMAND_BUF_LEN ; k++ ) {
      if ( readFifoIsEmpty() ) {
         break ;
      }
      cmdPkt.buf[k] = readReadChar() ;
   }
   cmdPkt.pkt_len = k ;
}
bool readFifoIsEmpty (void)
Function:
readFifoIsEmpty()
Description:
Return TRUE if the FPGA Command FIFO is not empty.
Return values
TRUE FPGA command FIFO is empty FALSE FPGA command FIFO is not empty
Exceptions
N/A
Definition at line 49 of file ocams_read.c.
Referenced by readDrainFIFO().
{
   return CMD_FIFO_EMPTY ? TRUE : FALSE ;
}
bool readFifoNotEmpty (void)
Function:
readFifoNotEmpty()
Description:
Return TRUE if the FPGA Command FIFO is not empty.
Return values
TRUE FPGA command FIFO not empty FALSE FPGA command FIFO is empty
Exceptions
N/A
Definition at line 68 of file ocams_read.c.
Referenced by loopExecLoopContents().
{
   return CMD_FIFO_EMPTY ? FALSE : TRUE ;
}
void readInitRead (void)
Function:
readInitRead()
Description:
One time call to initialize the command transaction parser to a known state. This must be called prior to parsing any transaction.
Return values
N/A
Exceptions
N/A
Definition at line 383 of file ocams_read.c.
Referenced by main().
{
   cmdPkt.pkt_len  = 0  ;
   cmdPkt.ip_len   = 0  ;
   cmdPkt.udp_len  = 0  ;
   cmdPkt.ip_sum   = 0  ;
   cmdPkt.udp_sum  = 0  ;
   cmdPkt.org      = 0  ;
}
void readScanPkt (void)
Function:
readScanPkt()
Description:
This is a wrapper for readValidatePkt(). It guarantees that the command parser is reset to a known state even if readValidatePkt() should fail.
Return values
N/A
Exceptions
N/A
Definition at line 354 of file ocams_read.c.
References readValidatePkt().
Referenced by loopExecLoopContents().
{
   readValidatePkt() ;
   // these data are stale so set to default state
   // maybe just call readReadInit() instead
   cmdPkt.ip_len  = 0  ;
   cmdPkt.udp_len = 0  ;
   cmdPkt.ip_sum  = 0  ;
   cmdPkt.udp_sum = 0  ;
   cmdPkt.org     = 0  ;
   cmdPkt.pkt_len = 0  ;
   // add command here to flush the FIFO
}