OCams FSW: ocams_packet.h File Reference
ocams_packet.h File Reference
Header file for ocams_packet.c.
#include "ocams_fsw.h"
Data Structures
struct hk_pkt
Macros
#define HK_PKT_ID 0x03
#define MSG_PKT_ID 0x04
#define MAX_PACKET_LEN 2100
#define HK_PKT_LEN sizeof(hk_pkt)
Typedefs
typedef struct hk_pkt hk_pkt
Functions
void pktEmitHK (void)
void pktEmitNOOP (void)
void pktEmitMsg (void)
Detailed Description
Header file for ocams_packet.c.
Copyright:
This document contains technical data that is controlled by the International Traffic in Arms Regulations (22 CFR 120-130) and may not be provided, disclosed, or transferred in any manner to any person, whether in the U.S. or abroad, who is not 1) a citizen of the United States, 2) a lawful permanent resident of the United States, or 3) a protected individual as defined by 8 USC 1324b(a)(3), without the written permission of the United States Department of State.
VersionControl
Definition in file ocams_packet.h.
Function Documentation
void pktEmitHK (void)
Function:
pktEmitHK
Description:
This routine creates an OCAMS HK packet and queues it for transmission to the S/C.
Return values
N/A
Exceptions
N/A
Definition at line 160 of file ocams_packet.c.
References clockReadSclk(), errIsRaised(), pktInitHeader(), rfc_1071x(), telemPushPkt(), and Write2().
Referenced by loopExecLoopContents().
{
   uint16   csum ;
   uint08  *base ;
   hk_pkt  *hp   ;
   pktInitHeader( CIP_ENGINEERING, HK_PKT_LEN ) ;
   if ( errIsRaised() ) {
      return ;
   }
   base = tlmPkt.buf + CIP_DATA_OFFSET ;
   hp   = (hk_pkt*) base            ;
   clockReadSclk() ;
   hp->hk_type   = HK_PKT_ID        ;
   hp->sclk_secs = TheSclk.secs     ;
   hp->sclk_tics = TheSclk.tics     ;
   hp->len       = sizeof(hk_pkt)   ;
   // clear the UDP check-sum
   Write2( tlmPkt.buf + UDP_CSUM_OFFSET, 0   )  ;
   csum = rfc_1071x( TRUE, PseudoSum, tlmPkt.buf + UDP_OFFSET, tlmPkt.udp_len ) ;
   if( errIsRaised() ) {
      return ;
   }
   Write2( tlmPkt.buf + UDP_CSUM_OFFSET, csum ) ;
   telemPushPkt( tlmPkt.buf, tlmPkt.ip_len )    ;
}
void pktEmitMsg (void)
Function:
pktEmitMsg()
Description:
This routine creates a message packet and queues it for transmission to the S/C. The contents of the packet are copied from the message packet staging area where messages have been accumulating to this point in time.
Return values
N/A
Exceptions
N/A
Definition at line 208 of file ocams_packet.c.
References errIsRaised(), msgCopyPkt(), msgGetSize(), pktInitHeader(), rfc_1071x(), telemPushPkt(), and Write2().
Referenced by loopExecLoopContents().
{
   uint16  csum    ;
   uint08 *base    ;
   uint16  msg_len ;
   msg_len = msgGetSize() ;
   pktInitHeader( CIP_ENGINEERING, msg_len ) ;
   if ( errIsRaised() ) {
      return ;
   }
   base = tlmPkt.buf + CIP_DATA_OFFSET ;
   msgCopyPkt( base, msg_len  )   ;
   if ( errIsRaised() ) {
      return ;
   }
   // clear the UDP check-sum
   Write2( tlmPkt.buf + UDP_CSUM_OFFSET, 0   )  ;
   csum = rfc_1071x( TRUE, PseudoSum, tlmPkt.buf + UDP_OFFSET, tlmPkt.udp_len ) ;
   if( errIsRaised() ) {
      return ;
   }
   Write2( tlmPkt.buf + UDP_CSUM_OFFSET, csum ) ;
   telemPushPkt( tlmPkt.buf, tlmPkt.ip_len )    ;
}
void pktEmitNOOP (void)
Function:
pktEmitNOOP()
Description:
Create a packet containing a NOOP CIP, type 0x00, and then queue for transmission to the S/C. This is the simplist packet that can be created.
Return values
N/A
Exceptions
N/A
Definition at line 125 of file ocams_packet.c.
References errIsRaised(), pktInitHeader(), rfc_1071x(), telemPushPkt(), and Write2().
Referenced by loopExecLoopContents().
{
   uint16 csum  ;
   pktInitHeader( CIP_NOOP, NOP_DATA_LEN ) ;
   if ( errIsRaised() ) {
      return ;
   }
   // clear the check-sum
   Write2( tlmPkt.buf + UDP_CSUM_OFFSET, 0   )  ;
   csum = rfc_1071x( TRUE, PseudoSum, tlmPkt.buf + UDP_OFFSET, tlmPkt.udp_len ) ;
   if( errIsRaised() ) {
      return ;
   }
   Write2( tlmPkt.buf + UDP_CSUM_OFFSET, csum ) ;
   telemPushPkt( tlmPkt.buf, tlmPkt.ip_len )       ;
}