onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /Tb_CoreAHBLtoAXI/HCLK
add wave -noupdate /Tb_CoreAHBLtoAXI/HRESETn
add wave -noupdate /Tb_CoreAHBLtoAXI/HSEL
add wave -noupdate /Tb_CoreAHBLtoAXI/HADDR
add wave -noupdate /Tb_CoreAHBLtoAXI/HWRITE
add wave -noupdate /Tb_CoreAHBLtoAXI/HREADY
add wave -noupdate /Tb_CoreAHBLtoAXI/HTRANS
add wave -noupdate /Tb_CoreAHBLtoAXI/HSIZE
add wave -noupdate /Tb_CoreAHBLtoAXI/HWDATA
add wave -noupdate /Tb_CoreAHBLtoAXI/HBURST
add wave -noupdate /Tb_CoreAHBLtoAXI/HMASTLOCK
add wave -noupdate /Tb_CoreAHBLtoAXI/HREADYOUT
add wave -noupdate /Tb_CoreAHBLtoAXI/HRESP
add wave -noupdate /Tb_CoreAHBLtoAXI/HRDATA
add wave -noupdate /Tb_CoreAHBLtoAXI/ACLK
add wave -noupdate /Tb_CoreAHBLtoAXI/ARESETn
add wave -noupdate /Tb_CoreAHBLtoAXI/AWREADY
add wave -noupdate /Tb_CoreAHBLtoAXI/WREADY
add wave -noupdate /Tb_CoreAHBLtoAXI/BID
add wave -noupdate /Tb_CoreAHBLtoAXI/BRESP
add wave -noupdate /Tb_CoreAHBLtoAXI/BVALID
add wave -noupdate /Tb_CoreAHBLtoAXI/ARREADY
add wave -noupdate /Tb_CoreAHBLtoAXI/RID
add wave -noupdate /Tb_CoreAHBLtoAXI/RDATA
add wave -noupdate /Tb_CoreAHBLtoAXI/RRESP
add wave -noupdate /Tb_CoreAHBLtoAXI/RLAST
add wave -noupdate /Tb_CoreAHBLtoAXI/RVALID
add wave -noupdate /Tb_CoreAHBLtoAXI/AWID
add wave -noupdate /Tb_CoreAHBLtoAXI/AWADDR
add wave -noupdate /Tb_CoreAHBLtoAXI/AWLEN
add wave -noupdate /Tb_CoreAHBLtoAXI/AWSIZE
add wave -noupdate /Tb_CoreAHBLtoAXI/AWBURST
add wave -noupdate /Tb_CoreAHBLtoAXI/AWVALID
add wave -noupdate /Tb_CoreAHBLtoAXI/WID
add wave -noupdate /Tb_CoreAHBLtoAXI/WDATA
add wave -noupdate /Tb_CoreAHBLtoAXI/WSTRB
add wave -noupdate /Tb_CoreAHBLtoAXI/WLAST
add wave -noupdate /Tb_CoreAHBLtoAXI/WVALID
add wave -noupdate /Tb_CoreAHBLtoAXI/BREADY
add wave -noupdate /Tb_CoreAHBLtoAXI/ARID
add wave -noupdate /Tb_CoreAHBLtoAXI/ARADDR
add wave -noupdate /Tb_CoreAHBLtoAXI/ARLEN
add wave -noupdate /Tb_CoreAHBLtoAXI/ARSIZE
add wave -noupdate /Tb_CoreAHBLtoAXI/ARBURST
add wave -noupdate /Tb_CoreAHBLtoAXI/ARLOCK
add wave -noupdate /Tb_CoreAHBLtoAXI/ARVALID
add wave -noupdate /Tb_CoreAHBLtoAXI/RREADY
add wave -noupdate /Tb_CoreAHBLtoAXI/AWLOCK
add wave -noupdate /Tb_CoreAHBLtoAXI/i
add wave -noupdate /Tb_CoreAHBLtoAXI/r
add wave -noupdate /Tb_CoreAHBLtoAXI/int
add wave -noupdate /Tb_CoreAHBLtoAXI/burst
add wave -noupdate /Tb_CoreAHBLtoAXI/size
add wave -noupdate /Tb_CoreAHBLtoAXI/trans_no
add wave -noupdate /Tb_CoreAHBLtoAXI/j
add wave -noupdate /Tb_CoreAHBLtoAXI/U_checker/write_actual_mem
add wave -noupdate /Tb_CoreAHBLtoAXI/U_checker/write_golden_mem
add wave -noupdate /Tb_CoreAHBLtoAXI/U_CoreAHBLtoAXI/burst_count_valid_sync
add wave -noupdate /Tb_CoreAHBLtoAXI/U_CoreAHBLtoAXI/rdch_fifo_full
add wave -noupdate /Tb_CoreAHBLtoAXI/U_CoreAHBLtoAXI/rdch_fifo_wr_en_r
add wave -noupdate /Tb_CoreAHBLtoAXI/U_checker/write_actual_mem
add wave -noupdate /Tb_CoreAHBLtoAXI/U_checker/write_golden_mem
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {373750 ps} 0}
configure wave -namecolwidth 432
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {750750 ps}
