#!/bin/bash
sudo umount -lf /home/steve/projects/zonge/457/Ch1
sudo umount -lf /home/steve/projects/zonge/457/Ch2
sudo umount -lf /home/steve/projects/zonge/457/Ch3
sudo umount -lf /home/steve/projects/zonge/457/Ch4
sudo umount -lf /home/steve/projects/zonge/457/Ch5
sudo umount -lf /home/steve/projects/zonge/457/Ch6

rm -r /home/steve/projects/zonge/457/Ch1/*
rm -r /home/steve/projects/zonge/457/Ch2/*
rm -r /home/steve/projects/zonge/457/Ch3/*
rm -r /home/steve/projects/zonge/457/Ch4/*
rm -r /home/steve/projects/zonge/457/Ch5/*
rm -r /home/steve/projects/zonge/457/Ch6/*

sshfs root@10.$1.1.1:/home/root /home/steve/projects/zonge/457/Ch1 -ouid=1000 -ogid=1000 -o reconnect,ServerAliveInterval=1,ServerAliveCountMax=3,TCPKeepAlive=yes,cache_timeout=3
sshfs root@10.$1.2.1:/home/root /home/steve/projects/zonge/457/Ch2 -ouid=1000 -ogid=1000 -o reconnect,ServerAliveInterval=1,ServerAliveCountMax=3,TCPKeepAlive=yes,cache_timeout=3
sshfs root@10.$1.3.1:/home/root /home/steve/projects/zonge/457/Ch3 -ouid=1000 -ogid=1000 -o reconnect,ServerAliveInterval=1,ServerAliveCountMax=3,TCPKeepAlive=yes,cache_timeout=3
sshfs root@10.$1.4.1:/home/root /home/steve/projects/zonge/457/Ch4 -ouid=1000 -ogid=1000 -o reconnect,ServerAliveInterval=1,ServerAliveCountMax=3,TCPKeepAlive=yes,cache_timeout=3
sshfs root@10.$1.5.1:/home/root /home/steve/projects/zonge/457/Ch5 -ouid=1000 -ogid=1000 -o reconnect,ServerAliveInterval=1,ServerAliveCountMax=3,TCPKeepAlive=yes,cache_timeout=3
sshfs root@10.$1.6.1:/home/root /home/steve/projects/zonge/457/Ch6 -ouid=1000 -ogid=1000 -o reconnect,ServerAliveInterval=1,ServerAliveCountMax=3,TCPKeepAlive=yes,cache_timeout=3
