#!/bin/bash
sudo umount -lf /home/steve/projects/zonge/457/Ch1
sudo umount -lf /home/steve/projects/zonge/457/Ch2
sudo umount -lf /home/steve/projects/zonge/457/Ch3
sudo umount -lf /home/steve/projects/zonge/457/Ch4
sudo umount -lf /home/steve/projects/zonge/457/Ch5
sudo umount -lf /home/steve/projects/zonge/457/Ch6
