Design Entry;SmartDesign Check||(null)||'Filterwheel_sb' was successfully generated.  ||(null);(null)||(null);(null)
Design Entry;SmartDesign Check||(null)||Please refer for details about Filterwheel_sb||Filterwheel_sb Log;liberoaction://open_report/file/Filterwheel_sb_SYS_BLD.xml||(null);(null)
HelpInfo,/home/summer/microchip/Libero_SoC_v2023.2/SynplifyPro/lib/html,fpgahelp.qhc,synerrmsg.mp,/home/summer/microchip/Libero_SoC_v2023.2/SynplifyPro/bin/assistant
