ESC FilterWheel C++ Source: BinaryUartRingBuffer.cpp File Reference
BinaryUartRingBuffer.cpp File Reference
#include "BinaryUartRingBuffer.hpp"
Functions
void TxBinaryPacket (const void *TxPktContext, const uint16_t PayloadTypeToken, const uint32_t SerialNumber, const void *PayloadData, const size_t PayloadLen)
Function Documentation
TxBinaryPacket()
void TxBinaryPacket (const void * TxPktContext, const uint16_t PayloadTypeToken, const uint32_t SerialNumber, const void * PayloadData, const size_t PayloadLen)
Definition at line 4 of file BinaryUartRingBuffer.cpp.
References formatf(), PayloadData(), PayloadLen, and TxBinaryPacket().
Referenced by TxBinaryPacket().