ESC FilterWheel C++ Source: fixedqueue_mt< T, queue_size > Class Template Reference
fixedqueue_mt< T, queue_size > Class Template Reference
Copyright (c) by Franks Development, LLC.
#include <fixedqueue_mt.hpp>
Public Member Functions
fixedqueue_mt ()
size_t max () const
bool empty () const
bool wasEmpty () const
bool full () const
bool wasFull () const
size_t len () const
size_t depth () const
void clear ()
void flush ()
bool pop (T &element)
bool push (T const &element)
Private Member Functions
T data[queue_size] __attribute__ ((aligned(4)))
size_t next (const size_t in) const
Private Attributes
std::atomic< size_t > begin
std::atomic< size_t > end
Detailed Description
template<typename T, size_t queue_size>
class fixedqueue_mt< T, queue_size >
Copyright (c) by Franks Development, LLC.
Definition at line 32 of file fixedqueue_mt.hpp.
Constructor & Destructor Documentation
fixedqueue_mt()
template<typename T , size_t queue_size> fixedqueue_mt< T, queue_size >::fixedqueue_mt () inline
Definition at line 45 of file fixedqueue_mt.hpp.
Member Function Documentation
__attribute__()
template<typename T , size_t queue_size> T data[queue_size] fixedqueue_mt< T, queue_size >::__attribute__ ((aligned(4))) private
clear()
template<typename T , size_t queue_size> void fixedqueue_mt< T, queue_size >::clear () inline
Definition at line 64 of file fixedqueue_mt.hpp.
References fixedqueue_mt< T, queue_size >::begin, and fixedqueue_mt< T, queue_size >::end.
Referenced by fixedqueue_mt< T, queue_size >::flush().
depth()
template<typename T , size_t queue_size> size_t fixedqueue_mt< T, queue_size >::depth () const inline
Definition at line 62 of file fixedqueue_mt.hpp.
References fixedqueue_mt< T, queue_size >::len().
empty()
template<typename T , size_t queue_size> bool fixedqueue_mt< T, queue_size >::empty () const inline
Definition at line 49 of file fixedqueue_mt.hpp.
References fixedqueue_mt< T, queue_size >::begin, and fixedqueue_mt< T, queue_size >::end.
Referenced by fixedqueue_mt< T, queue_size >::pop(), and fixedqueue_mt< T, queue_size >::wasEmpty().
flush()
template<typename T , size_t queue_size> void fixedqueue_mt< T, queue_size >::flush () inline
Definition at line 65 of file fixedqueue_mt.hpp.
References fixedqueue_mt< T, queue_size >::clear().
full()
template<typename T , size_t queue_size> bool fixedqueue_mt< T, queue_size >::full () const inline
Definition at line 52 of file fixedqueue_mt.hpp.
References fixedqueue_mt< T, queue_size >::begin, fixedqueue_mt< T, queue_size >::end, and fixedqueue_mt< T, queue_size >::next().
Referenced by fixedqueue_mt< T, queue_size >::push(), and fixedqueue_mt< T, queue_size >::wasFull().
len()
template<typename T , size_t queue_size> size_t fixedqueue_mt< T, queue_size >::len () const inline
Definition at line 55 of file fixedqueue_mt.hpp.
References fixedqueue_mt< T, queue_size >::begin, and fixedqueue_mt< T, queue_size >::end.
Referenced by fixedqueue_mt< T, queue_size >::depth().
max()
template<typename T , size_t queue_size> size_t fixedqueue_mt< T, queue_size >::max () const inline
Definition at line 47 of file fixedqueue_mt.hpp.
next()
template<typename T , size_t queue_size> size_t fixedqueue_mt< T, queue_size >::next (const size_t in) const inline private
Definition at line 41 of file fixedqueue_mt.hpp.
Referenced by fixedqueue_mt< T, queue_size >::full(), fixedqueue_mt< T, queue_size >::pop(), and fixedqueue_mt< T, queue_size >::push().
pop()
template<typename T , size_t queue_size> bool fixedqueue_mt< T, queue_size >::pop (T & element) inline
Definition at line 67 of file fixedqueue_mt.hpp.
References fixedqueue_mt< T, queue_size >::begin, fixedqueue_mt< T, queue_size >::empty(), and fixedqueue_mt< T, queue_size >::next().
push()
template<typename T , size_t queue_size> bool fixedqueue_mt< T, queue_size >::push (T const & element) inline
Definition at line 75 of file fixedqueue_mt.hpp.
References fixedqueue_mt< T, queue_size >::end, fixedqueue_mt< T, queue_size >::full(), and fixedqueue_mt< T, queue_size >::next().
wasEmpty()
template<typename T , size_t queue_size> bool fixedqueue_mt< T, queue_size >::wasEmpty () const inline
Definition at line 50 of file fixedqueue_mt.hpp.
References fixedqueue_mt< T, queue_size >::empty().
wasFull()
template<typename T , size_t queue_size> bool fixedqueue_mt< T, queue_size >::wasFull () const inline
Definition at line 53 of file fixedqueue_mt.hpp.
References fixedqueue_mt< T, queue_size >::full().
Member Data Documentation
begin
template<typename T , size_t queue_size> std::atomic<size_t> fixedqueue_mt< T, queue_size >::begin private
Definition at line 38 of file fixedqueue_mt.hpp.
Referenced by fixedqueue_mt< T, queue_size >::clear(), fixedqueue_mt< T, queue_size >::empty(), fixedqueue_mt< T, queue_size >::full(), fixedqueue_mt< T, queue_size >::len(), and fixedqueue_mt< T, queue_size >::pop().
end
template<typename T , size_t queue_size> std::atomic<size_t> fixedqueue_mt< T, queue_size >::end private
Definition at line 39 of file fixedqueue_mt.hpp.
Referenced by fixedqueue_mt< T, queue_size >::clear(), fixedqueue_mt< T, queue_size >::empty(), fixedqueue_mt< T, queue_size >::full(), fixedqueue_mt< T, queue_size >::len(), and fixedqueue_mt< T, queue_size >::push().
The documentation for this class was generated from the following file:
fixedqueue_mt.hpp