ESC FilterWheel C++ Source: fixedlist< T, list_size > Class Template Reference
fixedlist< T, list_size > Class Template Reference
Copyright (c) by Franks Development, LLC.
#include <fixedlist.hpp>
Public Member Functions
fixedlist ()
fixedlist (const size_t len, const T t[])
size_t Size () const
T * Data ()
T & operator[] (size_t i)
size_t Len ()
bool Used (const size_t i) const
bool Get (size_t i, T &element) const
void Clear ()
bool Add (T const &element)
T const & operator+= (T const &element)
bool AddUnique (T const &element)
bool UpdateUnique (T const &element)
bool Delete (T const &element)
bool Delete (const size_t index)
size_t Find (T const &element) const
bool Replace (size_t i, const T &element)
Private Member Functions
T data[list_size] __attribute__ ((aligned(4)))
Private Attributes
bool slot_used [list_size]
Detailed Description
template<typename T, size_t list_size = 16>
class fixedlist< T, list_size >
Copyright (c) by Franks Development, LLC.
Definition at line 31 of file fixedlist.hpp.
Constructor & Destructor Documentation
fixedlist() [1/2]
template<typename T , size_t list_size = 16> fixedlist< T, list_size >::fixedlist () inline
Definition at line 40 of file fixedlist.hpp.
References fixedlist< T, list_size >::Clear().
fixedlist() [2/2]
template<typename T , size_t list_size = 16> fixedlist< T, list_size >::fixedlist (const size_t len, const T t[]) inline
Definition at line 45 of file fixedlist.hpp.
References fixedlist< T, list_size >::Add(), and fixedlist< T, list_size >::Clear().
Member Function Documentation
__attribute__()
template<typename T , size_t list_size = 16> T data[list_size] fixedlist< T, list_size >::__attribute__ ((aligned(4))) private
Add()
template<typename T , size_t list_size = 16> bool fixedlist< T, list_size >::Add (T const & element) inline
Definition at line 97 of file fixedlist.hpp.
References fixedlist< T, list_size >::slot_used.
Referenced by fixedlist< T, list_size >::AddUnique(), fixedlist< T, list_size >::fixedlist(), fixedlist< T, list_size >::operator+=(), and fixedlist< T, list_size >::UpdateUnique().
AddUnique()
template<typename T , size_t list_size = 16> bool fixedlist< T, list_size >::AddUnique (T const & element) inline
Definition at line 113 of file fixedlist.hpp.
References fixedlist< T, list_size >::Add(), and fixedlist< T, list_size >::Find().
Clear()
template<typename T , size_t list_size = 16> void fixedlist< T, list_size >::Clear () inline
Definition at line 89 of file fixedlist.hpp.
References fixedlist< T, list_size >::slot_used.
Referenced by fixedlist< T, list_size >::fixedlist(), and fixedlist< T, list_size >::fixedlist().
Data()
template<typename T , size_t list_size = 16> T * fixedlist< T, list_size >::Data () inline
Definition at line 55 of file fixedlist.hpp.
Delete() [1/2]
template<typename T , size_t list_size = 16> bool fixedlist< T, list_size >::Delete (const size_t index) inline
Definition at line 151 of file fixedlist.hpp.
References fixedlist< T, list_size >::slot_used.
Delete() [2/2]
template<typename T , size_t list_size = 16> bool fixedlist< T, list_size >::Delete (T const & element) inline
Definition at line 138 of file fixedlist.hpp.
References fixedlist< T, list_size >::slot_used.
Find()
template<typename T , size_t list_size = 16> size_t fixedlist< T, list_size >::Find (T const & element) const inline
Definition at line 160 of file fixedlist.hpp.
References fixedlist< T, list_size >::slot_used.
Referenced by fixedlist< T, list_size >::AddUnique(), and fixedlist< T, list_size >::UpdateUnique().
Get()
template<typename T , size_t list_size = 16> bool fixedlist< T, list_size >::Get (size_t i, T & element) const inline
Definition at line 76 of file fixedlist.hpp.
References fixedlist< T, list_size >::slot_used.
Len()
template<typename T , size_t list_size = 16> size_t fixedlist< T, list_size >::Len () inline
Definition at line 60 of file fixedlist.hpp.
References fixedlist< T, list_size >::slot_used.
operator+=()
template<typename T , size_t list_size = 16> T const & fixedlist< T, list_size >::operator+= (T const & element) inline
Definition at line 111 of file fixedlist.hpp.
References fixedlist< T, list_size >::Add().
operator[]()
template<typename T , size_t list_size = 16> T & fixedlist< T, list_size >::operator[] (size_t i) inline
Definition at line 58 of file fixedlist.hpp.
Replace()
template<typename T , size_t list_size = 16> bool fixedlist< T, list_size >::Replace (size_t i, const T & element) inline
Definition at line 172 of file fixedlist.hpp.
References fixedlist< T, list_size >::slot_used.
Size()
template<typename T , size_t list_size = 16> size_t fixedlist< T, list_size >::Size () const inline
Definition at line 53 of file fixedlist.hpp.
UpdateUnique()
template<typename T , size_t list_size = 16> bool fixedlist< T, list_size >::UpdateUnique (T const & element) inline
Definition at line 121 of file fixedlist.hpp.
References fixedlist< T, list_size >::Add(), and fixedlist< T, list_size >::Find().
Used()
template<typename T , size_t list_size = 16> bool fixedlist< T, list_size >::Used (const size_t i) const inline
Definition at line 69 of file fixedlist.hpp.
References fixedlist< T, list_size >::slot_used.
Member Data Documentation
slot_used
template<typename T , size_t list_size = 16> bool fixedlist< T, list_size >::slot_used[list_size] private
Definition at line 36 of file fixedlist.hpp.
Referenced by fixedlist< T, list_size >::Add(), fixedlist< T, list_size >::Clear(), fixedlist< T, list_size >::Delete(), fixedlist< T, list_size >::Delete(), fixedlist< T, list_size >::Find(), fixedlist< T, list_size >::Get(), fixedlist< T, list_size >::Len(), fixedlist< T, list_size >::Replace(), and fixedlist< T, list_size >::Used().
The documentation for this class was generated from the following file:
fixedlist.hpp