ESC FilterWheel C++ Source: fixedlistlite< T, list_size > Class Template Reference
fixedlistlite< T, list_size > Class Template Reference
Copyright (c) by Franks Development, LLC.
#include <fixedlistlite.hpp>
Public Member Functions
fixedlistlite ()
size_t Max () const
T * Data ()
T & operator[] (size_t i)
size_t Len ()
void Clear ()
bool Get (size_t i, T &element) const
bool Add (T const &element)
T const & operator+= (T const &element)
Private Member Functions
T data[list_size] __attribute__ ((aligned(4)))
Private Attributes
size_t len
Detailed Description
template<typename T, size_t list_size = 16>
class fixedlistlite< T, list_size >
Copyright (c) by Franks Development, LLC.
Definition at line 31 of file fixedlistlite.hpp.
Constructor & Destructor Documentation
fixedlistlite()
template<typename T , size_t list_size = 16> fixedlistlite< T, list_size >::fixedlistlite () inline
Definition at line 40 of file fixedlistlite.hpp.
References fixedlistlite< T, list_size >::Clear().
Member Function Documentation
__attribute__()
template<typename T , size_t list_size = 16> T data[list_size] fixedlistlite< T, list_size >::__attribute__ ((aligned(4))) private
Add()
template<typename T , size_t list_size = 16> bool fixedlistlite< T, list_size >::Add (T const & element) inline
Definition at line 69 of file fixedlistlite.hpp.
References fixedlistlite< T, list_size >::len.
Referenced by fixedlistlite< T, list_size >::operator+=().
Clear()
template<typename T , size_t list_size = 16> void fixedlistlite< T, list_size >::Clear () inline
Definition at line 54 of file fixedlistlite.hpp.
References fixedlistlite< T, list_size >::len.
Referenced by fixedlistlite< T, list_size >::fixedlistlite().
Data()
template<typename T , size_t list_size = 16> T * fixedlistlite< T, list_size >::Data () inline
Definition at line 47 of file fixedlistlite.hpp.
Get()
template<typename T , size_t list_size = 16> bool fixedlistlite< T, list_size >::Get (size_t i, T & element) const inline
Definition at line 56 of file fixedlistlite.hpp.
References fixedlistlite< T, list_size >::len.
Len()
template<typename T , size_t list_size = 16> size_t fixedlistlite< T, list_size >::Len () inline
Definition at line 52 of file fixedlistlite.hpp.
References fixedlistlite< T, list_size >::len.
Max()
template<typename T , size_t list_size = 16> size_t fixedlistlite< T, list_size >::Max () const inline
Definition at line 45 of file fixedlistlite.hpp.
operator+=()
template<typename T , size_t list_size = 16> T const & fixedlistlite< T, list_size >::operator+= (T const & element) inline
Definition at line 80 of file fixedlistlite.hpp.
References fixedlistlite< T, list_size >::Add().
operator[]()
template<typename T , size_t list_size = 16> T & fixedlistlite< T, list_size >::operator[] (size_t i) inline
Definition at line 50 of file fixedlistlite.hpp.
References fixedlistlite< T, list_size >::len.
Member Data Documentation
len
template<typename T , size_t list_size = 16> size_t fixedlistlite< T, list_size >::len private
Definition at line 36 of file fixedlistlite.hpp.
Referenced by fixedlistlite< T, list_size >::Add(), fixedlistlite< T, list_size >::Clear(), fixedlistlite< T, list_size >::Get(), fixedlistlite< T, list_size >::Len(), and fixedlistlite< T, list_size >::operator[]().
The documentation for this class was generated from the following file:
fixedlistlite.hpp