ESC FilterWheel C++ Source: fixedqueue< T, queue_size > Class Template Reference
fixedqueue< T, queue_size > Class Template Reference
Copyright (c) by Franks Development, LLC.
#include <fixedqueue.hpp>
Public Member Functions
fixedqueue ()
bool empty () const
bool full () const
size_t max () const
size_t len () const
void clear ()
T const & front () const
T const & back () const
bool pop (T &element)
bool push (T const &element)
Private Member Functions
T data[queue_size] __attribute__ ((aligned(4)))
size_t next (const size_t in) const
Private Attributes
size_t volatile begin
size_t volatile end
Detailed Description
template<typename T, size_t queue_size>
class fixedqueue< T, queue_size >
Copyright (c) by Franks Development, LLC.
Definition at line 31 of file fixedqueue.hpp.
Constructor & Destructor Documentation
fixedqueue()
template<typename T , size_t queue_size> fixedqueue< T, queue_size >::fixedqueue () inline
Definition at line 51 of file fixedqueue.hpp.
Member Function Documentation
__attribute__()
template<typename T , size_t queue_size> T data[queue_size] fixedqueue< T, queue_size >::__attribute__ ((aligned(4))) private
back()
template<typename T , size_t queue_size> T const & fixedqueue< T, queue_size >::back () const inline
Definition at line 72 of file fixedqueue.hpp.
References fixedqueue< T, queue_size >::end.
clear()
template<typename T , size_t queue_size> void fixedqueue< T, queue_size >::clear () inline
Definition at line 70 of file fixedqueue.hpp.
References fixedqueue< T, queue_size >::begin, and fixedqueue< T, queue_size >::end.
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::Init().
empty()
template<typename T , size_t queue_size> bool fixedqueue< T, queue_size >::empty () const inline
Definition at line 53 of file fixedqueue.hpp.
References fixedqueue< T, queue_size >::begin, and fixedqueue< T, queue_size >::end.
Referenced by fixedqueue< T, queue_size >::pop(), and TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessTx().
front()
template<typename T , size_t queue_size> T const & fixedqueue< T, queue_size >::front () const inline
Definition at line 71 of file fixedqueue.hpp.
References fixedqueue< T, queue_size >::begin.
full()
template<typename T , size_t queue_size> bool fixedqueue< T, queue_size >::full () const inline
Definition at line 55 of file fixedqueue.hpp.
References fixedqueue< T, queue_size >::begin, fixedqueue< T, queue_size >::end, and fixedqueue< T, queue_size >::next().
Referenced by fixedqueue< T, queue_size >::push().
len()
template<typename T , size_t queue_size> size_t fixedqueue< T, queue_size >::len () const inline
Definition at line 61 of file fixedqueue.hpp.
References fixedqueue< T, queue_size >::begin, and fixedqueue< T, queue_size >::end.
max()
template<typename T , size_t queue_size> size_t fixedqueue< T, queue_size >::max () const inline
Definition at line 59 of file fixedqueue.hpp.
next()
template<typename T , size_t queue_size> size_t fixedqueue< T, queue_size >::next (const size_t in) const inline private
Definition at line 40 of file fixedqueue.hpp.
Referenced by fixedqueue< T, queue_size >::full(), fixedqueue< T, queue_size >::pop(), and fixedqueue< T, queue_size >::push().
pop()
template<typename T , size_t queue_size> bool fixedqueue< T, queue_size >::pop (T & element) inline
Definition at line 74 of file fixedqueue.hpp.
References fixedqueue< T, queue_size >::begin, fixedqueue< T, queue_size >::empty(), and fixedqueue< T, queue_size >::next().
Referenced by TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessTx().
push()
template<typename T , size_t queue_size> bool fixedqueue< T, queue_size >::push (T const & element) inline
Definition at line 82 of file fixedqueue.hpp.
References fixedqueue< T, queue_size >::end, fixedqueue< T, queue_size >::full(), and fixedqueue< T, queue_size >::next().
Member Data Documentation
begin
template<typename T , size_t queue_size> size_t volatile fixedqueue< T, queue_size >::begin private
Definition at line 37 of file fixedqueue.hpp.
Referenced by fixedqueue< T, queue_size >::clear(), fixedqueue< T, queue_size >::empty(), fixedqueue< T, queue_size >::front(), fixedqueue< T, queue_size >::full(), fixedqueue< T, queue_size >::len(), and fixedqueue< T, queue_size >::pop().
end
template<typename T , size_t queue_size> size_t volatile fixedqueue< T, queue_size >::end private
Definition at line 38 of file fixedqueue.hpp.
Referenced by fixedqueue< T, queue_size >::back(), fixedqueue< T, queue_size >::clear(), fixedqueue< T, queue_size >::empty(), fixedqueue< T, queue_size >::full(), fixedqueue< T, queue_size >::len(), and fixedqueue< T, queue_size >::push().
The documentation for this class was generated from the following file:
fixedqueue.hpp