ESC FilterWheel C++ Source: CGraphPacket Class Reference
CGraphPacket Class Reference
#include <CGraphPacket.hpp>
Public Member Functions
CGraphPacket ()
virtual ~CGraphPacket ()
virtual bool FindPacketStartPos (const uint8_t *Buffer, const size_t BufferLen, size_t &Offset) const override
virtual bool FindPacketEndPos (const uint8_t *Buffer, const size_t BufferLen, size_t &Offset) const override
virtual bool FindPacketStartPos (const uint8_t *Buffer, const size_t BufferLen, const size_t SearchStartPos, size_t &Offset) const override
virtual bool FindPacketEndPos (const uint8_t *Buffer, const size_t BufferLen, const size_t SearchStartPos, size_t &Offset) const override
virtual size_t HeaderLen () const override
virtual size_t FooterLen () const override
virtual size_t EndTokenLen () const override
virtual size_t PayloadOffset () const override
virtual size_t MaxPayloadLength () const override
virtual bool IsBroadcastSerialNum (const uint8_t *Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const override
virtual uint64_t SerialNum (const uint8_t *Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const override
virtual size_t PayloadLen (const uint8_t *Buffer, const size_t BufferCount, const size_t PacketStartPos) const override
virtual uint64_t PayloadType (const uint8_t *Buffer, const size_t BufferCount, const size_t PacketStartPos) const override
virtual bool DoesPayloadTypeMatch (const uint8_t *Buffer, const size_t BufferCount, const size_t PacketStartPos, const size_t PacketEndPos, const uint32_t CmdType) const override
virtual bool IsValid (const uint8_t *Buffer, const size_t BufferCount, const size_t PacketStartPos, const size_t PacketEndPos) const override
virtual size_t MakePacket (uint8_t *Buffer, const size_t BufferCount, const void *Payload, const uint16_t PayloadType, const size_t PayloadLen) const override
virtual bool FindPacketStartPos (const IArray &Buffer, const size_t SearchStartPos, size_t &Offset) const override
virtual bool ReverseFindPacketStartPos (const IArray &Buffer, const size_t SearchEndPos, size_t &Offset) const override
virtual bool FindPacketEndPos (const IArray &Buffer, const size_t SearchStartPos, size_t &Offset) const override
virtual size_t PayloadLen (const IArray &Buffer, const size_t PacketStartPos) const override
virtual bool IsValid (const IArray &Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const override
virtual bool IsBroadcastSerialNum (const IArray &Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const override
virtual uint64_t SerialNum (const IArray &Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const override
virtual uint64_t PayloadType (const IArray &Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const override
virtual bool DoesPayloadTypeMatch (const IArray &Buffer, const size_t PacketStartPos, const size_t PacketEndPos, const uint32_t CmdType) const override
Public Member Functions inherited from IPacket
IPacket ()
virtual ~IPacket ()
Detailed Description
Definition at line 66 of file CGraphPacket.hpp.
Constructor & Destructor Documentation
CGraphPacket()
CGraphPacket::CGraphPacket () inline
Definition at line 69 of file CGraphPacket.hpp.
~CGraphPacket()
virtual CGraphPacket::~CGraphPacket () inline virtual
Definition at line 70 of file CGraphPacket.hpp.
Member Function Documentation
DoesPayloadTypeMatch() [1/2]
virtual bool CGraphPacket::DoesPayloadTypeMatch (const IArray & Buffer, const size_t PacketStartPos, const size_t PacketEndPos, const uint32_t CmdType) const inline override virtual
Implements IPacket.
Definition at line 381 of file CGraphPacket.hpp.
References IArray::asU16(), IArray::Depth(), and PayloadType.
DoesPayloadTypeMatch() [2/2]
virtual bool CGraphPacket::DoesPayloadTypeMatch (const uint8_t * Buffer, const size_t BufferCount, const size_t PacketStartPos, const size_t PacketEndPos, const uint32_t CmdType) const inline override virtual
Implements IPacket.
Definition at line 186 of file CGraphPacket.hpp.
References CGraphPacketHeader::PayloadType.
EndTokenLen()
virtual size_t CGraphPacket::EndTokenLen () const inline override virtual
Implements IPacket.
Definition at line 145 of file CGraphPacket.hpp.
References CGraphPacketFooter::PacketEndToken.
FindPacketEndPos() [1/3]
virtual bool CGraphPacket::FindPacketEndPos (const IArray & Buffer, const size_t SearchStartPos, size_t & Offset) const inline override virtual
Implements IPacket.
Definition at line 279 of file CGraphPacket.hpp.
References IArray::asU32(), CGraphMagikPacketEndToken, and IArray::Depth().
FindPacketEndPos() [2/3]
virtual bool CGraphPacket::FindPacketEndPos (const uint8_t * Buffer, const size_t BufferLen, const size_t SearchStartPos, size_t & Offset) const inline override virtual
Implements IPacket.
Definition at line 124 of file CGraphPacket.hpp.
References CGraphMagikPacketEndToken.
FindPacketEndPos() [3/3]
virtual bool CGraphPacket::FindPacketEndPos (const uint8_t * Buffer, const size_t BufferLen, size_t & Offset) const inline override virtual
Implements IPacket.
Definition at line 100 of file CGraphPacket.hpp.
References CGraphMagikPacketEndToken.
FindPacketStartPos() [1/3]
virtual bool CGraphPacket::FindPacketStartPos (const IArray & Buffer, const size_t SearchStartPos, size_t & Offset) const inline override virtual
Implements IPacket.
Definition at line 251 of file CGraphPacket.hpp.
References IArray::asU32(), CGraphMagikPacketStartToken, and IArray::Depth().
FindPacketStartPos() [2/3]
virtual bool CGraphPacket::FindPacketStartPos (const uint8_t * Buffer, const size_t BufferLen, const size_t SearchStartPos, size_t & Offset) const inline override virtual
Implements IPacket.
Definition at line 111 of file CGraphPacket.hpp.
References CGraphMagikPacketStartToken.
FindPacketStartPos() [3/3]
virtual bool CGraphPacket::FindPacketStartPos (const uint8_t * Buffer, const size_t BufferLen, size_t & Offset) const inline override virtual
Implements IPacket.
Definition at line 72 of file CGraphPacket.hpp.
References CGraphMagikPacketStartToken.
FooterLen()
virtual size_t CGraphPacket::FooterLen () const inline override virtual
Implements IPacket.
Definition at line 141 of file CGraphPacket.hpp.
HeaderLen()
virtual size_t CGraphPacket::HeaderLen () const inline override virtual
Implements IPacket.
Definition at line 137 of file CGraphPacket.hpp.
IsBroadcastSerialNum() [1/2]
virtual bool CGraphPacket::IsBroadcastSerialNum (const IArray & Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const inline override virtual
Implements IPacket.
Definition at line 360 of file CGraphPacket.hpp.
IsBroadcastSerialNum() [2/2]
virtual bool CGraphPacket::IsBroadcastSerialNum (const uint8_t * Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const inline override virtual
Implements IPacket.
Definition at line 157 of file CGraphPacket.hpp.
IsValid() [1/2]
virtual bool CGraphPacket::IsValid (const IArray & Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const inline override virtual
Implements IPacket.
Definition at line 308 of file CGraphPacket.hpp.
References IArray::asU16(), IArray::asU32(), CGraphMagikPacketEndToken, CGraphMagikPacketStartToken, IArray::CopyToFlatBuffer(), CRC32BZIP2, IArray::Depth(), formatf(), PacketEndToken, PacketStartToken, PayloadLen, and PayloadType.
IsValid() [2/2]
virtual bool CGraphPacket::IsValid (const uint8_t * Buffer, const size_t BufferCount, const size_t PacketStartPos, const size_t PacketEndPos) const inline override virtual
Implements IPacket.
Definition at line 202 of file CGraphPacket.hpp.
References CGraphMagikPacketEndToken, CGraphMagikPacketStartToken, CRC32BZIP2, CGraphPacketFooter::CRC32BZIP2, CGraphPacketFooter::PacketEndToken, CGraphPacketHeader::PacketStartToken, and CGraphPacketHeader::PayloadLen.
MakePacket()
virtual size_t CGraphPacket::MakePacket (uint8_t * Buffer, const size_t BufferCount, const void * Payload, const uint16_t PayloadType, const size_t PayloadLen) const inline override virtual
Implements IPacket.
Definition at line 230 of file CGraphPacket.hpp.
References CGraphMagikPacketEndToken, CRC32BZIP2, CGraphPacketFooter::CRC32BZIP2, CGraphPacketFooter::PacketEndToken, PayloadLen, CGraphPacketHeader::PayloadLen, PayloadType, and CGraphPacketHeader::PayloadType.
MaxPayloadLength()
virtual size_t CGraphPacket::MaxPayloadLength () const inline override virtual
Implements IPacket.
Definition at line 153 of file CGraphPacket.hpp.
PayloadLen() [1/2]
virtual size_t CGraphPacket::PayloadLen (const IArray & Buffer, const size_t PacketStartPos) const inline override virtual
Implements IPacket.
Definition at line 294 of file CGraphPacket.hpp.
References IArray::asU16(), IArray::Depth(), and PayloadLen.
PayloadLen() [2/2]
virtual size_t CGraphPacket::PayloadLen (const uint8_t * Buffer, const size_t BufferCount, const size_t PacketStartPos) const inline override virtual
Implements IPacket.
Definition at line 166 of file CGraphPacket.hpp.
References CGraphPacketHeader::PayloadLen.
PayloadOffset()
virtual size_t CGraphPacket::PayloadOffset () const inline override virtual
Implements IPacket.
Definition at line 149 of file CGraphPacket.hpp.
PayloadType() [1/2]
virtual uint64_t CGraphPacket::PayloadType (const IArray & Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const inline override virtual
Implements IPacket.
Definition at line 369 of file CGraphPacket.hpp.
References IArray::asU16(), IArray::Depth(), and PayloadType.
PayloadType() [2/2]
virtual uint64_t CGraphPacket::PayloadType (const uint8_t * Buffer, const size_t BufferCount, const size_t PacketStartPos) const inline override virtual
Implements IPacket.
Definition at line 176 of file CGraphPacket.hpp.
References CGraphPacketHeader::PayloadType.
ReverseFindPacketStartPos()
virtual bool CGraphPacket::ReverseFindPacketStartPos (const IArray & Buffer, const size_t SearchEndPos, size_t & Offset) const inline override virtual
Implements IPacket.
Definition at line 264 of file CGraphPacket.hpp.
References IArray::asU32(), and CGraphMagikPacketStartToken.
SerialNum() [1/2]
virtual uint64_t CGraphPacket::SerialNum (const IArray & Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const inline override virtual
Implements IPacket.
Definition at line 364 of file CGraphPacket.hpp.
SerialNum() [2/2]
virtual uint64_t CGraphPacket::SerialNum (const uint8_t * Buffer, const size_t PacketStartPos, const size_t PacketEndPos) const inline override virtual
Implements IPacket.
Definition at line 161 of file CGraphPacket.hpp.
The documentation for this class was generated from the following file:
CGraphPacket.hpp