ESC FilterWheel C++ Source: IArray Class Reference
IArray Class Reference abstract
Copyright (c) by Franks Development, LLC.
#include <IArray.hpp>
Public Member Functions
IArray ()
virtual ~IArray ()
virtual uint8_t operator[] (const size_t offset) const =0
virtual uint8_t peek (const size_t offset) const =0
virtual uint16_t asU16 (const size_t offset) const =0
virtual uint32_t asU32 (const size_t offset) const =0
virtual size_t Depth () const =0
virtual size_t CopyToFlatBuffer (const size_t StartOffset, size_t &NumToCopy, uint8_t *const Buffer, const size_t BufferMaxLen) const =0
virtual void PopMany (const size_t LastReadAddrToPop)=0
Detailed Description
Copyright (c) by Franks Development, LLC.
Definition at line 31 of file IArray.hpp.
Constructor & Destructor Documentation
IArray()
IArray::IArray () inline
Definition at line 34 of file IArray.hpp.
~IArray()
virtual IArray::~IArray () inline virtual
Definition at line 35 of file IArray.hpp.
Member Function Documentation
asU16()
virtual uint16_t IArray::asU16 (const size_t offset) const pure virtual
Referenced by CGraphPacket::DoesPayloadTypeMatch(), CGraphPacket::IsValid(), CGraphPacket::PayloadLen(), and CGraphPacket::PayloadType().
asU32()
virtual uint32_t IArray::asU32 (const size_t offset) const pure virtual
Referenced by CGraphPacket::FindPacketEndPos(), CGraphPacket::FindPacketStartPos(), CGraphPacket::IsValid(), and CGraphPacket::ReverseFindPacketStartPos().
CopyToFlatBuffer()
virtual size_t IArray::CopyToFlatBuffer (const size_t StartOffset, size_t & NumToCopy, uint8_t *const Buffer, const size_t BufferMaxLen) const pure virtual
Referenced by BinaryUartRingBuffer::Process().
Depth()
virtual size_t IArray::Depth () const pure virtual
Referenced by CGraphPacket::DoesPayloadTypeMatch(), CGraphPacket::FindPacketEndPos(), CGraphPacket::FindPacketStartPos(), CGraphPacket::IsValid(), CGraphPacket::PayloadLen(), CGraphPacket::PayloadType(), and BinaryUartRingBuffer::Process().
operator[]()
virtual uint8_t IArray::operator[] (const size_t offset) const pure virtual
peek()
virtual uint8_t IArray::peek (const size_t offset) const pure virtual
PopMany()
virtual void IArray::PopMany (const size_t LastReadAddrToPop) pure virtual
Referenced by BinaryUartRingBuffer::Process().
The documentation for this class was generated from the following file:
IArray.hpp