ESC FilterWheel C++ Source: CmdSystem.cpp File Reference
CmdSystem.cpp File Reference
#include <string.h>
#include <stdio.h>
#include <stdint.h>
#include "format/formatf.h"
#include "CmdSystem.hpp"
Functions
bool ParseCmd (const char *LineIn, const unsigned int LineLen, const Cmd *Cmds, const size_t NumCmds, const bool Quiet, const char *Prefix, const unsigned int PrefixLen, const bool Binary, const void *Argument)
The function to locate and execute a command from a line of text.
void HelpCmds (const Cmd *Cmds, const size_t NumCmds)
Variables
const size_t MaxCmdNameLen = 32
Copyright (c) by Franks Development, LLC.
static char LineInUpperCase [MaxCmdNameLen]
Function Documentation
HelpCmds()
void HelpCmds (const Cmd * Cmds, const size_t NumCmds)
Definition at line 148 of file CmdSystem.cpp.
References formatf().
Referenced by ParseCmd().
ParseCmd()
bool ParseCmd (const char * LineIn, const unsigned int LineLen, const Cmd * Cmds, const size_t NumCmds, const bool Quiet, const char * Prefix, const unsigned int PrefixLen, const bool Binary, const void * Argument)
The function to locate and execute a command from a line of text.
Definition at line 44 of file CmdSystem.cpp.
References formatf(), HelpCmds(), LineInUpperCase, MaxCmdNameLen, Cmd::Response, and Cmd::Strlen.
Referenced by ParseConfigFile(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessRx(), and ProcessUserInterface().
Variable Documentation
LineInUpperCase
char LineInUpperCase[MaxCmdNameLen] static
Definition at line 41 of file CmdSystem.cpp.
Referenced by ParseCmd().
MaxCmdNameLen
const size_t MaxCmdNameLen = 32
Copyright (c) by Franks Development, LLC.
Definition at line 39 of file CmdSystem.cpp.
Referenced by ParseCmd().