ESC FilterWheel C++ Source: CmdSystem.hpp File Reference
CmdSystem.hpp File Reference
#include <stdint.h>
#include <string.h>
#include <stdio.h>
Classes
struct Cmd
Copyright (c) by Franks Development, LLC.
struct BinaryCmd
everything we need to know about a command, in a format that allows us to declare them sequentially in a file
Functions
bool ParseCmd (const char *LineIn, const unsigned int LineLen, const Cmd *Cmds, const size_t NumCmds, const bool Quiet=false, const char *Prefix=(const char *)(0), const unsigned int PrefixLen=0, const bool Binary=false, const void *Argument=0)
The function to locate and execute a command from a line of text.
bool ParseBinaryCmd (const char *LineIn, const unsigned int LineLen, const BinaryCmd *Cmds, const size_t NumCmds, const bool Quiet=false, const char *Prefix=(const char *)(0), const unsigned int PrefixLen=0, const bool Binary=false, const void *Argument=0)
void HelpCmds (const Cmd *Cmds, const size_t NumCmds)
Function Documentation
HelpCmds()
void HelpCmds (const Cmd * Cmds, const size_t NumCmds)
Definition at line 148 of file CmdSystem.cpp.
References formatf().
Referenced by ParseCmd().
ParseBinaryCmd()
bool ParseBinaryCmd (const char * LineIn, const unsigned int LineLen, const BinaryCmd * Cmds, const size_t NumCmds, const bool Quiet = false, const char * Prefix = (const char *)(0), const unsigned int PrefixLen = 0, const bool Binary = false, const void * Argument = 0)
ParseCmd()
bool ParseCmd (const char * LineIn, const unsigned int LineLen, const Cmd * Cmds, const size_t NumCmds, const bool Quiet = false, const char * Prefix = (const char *)(0), const unsigned int PrefixLen = 0, const bool Binary = false, const void * Argument = 0)
The function to locate and execute a command from a line of text.
Definition at line 44 of file CmdSystem.cpp.
References formatf(), HelpCmds(), LineInUpperCase, MaxCmdNameLen, Cmd::Response, and Cmd::Strlen.
Referenced by ParseConfigFile(), TerminalUart< txbufferlenbytes, rxbufferlenbytes >::ProcessRx(), and ProcessUserInterface().