ESC FilterWheel C++ Source: lt244xdetails Namespace Reference
lt244xdetails Namespace Reference
Copyright (c) by Franks Development, LLC.
Classes
union channel
union configregister
union lt244x_sample
Functions
union lt244xdetails::channel __attribute__ ((__packed__))
Variables
static const int32_t CountPosVRef = 0x1FFFFFFF
static const int32_t CountZero = 0x000000UL
static const int32_t CountNegVRef = (int32_t)0xE0000000UL
static const uint8_t DataRateNoChange = 0x00
static const uint8_t DataRateFClkDiv64 = 0x01
static const uint8_t DataRateFClkDiv128 = 0x02
static const uint8_t DataRateFClkDiv256 = 0x03
static const uint8_t DataRateFClkDiv512 = 0x04
static const uint8_t DataRateFClkDiv1024 = 0x05
static const uint8_t DataRateFClkDiv2048 = 0x06
static const uint8_t DataRateFClkDiv4096 = 0x07
static const uint8_t DataRateFClkDiv8192 = 0x08
static const uint8_t DataRateFClkDiv16384 = 0x09
static const uint8_t DataRateFClkDiv32768_60Hz50HzNull = 0x0F
Detailed Description
Copyright (c) by Franks Development, LLC.
Function Documentation
__attribute__()
union lt244xdetails::lt244x_sample lt244xdetails::__attribute__ ((__packed__))
Variable Documentation
CountNegVRef
const int32_t lt244xdetails::CountNegVRef = (int32_t)0xE0000000UL static
Definition at line 41 of file lt244x.h.
Referenced by Ltc244xAccumulator::CountsToVolts(), lt244x< pinout, spi, SpiClkDiv >::CountsToVolts(), lt244x_accum< pinout >::CountsToVolts(), lt244x< pinout, spi, SpiClkDiv >::CountsToVolts(), lt244x_accum< pinout >::CountsToVolts(), lt244xdetails::lt244x_sample::CountsToVolts(), and lt244x_accum< pinout >::CountsToVolts().
CountPosVRef
const int32_t lt244xdetails::CountPosVRef = 0x1FFFFFFF static
Definition at line 39 of file lt244x.h.
Referenced by Ltc244xAccumulator::CountsToVolts(), lt244x< pinout, spi, SpiClkDiv >::CountsToVolts(), lt244x_accum< pinout >::CountsToVolts(), lt244x< pinout, spi, SpiClkDiv >::CountsToVolts(), lt244x_accum< pinout >::CountsToVolts(), lt244xdetails::lt244x_sample::CountsToVolts(), and lt244x_accum< pinout >::CountsToVolts().
CountZero
const int32_t lt244xdetails::CountZero = 0x000000UL static
Definition at line 40 of file lt244x.h.
DataRateFClkDiv1024
const uint8_t lt244xdetails::DataRateFClkDiv1024 = 0x05 static
Definition at line 68 of file lt244x.h.
DataRateFClkDiv128
const uint8_t lt244xdetails::DataRateFClkDiv128 = 0x02 static
Definition at line 65 of file lt244x.h.
DataRateFClkDiv16384
const uint8_t lt244xdetails::DataRateFClkDiv16384 = 0x09 static
Definition at line 72 of file lt244x.h.
DataRateFClkDiv2048
const uint8_t lt244xdetails::DataRateFClkDiv2048 = 0x06 static
Definition at line 69 of file lt244x.h.
DataRateFClkDiv256
const uint8_t lt244xdetails::DataRateFClkDiv256 = 0x03 static
Definition at line 66 of file lt244x.h.
DataRateFClkDiv32768_60Hz50HzNull
const uint8_t lt244xdetails::DataRateFClkDiv32768_60Hz50HzNull = 0x0F static
Definition at line 73 of file lt244x.h.
Referenced by lt244xdetails::configregister::configregister().
DataRateFClkDiv4096
const uint8_t lt244xdetails::DataRateFClkDiv4096 = 0x07 static
Definition at line 70 of file lt244x.h.
DataRateFClkDiv512
const uint8_t lt244xdetails::DataRateFClkDiv512 = 0x04 static
Definition at line 67 of file lt244x.h.
DataRateFClkDiv64
const uint8_t lt244xdetails::DataRateFClkDiv64 = 0x01 static
Definition at line 64 of file lt244x.h.
DataRateFClkDiv8192
const uint8_t lt244xdetails::DataRateFClkDiv8192 = 0x08 static
Definition at line 71 of file lt244x.h.
DataRateNoChange
const uint8_t lt244xdetails::DataRateNoChange = 0x00 static
Definition at line 63 of file lt244x.h.