ESC FilterWheel C++ Source: BinaryUart Struct Reference
BinaryUart Struct Reference
#include <BinaryUart.hpp>
Public Member Functions
BinaryUart (struct IUart &pinout, struct IPacket &packet, const BinaryCmd *cmds, const size_t numcmds, struct BinaryUartCallbacks &callbacks, const bool verbose=true, const uint64_t serialnum=InvalidSerialNumber)
Constructs a BinaryUart object and initializes with given parameters.
void Debug (bool dbg)
int Init (uint64_t serialnum)
Initializes the BinaryUart.
int InitFast (uint64_t serialnum)
bool Process () override
Processes incoming data and checks for new packets.
void ProcessByte (const char c)
Adds a byte to the Rx buffer and handles buffer overflow.
bool CheckPacketStart ()
Checks if a packet is present in the buffer.
bool CheckPacketEnd ()
Checks if a complete packet (with both header and footer) is present in the buffer.
virtual void TxBinaryPacket (const uint16_t PayloadType, const uint32_t SerialNumber, const void *PayloadData, const size_t PayloadLen) const
Transmit a binary packet over UART.
void formatf () const
BinaryUart (CircularFifoFlattened &data, struct IPacket &packet, struct IBlockDevice &pinout, const BinaryCmd *cmds, const size_t numcmds, struct BinaryUartCallbacks &callbacks, const bool verbose=true, const uint64_t serialnum=InvalidSerialNumber)
Constructs a BinaryUart object and initializes with given parameters.
void Debug (bool dbg)
int Init (uint64_t serialnum)
Initializes the BinaryUart.
int InitFast (uint64_t serialnum)
bool Process ()
Processes incoming data and checks for new packets.
virtual void TxBinaryPacket (const uint16_t PayloadType, const uint32_t SerialNumber, const void *PayloadData, const size_t PayloadLen) const
Transmit a binary packet over UART.
void formatf () const
Public Member Functions inherited from IUartParser
IUartParser (struct IUart &pinout)
virtual ~IUartParser ()
void puts (const char *s, const size_t len)
Public Attributes
size_t PacketEnd = 0
Position of the detected packet end.
uint8_t RxBuffer [RxBufferLenBytes]
Buffer to store received characters.
uint16_t RxCount
Number of bytes currently in RxBuffer.
IPacket & Packet
Packet structure for defining headers, footers, etc.
const BinaryCmd * Cmds
Array of commands.
size_t NumCmds
BinaryUartCallbacks & Callbacks
bool debug
bool InPacket
Whether a packet is currently being processed.
size_t PacketStart
size_t PacketLen
size_t PayloadLen
size_t HeaderLen
size_t FooterLen
uint64_t SerialNum
Serial number for validating received packets.
size_t PacketEndPos = 0
Position of the detected packet end.
CircularFifoFlattened & Data
IBlockDevice & Pinout
size_t PacketStartPos
uint32_t LastDataLen
uint32_t PacketSearchedPos
Public Attributes inherited from IUartParser
IUart & Pinout
Static Public Attributes
static const uint16_t RxCountInit = 0
Initial count for received bytes.
static const size_t PacketStartInit = 0
static const size_t PacketLenInit = 0
static const size_t PayloadLenInit = 0
static const size_t HeaderLenInit = 0
static const size_t FooterLenInit = 0
static const bool InPacketInit = false
Default in-packet status.
static const bool debugDefault = false
static const char EmptyBufferChar = '\0'
Character to fill empty buffer space.
static const size_t RxBufferLenBytes = 4096
static const size_t TxBufferLenBytes = 4096
static const uint64_t InvalidSerialNumber = 0xFFFFFFFFFFFFFFFFULL
static const uint16_t LastDataLenInit = 0
Initial count for received bytes.
static const size_t PacketStartPosInit = 0
Detailed Description
BinaryUart manages a UART interface for binary packet communication. It provides buffering for received bytes, detects packet boundaries, and processes commands within received packets.
Definition at line 61 of file BinaryUart.hpp.
Constructor & Destructor Documentation
BinaryUart() [1/2]
BinaryUart::BinaryUart (struct IUart & pinout, struct IPacket & packet, const BinaryCmd * cmds, const size_t numcmds, struct BinaryUartCallbacks & callbacks, const bool verbose = true, const uint64_t serialnum = InvalidSerialNumber) inline
Constructs a BinaryUart object and initializes with given parameters.
Parameters
pinout UART interface to use for receiving data.
packet Packet structure defining header, footer, and payload format.
cmds Array of available commands.
numcmds Number of commands in the cmds array.
callbacks Callback functions for handling packet events.
verbose Enable or disable verbose debug mode.
serialnum Optional initial serial number, defaulting to InvalidSerialNumber.
Definition at line 106 of file BinaryUart.hpp.
References Init().
BinaryUart() [2/2]
BinaryUart::BinaryUart (CircularFifoFlattened & data, struct IPacket & packet, struct IBlockDevice & pinout, const BinaryCmd * cmds, const size_t numcmds, struct BinaryUartCallbacks & callbacks, const bool verbose = true, const uint64_t serialnum = InvalidSerialNumber) inline
Constructs a BinaryUart object and initializes with given parameters.
Parameters
pinout UART interface to use for receiving data.
packet Packet structure defining header, footer, and payload format.
cmds Array of available commands.
numcmds Number of commands in the cmds array.
callbacks Callback functions for handling packet events.
verbose Enable or disable verbose debug mode.
serialnum Optional initial serial number, defaulting to InvalidSerialNumber.
Definition at line 110 of file BinaryUartRingBuffer.hpp.
References Init().
Member Function Documentation
CheckPacketEnd()
bool BinaryUart::CheckPacketEnd () inline
Checks if a complete packet (with both header and footer) is present in the buffer.
If a packet end is detected, verifies its validity and processes it. Handles incomplete or corrupted packets, and clears the buffer appropriately after processing.
Returns
bool Returns true if a packet was successfully processed, false otherwise.
Definition at line 289 of file BinaryUart.hpp.
References Callbacks, Cmds, debug, IPacket::DoesPayloadTypeMatch(), BinaryUartCallbacks::EveryPacket(), IPacket::FindPacketEndPos(), formatf(), HeaderLen, InitFast(), InPacket, BinaryUartCallbacks::InvalidPacket(), InvalidSerialNumber, IPacket::IsBroadcastSerialNum(), IPacket::IsValid(), BinaryCmd::Name, NumCmds, Packet, PacketEnd, PacketStart, PayloadLen, IPacket::PayloadType(), BinaryCmd::Response, RxBuffer, RxCount, SerialNum, IPacket::SerialNum(), and BinaryUartCallbacks::UnHandledPacket().
Referenced by Process().
CheckPacketStart()
bool BinaryUart::CheckPacketStart () inline
Checks if a packet is present in the buffer.
If a packet is detected, InPacket is set to true.
Definition at line 265 of file BinaryUart.hpp.
References IPacket::FindPacketStartPos(), IPacket::HeaderLen(), InPacket, Packet, PacketStart, RxBuffer, and RxCount.
Referenced by Process().
Debug() [1/2]
void BinaryUart::Debug (bool dbg) inline
Definition at line 130 of file BinaryUart.hpp.
References debug.
Debug() [2/2]
void BinaryUart::Debug (bool dbg) inline
Definition at line 136 of file BinaryUartRingBuffer.hpp.
References debug.
formatf() [1/2]
void BinaryUart::formatf () const inline
Definition at line 443 of file BinaryUart.hpp.
References formatf(), InPacket, PacketStart, RxBuffer, and RxCount.
Referenced by CheckPacketEnd(), formatf(), Init(), Process(), ProcessByte(), and TxBinaryPacket().
formatf() [2/2]
void BinaryUart::formatf () const inline
Definition at line 424 of file BinaryUartRingBuffer.hpp.
References Data, formatf(), InPacket, LastDataLen, and PacketStartPos.
Init() [1/2]
int BinaryUart::Init (uint64_t serialnum) inline
Initializes the BinaryUart.
Initializes the BinaryUart with the specified serial number and resets the Rx buffer and other internal states. Called upon construction and after buffer overflows or other packet error states.
Parameters
serialnum Serial number to initialize, used for packet validation.
Returns
int status code, 0 for success.
Definition at line 145 of file BinaryUart.hpp.
References debug, EmptyBufferChar, FooterLen, IPacket::FooterLen(), FooterLenInit, formatf(), HeaderLen, IPacket::HeaderLen(), HeaderLenInit, InPacket, InPacketInit, Packet, PacketLen, PacketLenInit, PacketStart, PacketStartInit, PayloadLen, PayloadLenInit, RxBuffer, RxBufferLenBytes, RxCount, RxCountInit, and SerialNum.
Referenced by BinaryUart(), BinaryUart(), and ProcessByte().
Init() [2/2]
int BinaryUart::Init (uint64_t serialnum) inline
Initializes the BinaryUart.
Initializes the BinaryUart with the specified serial number and resets the Rx buffer and other internal states. Called upon construction and after buffer overflows or other packet error states.
Parameters
serialnum Serial number to initialize, used for packet validation.
Returns
int status code, 0 for success.
Definition at line 151 of file BinaryUartRingBuffer.hpp.
References debug, FooterLen, IPacket::FooterLen(), FooterLenInit, formatf(), HeaderLen, IPacket::HeaderLen(), HeaderLenInit, InPacket, InPacketInit, LastDataLen, Packet, PacketLen, PacketLenInit, PacketSearchedPos, PacketStartPos, PacketStartPosInit, PayloadLen, PayloadLenInit, and SerialNum.
InitFast() [1/2]
int BinaryUart::InitFast (uint64_t serialnum) inline
Definition at line 162 of file BinaryUart.hpp.
References FooterLen, FooterLenInit, HeaderLen, HeaderLenInit, InPacket, InPacketInit, PacketLen, PacketLenInit, PacketStart, PacketStartInit, PayloadLen, PayloadLenInit, RxCount, RxCountInit, and SerialNum.
Referenced by CheckPacketEnd().
InitFast() [2/2]
int BinaryUart::InitFast (uint64_t serialnum) inline
Definition at line 173 of file BinaryUartRingBuffer.hpp.
References FooterLen, FooterLenInit, HeaderLen, HeaderLenInit, InPacket, InPacketInit, LastDataLen, PacketLen, PacketLenInit, PacketSearchedPos, PacketStartPos, PacketStartPosInit, PayloadLen, PayloadLenInit, and SerialNum.
Process() [1/2]
bool BinaryUart::Process () inline virtual
Processes incoming data and checks for new packets.
Reads a new character if available, adds it to the Rx buffer, and checks for packet boundaries (start and end).
Returns
bool Returns true if data was processed, false if no new data.
Implements IUartParser.
Definition at line 201 of file BinaryUartRingBuffer.hpp.
References Callbacks, Cmds, Data, debug, IPacket::DoesPayloadTypeMatch(), IPacket::EndTokenLen(), BinaryUartCallbacks::EveryPacket(), IPacket::FindPacketEndPos(), FooterLen, IPacket::FooterLen(), formatf(), HeaderLen, IPacket::HeaderLen(), BinaryUartCallbacks::InvalidPacket(), IPacket::IsValid(), LastDataLen, BinaryCmd::Name, NumCmds, Packet, PacketEndPos, PacketLen, PacketStartPos, PayloadLen, IPacket::PayloadLen(), IPacket::PayloadType(), BinaryCmd::Response, IPacket::ReverseFindPacketStartPos(), and BinaryUartCallbacks::UnHandledPacket().
Process() [2/2]
bool BinaryUart::Process () inline override virtual
Processes incoming data and checks for new packets.
Reads a new character if available, adds it to the Rx buffer, and checks for packet boundaries (start and end).
Returns
bool Returns true if data was processed, false if no new data.
Implements IUartParser.
Definition at line 187 of file BinaryUart.hpp.
References CheckPacketEnd(), CheckPacketStart(), FooterLen, IPacket::FooterLen(), HeaderLen, IPacket::HeaderLen(), InPacket, Packet, PacketStart, PayloadLen, IPacket::PayloadLen(), Pinout, ProcessByte(), RxBuffer, and RxCount.
ProcessByte()
void BinaryUart::ProcessByte (const char c) inline
Adds a byte to the Rx buffer and handles buffer overflow.
Parameters
c The character to add to the buffer.
Definition at line 239 of file BinaryUart.hpp.
References BinaryUartCallbacks::BufferOverflow(), Callbacks, debug, formatf(), Init(), RxBuffer, RxBufferLenBytes, RxCount, and SerialNum.
Referenced by Process().
TxBinaryPacket() [1/2]
virtual void BinaryUart::TxBinaryPacket (const uint16_t PayloadType, const uint32_t SerialNumber, const void * PayloadData, const size_t PayloadLen) const inline virtual
Transmit a binary packet over UART.
Constructs a binary packet using the specified payload type, serial number, and payload data, and transmits it byte-by-byte over UART.
Parameters
PayloadType The type identifier for the packet. This distinguishes different commands in the packet.
SerialNumber The unique serial number for this packet.
PayloadData A pointer to the data to be transmitted as the packet payload.
PayloadLen The length of the payload data in bytes.
< Temporary buffer to hold the constructed packet
< Build packet
Definition at line 426 of file BinaryUart.hpp.
References debug, formatf(), IPacket::MakePacket(), Packet, PayloadData(), PayloadLen, PayloadType, Pinout, and TxBufferLenBytes.
TxBinaryPacket() [2/2]
virtual void BinaryUart::TxBinaryPacket (const uint16_t PayloadType, const uint32_t SerialNumber, const void * PayloadData, const size_t PayloadLen) const inline virtual
Transmit a binary packet over UART.
Constructs a binary packet using the specified payload type, serial number, and payload data, and transmits it byte-by-byte over UART.
Parameters
PayloadType The type identifier for the packet. This distinguishes different commands in the packet.
SerialNumber The unique serial number for this packet.
PayloadData A pointer to the data to be transmitted as the packet payload.
PayloadLen The length of the payload data in bytes.
< Temporary buffer to hold the constructed packet
< Build packet
Definition at line 400 of file BinaryUartRingBuffer.hpp.
References debug, formatf(), IPacket::MakePacket(), Packet, PayloadData(), PayloadLen, PayloadType, Pinout, IBlockDevice::puts(), and TxBufferLenBytes.
Member Data Documentation
Callbacks
BinaryUartCallbacks & BinaryUart::Callbacks
Definition at line 85 of file BinaryUart.hpp.
Referenced by CheckPacketEnd(), Process(), and ProcessByte().
Cmds
const BinaryCmd * BinaryUart::Cmds
Array of commands.
Definition at line 83 of file BinaryUart.hpp.
Referenced by CheckPacketEnd(), and Process().
Data
CircularFifoFlattened& BinaryUart::Data
Definition at line 82 of file BinaryUartRingBuffer.hpp.
Referenced by formatf(), and Process().
debug
bool BinaryUart::debug
Definition at line 86 of file BinaryUart.hpp.
Referenced by CheckPacketEnd(), Debug(), Init(), Process(), ProcessByte(), and TxBinaryPacket().
debugDefault
static const bool BinaryUart::debugDefault = false static
Definition at line 71 of file BinaryUart.hpp.
EmptyBufferChar
static const char BinaryUart::EmptyBufferChar = '\0' static
Character to fill empty buffer space.
Definition at line 72 of file BinaryUart.hpp.
Referenced by Init().
FooterLen
size_t BinaryUart::FooterLen
Definition at line 92 of file BinaryUart.hpp.
Referenced by Init(), InitFast(), Process(), and Process().
FooterLenInit
static const size_t BinaryUart::FooterLenInit = 0 static
Definition at line 69 of file BinaryUart.hpp.
Referenced by Init(), and InitFast().
HeaderLen
size_t BinaryUart::HeaderLen
Definition at line 91 of file BinaryUart.hpp.
Referenced by CheckPacketEnd(), Init(), InitFast(), Process(), and Process().
HeaderLenInit
static const size_t BinaryUart::HeaderLenInit = 0 static
Definition at line 68 of file BinaryUart.hpp.
Referenced by Init(), and InitFast().
InPacket
bool BinaryUart::InPacket
Whether a packet is currently being processed.
Definition at line 87 of file BinaryUart.hpp.
Referenced by CheckPacketEnd(), CheckPacketStart(), formatf(), Init(), InitFast(), and Process().
InPacketInit
static const bool BinaryUart::InPacketInit = false static
Default in-packet status.
Definition at line 70 of file BinaryUart.hpp.
Referenced by Init(), and InitFast().
InvalidSerialNumber
static const uint64_t BinaryUart::InvalidSerialNumber = 0xFFFFFFFFFFFFFFFFULL static
Definition at line 75 of file BinaryUart.hpp.
Referenced by CheckPacketEnd().
LastDataLen
uint32_t BinaryUart::LastDataLen
Definition at line 96 of file BinaryUartRingBuffer.hpp.
Referenced by formatf(), Init(), InitFast(), and Process().
LastDataLenInit
const uint16_t BinaryUart::LastDataLenInit = 0 static
Initial count for received bytes.
Definition at line 66 of file BinaryUartRingBuffer.hpp.
NumCmds
size_t BinaryUart::NumCmds
Definition at line 84 of file BinaryUart.hpp.
Referenced by CheckPacketEnd(), and Process().
Packet
IPacket & BinaryUart::Packet
Packet structure for defining headers, footers, etc.
Definition at line 82 of file BinaryUart.hpp.
Referenced by CheckPacketEnd(), CheckPacketStart(), Init(), Process(), Process(), and TxBinaryPacket().
PacketEnd
size_t BinaryUart::PacketEnd = 0
Position of the detected packet end.
Definition at line 77 of file BinaryUart.hpp.
Referenced by CheckPacketEnd().
PacketEndPos
size_t BinaryUart::PacketEndPos = 0
Position of the detected packet end.
Definition at line 79 of file BinaryUartRingBuffer.hpp.
Referenced by Process().
PacketLen
size_t BinaryUart::PacketLen
Definition at line 89 of file BinaryUart.hpp.
Referenced by Init(), InitFast(), and Process().
PacketLenInit
static const size_t BinaryUart::PacketLenInit = 0 static
Definition at line 66 of file BinaryUart.hpp.
Referenced by Init(), and InitFast().
PacketSearchedPos
uint32_t BinaryUart::PacketSearchedPos
Definition at line 97 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), and InitFast().
PacketStart
size_t BinaryUart::PacketStart
Definition at line 88 of file BinaryUart.hpp.
Referenced by CheckPacketEnd(), CheckPacketStart(), formatf(), Init(), InitFast(), and Process().
PacketStartInit
const size_t BinaryUart::PacketStartInit = 0 static
Definition at line 65 of file BinaryUart.hpp.
Referenced by Init(), and InitFast().
PacketStartPos
size_t BinaryUart::PacketStartPos
Definition at line 90 of file BinaryUartRingBuffer.hpp.
Referenced by formatf(), Init(), InitFast(), and Process().
PacketStartPosInit
const size_t BinaryUart::PacketStartPosInit = 0 static
Definition at line 67 of file BinaryUartRingBuffer.hpp.
Referenced by Init(), and InitFast().
PayloadLen
size_t BinaryUart::PayloadLen
Definition at line 90 of file BinaryUart.hpp.
Referenced by CheckPacketEnd(), Init(), InitFast(), Process(), Process(), and TxBinaryPacket().
PayloadLenInit
static const size_t BinaryUart::PayloadLenInit = 0 static
Definition at line 67 of file BinaryUart.hpp.
Referenced by Init(), and InitFast().
Pinout
IBlockDevice& BinaryUart::Pinout
Definition at line 84 of file BinaryUartRingBuffer.hpp.
Referenced by Process(), and TxBinaryPacket().
RxBuffer
uint8_t BinaryUart::RxBuffer[RxBufferLenBytes]
Buffer to store received characters.
Definition at line 78 of file BinaryUart.hpp.
Referenced by CheckPacketEnd(), CheckPacketStart(), formatf(), Init(), Process(), and ProcessByte().
RxBufferLenBytes
const size_t BinaryUart::RxBufferLenBytes = 4096 static
Definition at line 73 of file BinaryUart.hpp.
Referenced by Init(), and ProcessByte().
RxCount
uint16_t BinaryUart::RxCount
Number of bytes currently in RxBuffer.
Definition at line 79 of file BinaryUart.hpp.
Referenced by CheckPacketEnd(), CheckPacketStart(), formatf(), Init(), InitFast(), Process(), and ProcessByte().
RxCountInit
const uint16_t BinaryUart::RxCountInit = 0 static
Initial count for received bytes.
Definition at line 64 of file BinaryUart.hpp.
Referenced by Init(), and InitFast().
SerialNum
uint64_t BinaryUart::SerialNum
Serial number for validating received packets.
Definition at line 93 of file BinaryUart.hpp.
Referenced by CheckPacketEnd(), Init(), InitFast(), and ProcessByte().
TxBufferLenBytes
static const size_t BinaryUart::TxBufferLenBytes = 4096 static
Definition at line 74 of file BinaryUart.hpp.
Referenced by TxBinaryPacket().
The documentation for this struct was generated from the following files:
BinaryUart.hpp
BinaryUartRingBuffer.hpp