ESC FilterWheel C++ Source: lt244x< pinout, spi, SpiClkDiv > Struct Template Reference
lt244x< pinout, spi, SpiClkDiv > Struct Template Reference
#include <lt244x.h>
Public Member Functions
lt244x (const double adcvref)
virtual ~lt244x ()
double CountsToVolts (const lt244xdetails::lt244x_sample &Counts) const
double CountsToVolts (const int32_t &Counts) const
bool StillConverting ()
void ReadChannel (const lt244xdetails::configregister &NewChannel, lt244xdetails::lt244x_sample &newsample)
void ReadChannel (const lt244xdetails::channel &NewChannel, lt244xdetails::lt244x_sample &newsample)
Public Attributes
const lt244xdetails::channel chan_diff0vs1
const lt244xdetails::channel chan_diff2vs3
const lt244xdetails::channel chan_diff4vs5
const lt244xdetails::channel chan_diff6vs7
const lt244xdetails::channel chan_diff8vs9
const lt244xdetails::channel chan_diff10vs11
const lt244xdetails::channel chan_diff12vs13
const lt244xdetails::channel chan_diff14vs15
const lt244xdetails::channel chan_diff1vs0
const lt244xdetails::channel chan_diff3vs2
const lt244xdetails::channel chan_diff5vs4
const lt244xdetails::channel chan_diff7vs6
const lt244xdetails::channel chan_diff9vs8
const lt244xdetails::channel chan_diff11vs10
const lt244xdetails::channel chan_diff13vs12
const lt244xdetails::channel chan_diff15vs14
const lt244xdetails::channel chan_se0
const lt244xdetails::channel chan_se1
const lt244xdetails::channel chan_se2
const lt244xdetails::channel chan_se3
const lt244xdetails::channel chan_se4
const lt244xdetails::channel chan_se5
const lt244xdetails::channel chan_se6
const lt244xdetails::channel chan_se7
const lt244xdetails::channel chan_se8
const lt244xdetails::channel chan_se9
const lt244xdetails::channel chan_se10
const lt244xdetails::channel chan_se11
const lt244xdetails::channel chan_se12
const lt244xdetails::channel chan_se13
const lt244xdetails::channel chan_se14
const lt244xdetails::channel chan_se15
Static Public Attributes
static const unsigned int WaitSlowestSampleTimeoutuS = 150000
static const unsigned int WaitFastestSampleTimeoutuS = 285
Private Member Functions
__inline__ void XferData (const lt244xdetails::configregister config_in, lt244xdetails::lt244x_sample &adcdata_out)
Private Attributes
const double AdcVRef
lt244xdetails::configregister LastChannelAndSamplingFreq
Detailed Description
template<class pinout, class spi, const uint8_t SpiClkDiv = 60>
struct lt244x< pinout, spi, SpiClkDiv >
Definition at line 162 of file lt244x.h.
Constructor & Destructor Documentation
lt244x()
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> lt244x< pinout, spi, SpiClkDiv >::lt244x (const double adcvref) inline
Definition at line 176 of file lt244x.h.
~lt244x()
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> virtual lt244x< pinout, spi, SpiClkDiv >::~lt244x () inline virtual
Definition at line 215 of file lt244x.h.
Member Function Documentation
CountsToVolts() [1/2]
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> double lt244x< pinout, spi, SpiClkDiv >::CountsToVolts (const int32_t & Counts) const inline
Definition at line 268 of file lt244x.h.
References lt244x< pinout, spi, SpiClkDiv >::AdcVRef, lt244xdetails::CountNegVRef, and lt244xdetails::CountPosVRef.
CountsToVolts() [2/2]
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> double lt244x< pinout, spi, SpiClkDiv >::CountsToVolts (const lt244xdetails::lt244x_sample & Counts) const inline
Definition at line 255 of file lt244x.h.
References lt244x< pinout, spi, SpiClkDiv >::AdcVRef, lt244xdetails::CountNegVRef, lt244xdetails::CountPosVRef, lt244xdetails::lt244x_sample::overrange(), lt244xdetails::lt244x_sample::sample, and lt244xdetails::lt244x_sample::underrange().
ReadChannel() [1/2]
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> void lt244x< pinout, spi, SpiClkDiv >::ReadChannel (const lt244xdetails::channel & NewChannel, lt244xdetails::lt244x_sample & newsample) inline
Definition at line 299 of file lt244x.h.
References delayus(), formatf(), lt244x< pinout, spi, SpiClkDiv >::LastChannelAndSamplingFreq, lt244xdetails::lt244x_sample::StillConverting, and lt244x< pinout, spi, SpiClkDiv >::XferData().
ReadChannel() [2/2]
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> void lt244x< pinout, spi, SpiClkDiv >::ReadChannel (const lt244xdetails::configregister & NewChannel, lt244xdetails::lt244x_sample & newsample) inline
Definition at line 288 of file lt244x.h.
References lt244xdetails::configregister::DataRate, delayus(), lt244x< pinout, spi, SpiClkDiv >::LastChannelAndSamplingFreq, lt244x< pinout, spi, SpiClkDiv >::WaitFastestSampleTimeoutuS, and lt244x< pinout, spi, SpiClkDiv >::XferData().
StillConverting()
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> bool lt244x< pinout, spi, SpiClkDiv >::StillConverting () inline
Definition at line 276 of file lt244x.h.
References delayus().
XferData()
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> __inline__ void lt244x< pinout, spi, SpiClkDiv >::XferData (const lt244xdetails::configregister config_in, lt244xdetails::lt244x_sample & adcdata_out) inline private
Definition at line 338 of file lt244x.h.
References lt244xdetails::configregister::bytes, lt244xdetails::lt244x_sample::bytes, and delayus().
Referenced by lt244x< pinout, spi, SpiClkDiv >::ReadChannel(), and lt244x< pinout, spi, SpiClkDiv >::ReadChannel().
Member Data Documentation
AdcVRef
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const double lt244x< pinout, spi, SpiClkDiv >::AdcVRef private
Definition at line 332 of file lt244x.h.
Referenced by lt244x< pinout, spi, SpiClkDiv >::CountsToVolts(), and lt244x< pinout, spi, SpiClkDiv >::CountsToVolts().
chan_diff0vs1
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff0vs1
Definition at line 222 of file lt244x.h.
chan_diff10vs11
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff10vs11
Definition at line 227 of file lt244x.h.
chan_diff11vs10
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff11vs10
Definition at line 235 of file lt244x.h.
chan_diff12vs13
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff12vs13
Definition at line 228 of file lt244x.h.
chan_diff13vs12
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff13vs12
Definition at line 236 of file lt244x.h.
chan_diff14vs15
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff14vs15
Definition at line 229 of file lt244x.h.
chan_diff15vs14
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff15vs14
Definition at line 237 of file lt244x.h.
chan_diff1vs0
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff1vs0
Definition at line 230 of file lt244x.h.
chan_diff2vs3
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff2vs3
Definition at line 223 of file lt244x.h.
chan_diff3vs2
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff3vs2
Definition at line 231 of file lt244x.h.
chan_diff4vs5
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff4vs5
Definition at line 224 of file lt244x.h.
chan_diff5vs4
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff5vs4
Definition at line 232 of file lt244x.h.
chan_diff6vs7
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff6vs7
Definition at line 225 of file lt244x.h.
chan_diff7vs6
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff7vs6
Definition at line 233 of file lt244x.h.
chan_diff8vs9
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff8vs9
Definition at line 226 of file lt244x.h.
chan_diff9vs8
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_diff9vs8
Definition at line 234 of file lt244x.h.
chan_se0
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se0
Definition at line 238 of file lt244x.h.
chan_se1
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se1
Definition at line 239 of file lt244x.h.
chan_se10
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se10
Definition at line 248 of file lt244x.h.
chan_se11
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se11
Definition at line 249 of file lt244x.h.
chan_se12
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se12
Definition at line 250 of file lt244x.h.
chan_se13
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se13
Definition at line 251 of file lt244x.h.
chan_se14
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se14
Definition at line 252 of file lt244x.h.
chan_se15
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se15
Definition at line 253 of file lt244x.h.
chan_se2
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se2
Definition at line 240 of file lt244x.h.
chan_se3
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se3
Definition at line 241 of file lt244x.h.
chan_se4
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se4
Definition at line 242 of file lt244x.h.
chan_se5
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se5
Definition at line 243 of file lt244x.h.
chan_se6
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se6
Definition at line 244 of file lt244x.h.
chan_se7
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se7
Definition at line 245 of file lt244x.h.
chan_se8
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se8
Definition at line 246 of file lt244x.h.
chan_se9
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const lt244xdetails::channel lt244x< pinout, spi, SpiClkDiv >::chan_se9
Definition at line 247 of file lt244x.h.
LastChannelAndSamplingFreq
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> lt244xdetails::configregister lt244x< pinout, spi, SpiClkDiv >::LastChannelAndSamplingFreq private
Definition at line 334 of file lt244x.h.
Referenced by lt244x< pinout, spi, SpiClkDiv >::ReadChannel(), and lt244x< pinout, spi, SpiClkDiv >::ReadChannel().
WaitFastestSampleTimeoutuS
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const unsigned int lt244x< pinout, spi, SpiClkDiv >::WaitFastestSampleTimeoutuS = 285 static
Definition at line 219 of file lt244x.h.
Referenced by lt244x< pinout, spi, SpiClkDiv >::ReadChannel().
WaitSlowestSampleTimeoutuS
template<class pinout , class spi , const uint8_t SpiClkDiv = 60> const unsigned int lt244x< pinout, spi, SpiClkDiv >::WaitSlowestSampleTimeoutuS = 150000 static
Definition at line 218 of file lt244x.h.
The documentation for this struct was generated from the following file:
lt244x.h