# Netlist Viewer TCL File
set_family -name SmartFusion2
top_module -name FineSteeringMirror
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/work/FCCC_C0/FCCC_C0_0/FCCC_C0_FCCC_C0_0_FCCC.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/work/FCCC_C0/FCCC_C0.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/work/FineSteeringMirror_sb/CCC_0/FineSteeringMirror_sb_CCC_0_FCCC.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/Actel/SgCore/OSC/2.0.101/osc_comps.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/work/FineSteeringMirror_sb/FABOSC_0/FineSteeringMirror_sb_FABOSC_0_OSC.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/work/FineSteeringMirror_sb_MSS/FineSteeringMirror_sb_MSS_syn.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/work/FineSteeringMirror_sb_MSS/FineSteeringMirror_sb_MSS.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/Actel/DirectCore/CoreResetP/7.1.100/rtl/vlog/core/coreresetp_pcie_hotreset.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/Actel/DirectCore/CoreResetP/7.1.100/rtl/vlog/core/coreresetp.v}
addfile -view RTL -lib COREAPB3_LIB -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vlog/core/coreapb3_muxptob3.v}
addfile -view RTL -lib COREAPB3_LIB -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vlog/core/coreapb3_iaddr_reg.v}
addfile -view RTL -lib COREAPB3_LIB -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/Actel/DirectCore/CoreAPB3/4.1.100/rtl/vlog/core/coreapb3.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/work/FineSteeringMirror_sb/FineSteeringMirror_sb.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/fpgapeekfifos/BuildNumber.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/crc_byte.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/crc_stream.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/crc_fifo.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/IBufP1.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/IBufP2.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/IBufP3.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/VariableClockDivider.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/SpiMasterQuad.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/OneShot.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/Ltc2378AccumQuad.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/PPSCount.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/UartRxRaw.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/UartRxExtClk.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/fifo_gen.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/gated_fifo.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/UartRxFifoExtClk.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/fifo_peek.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/gated_fifo_peek.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/UartRxFifoExtClkPeek.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/UartTx.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/UartTxFifoExtClk.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/ClockDivider.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/SpiMaster.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/SpiDac.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/SpiDacQuad.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/SpiMasterDual.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/include/fpga/SpiDeviceDual.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/fpgapeekfifos/Main.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {/home/summer/projects/CGraph/firmware/FineSteeringMirrorController/Liberopeekfifos/component/work/FineSteeringMirror/FineSteeringMirror.v}