name: FPGASim

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Install GHDL
        run: sudo apt-get update && sudo apt-get install -y ghdl
      - name: Run FPGA tests
        run: |
          cd include/fpga/testbenches
          make all
          make clean
        