name: Deploy Doxygen Docs to GitHub Pages

on:
    push:
        branches:
            - master
            - sfrinaldi/ci-github-pages
    pull_request:
        types: [opened,reopened,edited,synchronize]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            #- name: Generate Token
            #  id: generate-token
            #  uses: actions/create-github-app-token@v2
            #  with:
            #    app-id: ${{ vars.APP_ID }}
            #    private-key: ${{ secrets.APP_PRIVATE_KEY }}

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            
            - name: Install Dependencies
              run: |
                pip install sphinx sphinx-rtd-them ghp-import
                DEBIAN_FRONTEND=noninteractive apt install -y doxygen graphviz

            - name: Build Sphinx Docs
              run: |
                mkdir -p doxygen
                mkdir -p doxygen/Filterwheel/processor
                cd Filterwheel/processor/dox
                doxygen
                cd ../../../
                mkdir -p doxygen/FilterwheelTq144/fpga  
                cd FilterwheelTq144/fpga/dox
                doxygen 
                cd ../../../
                mkdir -p doxygen/FineSteeringMirrorController/processor
                cd FineSteeringMirrorController/processor/Main/dox
                doxygen 
                cd ../../../
                mkdir -p doxygen/FineSteeringMirrorController/fpga
                cd FineSteeringMirrorController/fpga/dox
                doxygen
                cd ../../../
                cd dox
                doxygen

            - name: Deploy GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              if: github.ref == 'refs/heads/main'
              with:
                github_token: ${{ secrets.GITHUB_TOKEN}}
                publish_dir: doxygen

            - name: Upload Pages
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: firmware-pages
                path: |
                    doxygen/*
            
