name: Deploy Doxygen Docs to GitHub Pages

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened,reopened,edited,synchronize]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.x'

            - name: Install Dependencies
              run: |
                sudo apt-get install doxygen graphviz -y

            - name: Build Doxygen Docs
              run: |
                bash local_deploy.sh

            - name: Prep for gh-pages
              run: |
                cd $GITHUB_WORKSPACE
                mkdir -p gh-pages
                mv doxygen/html/* gh-pages
                mv doxygen/FineSteeringMirrorController gh-pages
                mv doxygen/FilterwheelTq144 gh-pages
                mv doxygen/Filterwheel gh-pages
                cd $GITHUB_WORKSPACE

            - name: Deploy GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              if: github.ref == 'refs/heads/master'
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: gh-pages/

            - name: Upload Pages
              uses: actions/upload-artifact@v7
              if: always()
              with:
                name: firmware-pages
                path: |
                    gh-pages/*
